- trymito.io/components/FeatureRow/FeatureRow.tsx
- trymito.io/components/FeatureSection/FeatureSection.tsx
- trymito.io/pages/plans.tsx
This PR adds our two features that are coming soon, and labels them as such for clear communication. 
Also peep how I reorged the plans page data structures. Makes it easier to insert items into the feature sections, which I think is pleasant as it's gonna be a common modification. Previously, you had to modify two variables to do this. It's not a huge win, but I prefer it.
> trymito.io: add coming soon features, reorg for easy adding

- .github/workflows/lint-mitosheet-typescript.yml
- .github/workflows/test-mitoinstaller.yml
- .github/workflows/test-mitosheet-mypy.yml
- .github/workflows/test-mitosheet-python.yml
This just adds the actions that test and lint the mitosheet package. Notably, the deployment scripts are not included in here.
> actions: add testing and linting workflows for mitosheet

- .github/workflows/deploy-mitosheet-mitoinstaller.yml
- mitosheet/deployment/README.md
- mitosheet/deployment/bump_version.py
- mitosheet/deployment/deploy.py
Adds deployment scripts, and deployment action. 
Before merging this, we need to add the secrets to this Github repo that allow these actions to post to PyPi. Since I don't have access to PyPi rn, @aarondr77 the task falls to you. To do so:
1. Go to the Github secrets for our org here: https://github.com/organizations/mito-ds/settings/secrets/actions
2. Create a new org secret called `PYPI_API_TOKEN`. Set it equal to the value you get from PyPi (instructions here: https://pypi.org/help/#apitoken). Make sure to give it enough permissions to upload packages.
3. Add another secret, called `TEST_PYPI_API_TOKEN`, which you can get from test pypi. Otherwise, the same.
Then, you should be good to merge, and this should run correctly.
We'll have to test this once we merge it for the first time! …
> mitosheet: add deployment scripts and workflow

- mitosheet/mitosheet/api/graph/bar.py
- mitosheet/mitosheet/api/graph/box.py
- mitosheet/mitosheet/api/graph/get_graph.py
- mitosheet/mitosheet/api/graph/graph_utils.py
- mitosheet/mitosheet/api/graph/histogram.py
- mitosheet/mitosheet/api/graph/scatter.py
- mitosheet/mitosheet/column_headers.py
- mitosheet/mitosheet/errors.py
- mitosheet/mitosheet/parser.py
- mitosheet/mitosheet/step.py
- mitosheet/mitosheet/step_performers/bulk_old_rename/bulk_old_rename.py
- mitosheet/mitosheet/step_performers/bulk_old_rename/deprecated_utils.py
- mitosheet/mitosheet/step_performers/column_steps/change_column_dtype.py
- mitosheet/mitosheet/step_performers/column_steps/change_column_format.py
- mitosheet/mitosheet/step_performers/column_steps/delete_column.py
- mitosheet/mitosheet/step_performers/column_steps/rename_column.py
- mitosheet/mitosheet/step_performers/column_steps/reorder_column.py
- mitosheet/mitosheet/step_performers/column_steps/set_column_formula.py
- mitosheet/mitosheet/step_performers/drop_duplicates.py
- mitosheet/mitosheet/step_performers/filter.py
- mitosheet/mitosheet/step_performers/merge.py
- mitosheet/mitosheet/step_performers/pivot.py
- mitosheet/mitosheet/step_performers/set_cell_value.py
- mitosheet/mitosheet/step_performers/sort.py
- mitosheet/mitosheet/step_performers/step_performer.py
- mitosheet/mitosheet/tests/test_utils.py
- mitosheet/mitosheet/topological_sort.py
- mitosheet/mitosheet/transpiler/transpile_utils.py
- mitosheet/mitosheet/types.py
- mitosheet/mitosheet/utils.py
This makes no functional changes; it just edits types to make things more clear. Seeing List[ColumnID] is much more clear than List[str]!
In making these changes, this PR also catches a few bugs where we were treating column headers as strings when they had no right to be! It will continue to catch bugs for us in the future as well :-)
> mitosheet: add explicit types for ColumnHeader and ColumnID, for clarity

- mitosheet/mitosheet/errors.py
- mitosheet/mitosheet/mito_widget.py
- mitosheet/src/components/DefaultModal.tsx
- mitosheet/src/components/modals/ErrorModal.tsx
- mitosheet/src/types.tsx
- mitosheet/src/utils/classNames.tsx
@aarondr77 this is something you've been talking about for a while, so feast your eyes. Feel free to make it prettier / look better. 
Note that this is a workaround as we continue to improve our in place error handling; this does not want to stay forever!
Try as many errors as you can think of:
1. Invalid formulas
2. Invalid merge
3. Writing any formula in a sheet with the column header `0` <- this is in `small-datasets/small-excel`
4. And any more you can think of!
Note the goal here is to make sure none of our error infra broke; so some of the above don't trigger the error modal at all.
> mitosheet: have error modal display an traceback

- mitosheet/src/components/Mito.tsx
- mitosheet/src/components/elements/ErrorBoundary.tsx
- mitosheet/src/components/modals/ErrorModal.tsx
- mitosheet/src/components/toolbar/Toolbar.tsx
- mitosheet/src/data/documentationLinks.tsx
- mitosheet/src/utils/actions.tsx
See title.
Add this line somewhere in the toolbar, before the return statement: 
```
throw new Error('I crashed!');
```
Check that the log appears in Mixpanel!
No.
> error boundary: add basic error boundary to Mito to stop violent sheet crashes

- docs/getting-started/installing-mito/installing-mito-in-a-docker-container.md
- docs/misc/release-notes.md
- mitosheet/installer/mitoinstaller/__main__.py
- mitosheet/mitosheet/step_performers/column_steps/set_column_formula.py
The only really fixable bug from dogfooding. We still need to:
Not much here.
See new release notes.
> mitosheet: 10-22 release

- mitosheet/src/plugin.tsx
- mitosheet/src/widget.tsx
Per clients request, since when telemetry is off we don't have anything, we use just a comment in the analysis code block.
```
!python -m mitosheet turnofflogging
import mitosheet
mitosheet.sheet()
```
Then so some things, and make sure it replays. Then, turn on logging [!python -m mitosheet turnonlogging], and make sure it switches back + reads in correctly. Maybe switch back to logging off one more time, and make sure that direction works as well.
N/A
> mitosheet: improve analysis id to be private when telemetry is off

- .github/workflows/deploy-mitosheet-private.yml
- deployment/deploy.py
- mitosheet/mitosheet/mito_analytics.py
- mitosheet/mitosheet/mito_widget.py
- mitosheet/mitosheet/steps_manager.py
- mitosheet/mitosheet/tests/startup/test_startup.py
- mitosheet/mitosheet/user/location.py
- mitosheet/mitosheet/user/utils.py
- mitosheet/mitosheet/utils.py
- mitosheet/setup.py
- mitosheet/switch.py
NOTE: merge after mitosheet private!
1. Adds logging for how long ops take to run, in 10ths of a second
2. Add an explicit log for errors
3. Add log if DF names are not read in correctly
4. Add location log
Just check log to see processing time
Generate an invalid formula, and see if an explicit error log is generated
Comment out line 142 of Mito.tsx, so the names aren't read in correctly. Then, try and make an edit, and make sure the log gets generated.
1. Check in Python terminal (make sure in venv where jupyterlab is run from). Run
```
python3
from mitosheet.user.location import get_location
get_location()
```
Try running this when no labs/notebooks are running, and when they are
6. Test in Jlab
Start a Jlab, and run
```
from mitosheet.user.location import get_location
get_location() …
```
> Logging changes

- .gitignore
- mitoinstaller/mitoinstaller/installer_steps/final_installer_steps.py
- mitoinstaller/mitoinstaller/user_install.py
- mitosheet/src/components/Mito.tsx
Based on my investigation here: https://www.notion.so/trymito/Checking-on-New-Deployment-15670ee7011646c79cadef22bc71ba0c
I fixed these issues:
- Investigate the log('upgrading_mitosheet_labextension', log from the installer
- Figure out why the installer_finished or whatever log isn’t being used... - we needed to flush the changes
- Added a rendered sheet log - so we know if a sheet is rendering. Doh!
Test the new log (and that the installer finished log is working) by running installer.
No.
> Fixup minor issues from last deployment [there aren't many]

- mitoinstaller/mitoinstaller/__main__.py
- mitoinstaller/mitoinstaller/commands.py
- mitoinstaller/mitoinstaller/install.py
- mitoinstaller/mitoinstaller/installer_steps/final_installer_steps.py
- mitoinstaller/mitoinstaller/installer_steps/initial_installer_steps.py
- mitoinstaller/mitoinstaller/installer_steps/installer_step.py
- mitoinstaller/mitoinstaller/installer_steps/installer_step_utils.py
- mitoinstaller/mitoinstaller/installer_steps/mitosheet_installer_steps.py
- mitoinstaller/mitoinstaller/log_utils.py
- mitoinstaller/mitoinstaller/user_install.py
- mitoinstaller/tests/test_upgrades.py
This PR is high priority, as it does a few things:
1. It cleans up our logging in our installer - so we can actually tell what is happening. Things were very messy and inconsistent before, which mostly meant it's pretty much impossible to figure out when/why things are failing.
2. Fixes a bug where many install attempts were not logged (namely, those where users never ran an import mitosheet call), because the identify function was not calling the underlying analytics.identify due to a non-updated guard to stop profile overwriting.
Notably, to do so, I further simplify the architecture of the installer. It's pretty damn simple now, and should be really understandable. As before, I'm continually realizing that simplicity is of the _upmost_ importance here, because debugging it otherwise is …
> mitoinstaller: major cleanup, bug fixes with identify

- mitosheet/mitosheet/step_performers/filter.py
- mitosheet/mitosheet/tests/steps_performers/test_filter.py
- mitosheet/src/components/taskpanes/ControlPanel/FilterAndSortTab/filter/filterConditions.tsx
- mitosheet/src/types.tsx
Closes #138 
See tests. Test in Mito. Note that on Mixed type data, our current string filtering does not perform well when combining different types into multiple filter conditions (namely, `na=None` is not how we combine things in the multi-filter conditions - where we type cast). 
A note on the tests for the "combining filter conditions" for future reference:
1. We no longer test transpired code directly (I think when these were written, we used to do so).
2. The string condition aggregation isn't tested at all, let alone with mixed data types.
Instead of fixing these issues, I opened an issue here: https://github.com/mito-ds/monorepo/issues/139
Nope.
> mitosheet: add starts with and endswith string filters

- docs/how-to/graphing.md
- mitosheet/mitosheet/step_performers/graph/graph_utils.py
- mitosheet/mitosheet/step_performers/graph/plotly_express_graphs.py
- mitosheet/src/components/taskpanes/Graph/AxisSection.tsx
- mitosheet/src/components/taskpanes/Graph/GraphSidebar.tsx
See title. I went through plotly express and added every graph that supports and x and y axis: https://plotly.com/python/plotly-express/.
In the future, we can extend to support many more of these graph types (we just need to change up the interface to communicate to the user which params they need to pass).
The main question I have: what order should we put these in? We should put them in a good default order, and then standardize across the codebase (e.g. in the definitions and if statements). @aarondr77 if you wanna go for this, do it!
Test new graph types, and generated code works!
Yes, a list of graph types are added.
> mitosheet: add 6 new graph types, remove ctas and limitations

- mitosheet/src/components/Mito.tsx
- mitosheet/src/components/footer/Footer.tsx
- mitosheet/src/components/taskpanes/taskpanes.tsx
I don't have a good way of doing this one. We want:
1. To update the graph if the underlying data has been edited
2. To not update the graph when the user opens it otherwise.
I don't think both of these things are possible, without a backend implementation of "refresh_dependent_graphs" - which IMO would be really horribly annoying and not worth it. Thoughts?
> Graph bug fixes from usability test

- mitosheet/mitosheet/errors.py
- mitosheet/mitosheet/updates/replay_analysis.py
- mitosheet/src/plugin.tsx
Previously, if a user replayed an analysis that they didn't have access to in their .mito folder, it would completely clear all of their generated code. This isn't generally an issue for users, but I spoke with a user that is sharing notebooks back and forth via OneDrive and was concerned about deleting their colleague's work. 
Now, if the analysis doesn't exist, we just give an error that explains what is happening (along with the log you've already created) and we don't clear the analysis. 
1. Create an analysis
2. Change the analysis ID
3. Rerun the analysis and notice that an error appears instead of clearing out the generated code. 
> mitosheet: don't clear analysis if it doesn't exist

- .github/workflows/test-mitoinstaller.yml
- mitoinstaller/mitoinstaller/log_utils.py
- mitosheet/mitosheet/errors.py
Makes it so we get no path unnecessary path information in our tracebacks.
Generate error logs with installer and with the mitosheet package, and make sure they only have the last file name. After we merge them (NOTE: after we do the deploy), let's test this on windows as well!
No.
> Strip path from tracebacks

- mitosheet/mitosheet/mito_analytics.py
Per this investigation, adds a log so we know what version of notebooks to build for: https://www.notion.so/trymito/Jupyter-Versions-640b9f8459c04daa9b4ffb7420d920d8
Test it logs notebook version.
> mitosheet: log notebook version

- mitosheet/mitosheet/step_performers/column_steps/change_column_dtype.py
- mitosheet/mitosheet/tests/steps_performers/column_steps/test_change_column_dtype.py
- mitosheet/src/components/Mito.tsx
- mitosheet/src/components/footer/DataSheetTabActions.tsx
- mitosheet/src/components/footer/Footer.tsx
- mitosheet/src/components/footer/SheetTab.tsx
- mitosheet/src/components/taskpanes/ControlPanel/FilterAndSortTab/DtypeCard.tsx
- mitosheet/src/components/taskpanes/Graph/AxisSection.tsx
- mitosheet/src/components/taskpanes/Graph/graphUtils.tsx
- mitosheet/src/pro/download/ExcelFormatSection.tsx
Makes the changes to fix errors and sheet crash reduction found in this investigation: https://www.notion.so/trymito/3-20-22-86a74cf19dc946379f6f60ac109fde53
I did this process a bit different than described in the initial doc. For sheet crashing, looked at the last week of sheet crashes. Turns out these are much harder to get to the bottom of now, as I've got most of the easy ones, so many of them simply cannot be backtracked (and we need to think of other strats for avoiding these issues).
For errors, the categorization I proposed initially (our fault, theirs, etc) seemed mostly not helpful. With 90% of errors, we know about them, they are from user input, or we're handling them in some way already. The other 10% were clear "needs investigation."
I like this new structure of (sheet …
> Error and sheet crash reduction

- mitosheet/mitosheet/state.py
- mitosheet/mitosheet/step_performers/bulk_old_rename/bulk_old_rename.py
- mitosheet/mitosheet/step_performers/column_steps/add_column.py
- mitosheet/mitosheet/step_performers/column_steps/change_column_dtype.py
- mitosheet/mitosheet/step_performers/column_steps/change_column_format.py
- mitosheet/mitosheet/step_performers/column_steps/delete_column.py
- mitosheet/mitosheet/step_performers/column_steps/rename_column.py
- mitosheet/mitosheet/step_performers/column_steps/reorder_column.py
- mitosheet/mitosheet/step_performers/column_steps/set_column_formula.py
- mitosheet/mitosheet/step_performers/dataframe_steps/dataframe_delete.py
- mitosheet/mitosheet/step_performers/dataframe_steps/dataframe_duplicate.py
- mitosheet/mitosheet/step_performers/dataframe_steps/dataframe_rename.py
- mitosheet/mitosheet/step_performers/drop_duplicates.py
- mitosheet/mitosheet/step_performers/filter.py
- mitosheet/mitosheet/step_performers/graph_steps/graph.py
- mitosheet/mitosheet/step_performers/graph_steps/graph_delete.py
- mitosheet/mitosheet/step_performers/graph_steps/graph_duplicate.py
- mitosheet/mitosheet/step_performers/graph_steps/graph_rename.py
- mitosheet/mitosheet/step_performers/import_steps/excel_import.py
- mitosheet/mitosheet/step_performers/import_steps/simple_import.py
- mitosheet/mitosheet/step_performers/merge.py
- mitosheet/mitosheet/step_performers/pivot.py
- mitosheet/mitosheet/step_performers/set_cell_value.py
- mitosheet/mitosheet/step_performers/sort.py
Makes us copy less dataframes. This is pretty much a strict improvement in performance, as in most cases we move from a deep copy of dataframes to shallow ones for most dataframes. In the wild, when the user is working on large datasets, I would not be surprised if this sped up all operations by 2x or so (that's a random guess though). 
To see what I meant with issue with benchmarking in Mixpanel, see here: https://mixpanel.com/s/22suFM
Try and mess with it. I've tried pretty much every configuration, and cannot get it to give me data in any useful format...
Given that this is just a strict improvement, I think we should deploy. I do think we need to rethink our benchmarking strategy at some point to work around these mixpanel limitations. 
Make sure the ops work, boi.
No.
> mitosheet: make us copy less dataframes

- mitosheet/mitosheet/parser.py
- mitosheet/mitosheet/step_performers/pivot.py
- mitosheet/mitosheet/utils.py
- mitosheet/src/components/endo/widthUtils.tsx
- Only displays the first 1500 column in the pandas dataframe to make Mito snappier! 
- Adds logging for the pandas performance warning that occurs when creating a really large pivot table, so that we can figure out how much guidance is appropriate to provide to users. 
- Dramatically improves the efficiency of building the column evaluation graph by short circuiting if the column has no formula!
1. Create a pivot table that has over 1500 columns, but not enough data to crash the sheet -- you can achieve this by adding a column and a value, with no row. See that the pivot table loads quickly and that if you rename, delete, or set the formula of a column, the operation finishes in about 30-60 seconds.  
2. Create a new pivot table with a row and column that each have a large number of …
> mitosheet: only display the first 1500 columns

- mitosheet/src/components/taskpanes/PivotTable/PivotTableKeySelection.tsx
- mitosheet/src/components/taskpanes/PivotTable/PivotTaskpane.tsx
Add a little hint that tells the user to using only rows and values in their pivot table. 
> mitosheet: add hint for pivot tables

- mitosheet/src/components/endo/ColumnHeader.tsx
Always open the filter / sort tab when the filter icon or dtype icon is clicked. 
Test it! 
No.
> mitosheet: always open filter tab on filter icon click

- docs/misc/release-notes.md
- mitosheet/src/components/Mito.tsx
- mitosheet/src/components/modals/ReplayAnalysisModals.tsx
- mitosheet/src/components/modals/modals.tsx
Now you get offered support + create a new analysis in both cases of failure, which is nice. The other change I merged into dev already was a minor change to the pivot table language to make it fit on one line.
Test that the two types of failure of replaying (nonexistent, failure) give correct modals.
Adds release notes.
> mitosheet: unify replay analysis errors

- mitosheet/src/components/taskpanes/Concat/ConcatTaskpane.tsx
- mitosheet/src/components/taskpanes/ControlPanel/ControlPanelTaskpane.tsx
- mitosheet/src/components/taskpanes/ControlPanel/FilterAndSortTab/filter/FilterCard.tsx
What are your thoughts on when the original number of rows variable in the filter taskpane should update now that you see it? I'm leaning towards ideally it would update when you either 1) open the taskpane or 2) add/remove a filter condition. 
However, there's a lot more complexity that comes with condition 2 that I'm not sure is worth it. Let me know your thoughts. 
Concat files together and make sure that if they have all the same column headers, then the text says they are all included. If a column header is not shared, make sure it shows up in the text. 
Filter and make sure the number of values that it says are removed is correct. 
No.
> Communicate Result

- mitosheet/src/components/taskpanes/DropDuplicates/DropDuplicates.tsx
Removes the confusion caused by drop duplicates automatically deduplicating the data when the taskpane is open by starting the taskpane with no columns selected. This means that no data is dropped until the user configured the taskpane + they have a better idea of how to get back to a state where no duplicates are dropped. 
No.
> mitosheet: make drop duplicates start with no columns selected

- mitosheet/src/components/taskpanes/Concat/ConcatTaskpane.tsx
- mitosheet/src/components/taskpanes/Graph/GraphSetupTab.tsx
- mitosheet/src/utils/actions.tsx
See work here: https://www.notion.so/trymito/4-16-22-b05459f5e10d47dd9839c377d70ef8f2. The main fix is a sheet crashing bug if you opened concat with no data. Only one user hit it so far, so nbd, but we can do a better job testing for no data in the future.
NOTE: the number of sheet crashing bugs is down 4x from a month ago. That's awesome.
Test changed things from the doc!
Nope.
> Sheet crashing error reduction

- docs/getting-started/installing-mito/README.md
- docs/getting-started/installing-mito/common-install-errors.md
- docs/getting-started/installing-mito/installing-mito-in-a-docker-container.md
- docs/getting-started/overview-of-the-mitosheet.md
- docs/how-to/creating-a-mitosheet/README.md
- docs/how-to/importing-data-to-mito.md
- docs/misc/faq.md
- mitoinstaller/mitoinstaller/commands.py
- mitoinstaller/mitoinstaller/create_startup_file.py
- mitoinstaller/mitoinstaller/installer_steps/final_installer_steps.py
- mitoinstaller/mitoinstaller/installer_steps/initial_installer_steps.py
- mitoinstaller/mitoinstaller/installer_steps/mitosheet_installer_steps.py
- mitoinstaller/mitoinstaller/jupyter_utils.py
- mitoinstaller/tests/test_installs.py
- mitoinstaller/tests/test_launch_jupyter.py
- mitoinstaller/tests/test_static_user_id.py
- mitosheet/mitosheet.json
- mitosheet/setup.py
- trymito.io/components/CTAButtons/CTAButtons.tsx
- trymito.io/pages/index.tsx
- trymito.io/pages/plans.tsx
This PR follows this spec: https://www.notion.so/trymito/Notebooks-Installer-Specification-ed28937abcba413aa27cff012e6274ff. It simplifies the logic for checking which to launch, which I think is fine for now! We can improve on v2 - let's get this out ASAP!
Once we get this merged and dogfooded, we're good to ready to deploy notebooks!
Should launch Notebook:
```
deactivate; rm -rf venv; python3 -m venv venv; source venv/bin/activate && pip install -r requirements.txt; pip install notebook; python -m mitoinstaller install --test-pypi
```
Should launch Lab:
```
deactivate; rm -rf venv; python3 -m venv venv; source venv/bin/activate && pip install -r requirements.txt;  python -m mitoinstaller install --test-pypi
```
Feel free to test other configurations.
See new docs, and also changes to …
> Add notebook installer

- mitoinstaller/mitoinstaller/installer_steps/final_installer_steps.py
- mitoinstaller/mitoinstaller/jupyter_utils.py
See Zulip. We should launch them into notebook if they are running notebook.
```
deactivate; rm -rf venv; python3 -m venv venv; source venv/bin/activate && pip install -r requirements.txt; pip install jupyterlab; jupyter notebook
```
Then, run the local install command, and you should launch in notebook.
Nope.
> mitoinstaller: get smarter about when we launch notebooks

- mitosheet/src/components/endo/ColumnHeader.tsx
- mitosheet/src/components/endo/ColumnHeaderDropdown.tsx
This adds a set of action to the column header. Let me know your thoughts!
The only issue with this is that the open column header dropdown is that it's not in global state so that you can open multiple at once. We can refactor this if we want, but I am kinda ok with it. let me know ur thoughts.
Try the actions! 
N/A
> mitosheet: add right click on column header

- mitosheet/css/footer.css
- mitosheet/css/sitewide/scroll.css
- mitosheet/src/components/footer/Footer.tsx
Makes sure that there is always a scrollbar for the user to scroll the sheet tabs even if they don't have a trackpad by using the [scollbar-gutter](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter) css property. 
However, this doesn't work on IE or Safari. 
Note: The scrollbar-gutter property only effects computers whose scrollbars are not floating. On Macs, the scrollabrs float, so this has no effect.  Which unfortunately means the footer is different on macs and windows. 
Windows JupyterLab:
Windows Notebook: 
If there is no overflow, then it just looks normal:
Note if any new documentation needs to addressed or …
> add scrollbar to tabs

- mitoinstaller/mitoinstaller/commands.py
Addresses #308 
Try passing it through (and print out command), it should be there. It also should work locally for you now @aarondr77 after we deploy this (as long as you add this flag!).
N/A.
> mitoinstaller: allow users to pass through no cache dir

- mitosheet/src/components/Mito.tsx
- mitosheet/src/components/footer/Footer.tsx
- mitosheet/src/components/footer/SheetTab.tsx
Makes sure that the cell editor is not open in the graph. Previously, you could open the cell editor, switch to a graph taskpane, and the cell editor would still be open.
> mitohseet: close cell editor when opening graph tab

- mitosheet/mitosheet/code_chunks/step_performers/column_steps/split_text_to_columns_code_chunk.py
- mitosheet/src/components/endo/EmptyGridMessages.tsx
- mitosheet/src/components/endo/EndoGrid.tsx
- mitosheet/src/components/endo/sheetViewUtils.tsx
- mitosheet/src/components/endo/utils.tsx
- mitosheet/src/components/endo/visibilityUtils.tsx
- mitosheet/src/components/footer/DataSheetTabActions.tsx
- mitosheet/src/components/footer/GraphSheetTabActions.tsx
- mitosheet/src/types.tsx
- mitosheet/src/utils/copy.tsx
- Fix bug where if you selected the entire dataframe, including all indexes and column headers, copy didn't work. 
- Fix bug with replay anlaysis documented here: https://github.com/mito-ds/monorepo/issues/338
- Reverting scroll saving (because it was so buggy).
- Fix bug where the delimiters where confusingly labeled in comments and step descriptions
Test scrolling, and copy.
N/A.
> Dogfood 5 31

- mitosheet/mitosheet/tests/test_mito_widget.py
- mitosheet/mitosheet/utils.py
Fixes a warning we were getting with SettingWithCopyWarning in the utils file, which you can read about here: https://www.dataquest.io/blog/settingwithcopywarning/
It was an invalid warning (it wasn't real), but rather than silencing it I just moved where we copy to fix it up. No functionality changes.
Had to do this because warnings on Notebooks appear in the notebook rather than printed elsewhere, which looks awful.
Testing nothing broke.
N/A.
> mitosheet: remove setting on warnings errors

- mitoinstaller/mitoinstaller/commands.py
- mitoinstaller/mitoinstaller/installer_steps/mitosheet_installer_steps.py
This adds the option for users to do a user install with the mitoinstaller, which hopefully will address.
This is very hard to test. Here's what you can do:
1. Change `Consider using the `--user` option or check the permissions.` to `KeyboardInterrupt`, and then press control + c during this step (and then see if you enter the condition correctly). 
2. Confirm that you get an error when trying to do a user install inside a venv - this confirms that we are at least trying to do a user install.
This might lead to more bugs with notebook installs or something, but it's very hard to say before we deploy. Given how uncommon this is, I think we should sanity check per above and then see how common this is in the future before doing much more. We know user installs will work in many cases, so …
> mitosheet: add user install option

- mitosheet/src/components/endo/ColumnHeader.tsx
- mitosheet/src/components/endo/ColumnHeaderDropdown.tsx
Delete all of the selected columns when using the column header dropdown. This is what users expect. 
> mitosheet: delete selected columns

- mitosheet/mitosheet/step_performers/graph_steps/graph.py
- mitosheet/mitosheet/step_performers/graph_steps/plotly_express_graphs.py
- mitosheet/mitosheet/tests/step_performers/graph_steps/test_graph.py
- mitosheet/mitosheet/tests/test_utils.py
- mitosheet/src/components/taskpanes/Graph/GraphStyleTab.tsx
- mitosheet/src/components/taskpanes/Graph/graphUtils.tsx
- mitosheet/src/types.tsx
Adds the ability to set [Plotly's axis type ](https://plotly.com/python/axes/) following this [specification](https://www.notion.so/trymito/Log-graph-transformations-d5b4b08a3cf74c25a25c37b9b828b860) 
Create some graphs. 
See proposal for doc changes [here](https://app.gitbook.com/o/-MS4px_3crWEYYdbNPU8/s/-MP_U5ZCmiamDOXEOOTC/~/changes/n37dfGIxRPBQd5cYc79g/how-to/graphing). Merge when releasing.
> mitosheet: add axis type transformations to graph

- mitosheet/src/hooks/useCopyToClipboard.tsx
- mitosheet/src/utils/actions.tsx
- mitosheet/src/utils/copy.tsx
If a user was:
1. One http
2. On a remote serve (aka not local host)
This is considered a non-secure context, and the navigator.clipboard api is disabled. In this case, we need to copy to the clipboard differently. 
Add a `&& false` to the first condition. Make sure it still copies! Not sure how to test it better than this...
N/A.
> mitosheet: make copy and paste work in non-secure contexts

- mitoinstaller/mitoinstaller/commands.py
- mitoinstaller/mitoinstaller/experiments/experiment_utils.py
- mitoinstaller/mitoinstaller/install.py
- mitoinstaller/mitoinstaller/installer_steps/__init__.py
- mitoinstaller/mitoinstaller/installer_steps/final_installer_steps.py
- mitoinstaller/mitoinstaller/installer_steps/initial_installer_steps.py
- mitoinstaller/mitoinstaller/installer_steps/installer_step.py
- mitoinstaller/mitoinstaller/installer_steps/installer_step_utils.py
- mitoinstaller/mitoinstaller/installer_steps/mitosheet_installer_steps.py
- mitoinstaller/mitoinstaller/log_utils.py
- mitoinstaller/mitoinstaller/print_utils.py
- mitoinstaller/mitoinstaller/user_install.py
- mitoinstaller/tests/test_user_json.py
- mitosheet/mitosheet/experiments/experiment_utils.py
- mitosheet/mitosheet/telemetry/telemetry_utils.py
- mitosheet/mitosheet/tests/user/conftest.py
- mitosheet/mitosheet/tests/user/test_user.py
- mitosheet/mitosheet/user/upgrade.py
Implements: https://www.notion.so/trymito/Faster-Installer-Investigation-adc3de7829f14db9b75d145d60fcea42
Also implements all the AB test infrastructure for the installer, which is sweet!
```
rm ~/.mito/user.json; deactivate; rm -rf venv; python3 -m venv venv; source venv/bin/activate; pip install -r requirements.txt; python -m mitoinstaller install
```
Things to test:
1. Logs generate correctly in both versions.
2. Logs generate correct when there are errors in steps (insert random Throws in steps)
3. You can keyboard cancel.
4. Both Mac and windows.
Nothing different!
> Installer communication

- mitosheet/src/components/Mito.tsx
- mitosheet/src/components/taskpanes/PivotTable/PivotTaskpane.tsx
- mitosheet/src/components/taskpanes/PivotTable/pivotUtils.tsx
- mitosheet/src/components/taskpanes/taskpanes.tsx
- mitosheet/src/jupyter/api.tsx
- mitosheet/src/types.tsx
- mitosheet/src/utils/actions.tsx
This PR fixes a bug I discovered while working on the new TTV checklist. Namely, if you switched to a sheet b/c of an open pivot table, you can get a race condition that leads to the wrong param being used as the sheet index.
This bug isn't manifesting in deployed code, but based on the fact adding a checklist made it happen means it might, so let's get this fixed ASAP!
Use the pivot table!
N/A.
> mitosheet: fix up some unrealized race conditions

- mitoinstaller/mitoinstaller/experiments/experiment_utils.py
- mitoinstaller/mitoinstaller/install.py
- mitoinstaller/mitoinstaller/user_install.py
- mitosheet/mitosheet/experiments/experiment_utils.py
In trying to understand this experiment. I upgraded an old mitosheet and the upgrade process failed with the error `File "/Users/aarondiamond-reivich/Desktop/mito-upgrade-test/venv/lib/python3.8/site-packages/mitoinstaller/user_install.py", line 73, in try_create_user_json_file
if new_experiment is not None and updated_user_json['experiment']['experiment_id'] != new_experiment['experiment_id']:
KeyError: 'experiment'`
To recreate it:
1. Delete your user.jsoin
2. Run `pip install mitosheet=0.1.430 --no-cache-dir`
3. Go through the signup flow. 
4. Then kill the server and try to upgrade Mito by running: `python -m pip install mitoinstaller --upgrade` followed by `python -m mitoinstaller upgrade`
On the actual upgrade command the error appears. Also, importantly note that it doesn't show up …
> mitoinstaller: make sure experiment is in user.json

- mitosheet/mitosheet/api/get_column_summary_graph.py
- mitosheet/mitosheet/step_performers/graph_steps/graph.py
- mitosheet/mitosheet/step_performers/graph_steps/graph_utils.py
- mitosheet/src/jupyter/api.tsx
1. Detects if Plotly is not loaded, and loads from the backend. This makes Plotly work when it is offline.
2. Parses the Plotly generated code better.
1. Test graphing normally.
2. Open console and `delete window.Plotly`, and make sure graphing still works (and that window.Plotly gets redefined after 1 new graph is made)
N/A.
> Make Plotly work offline

- .github/workflows/deploy-mitosheet-private.yml
- mitosheet/mitosheet/telemetry/telemetry_utils.py
- mitosheet/mitosheet/user/utils.py
- mitosheet/setup.py
- mitosheet/src/components/checklists/Checklist.tsx
- mitosheet/switch.py
Check that it undoes the changes here: https://github.com/mito-ds/monorepo/pull/407/files
And that it activates pro. 
Test this by running the switch, and actually setting up the `mitosheet-private` package. **I would reccomend editing the macsetup.sh script to switch to the mitosheet-private package, and then just running that. It makes life much easier.**
No.
> mitosheet: add back mitosheet-private package

- mitoinstaller/setup.py
Adds link to github in mitoinstaller/setup.py
I think this is required for some companies to verify open source packages, as requested by a user [here](https://github.com/mito-ds/monorepo/discussions/441)
> Add missing github link

- mitosheet/mitosheet/code_chunks/postprocessing/set_dataframe_format_code_chunk.py
Uses `.head` on the styler when it is needed for performance.  
Format a very large dataframe and check the styler generated code.
> mitosheet: use .head on styler if too many rows

- mitosheet/setup.py
There is a newly released version of ipywidgets (8.0.1) on 8/18, which is incompatible with our pinned version of jupyterlab-widgets~=1.0.0. So the installation finishes, but then Mito won't load. Updating our setup.py file to allow for the new version of jupyterlab-widgets (3.0.2) created a big ugly javascript error, but it might work if I redeploy to test-pypi so the mitosheet package has new dependencies. I'm not sure why we pinned the jupyterlab-widgets to version 1.
> mitosheet: fix dependency issues with new ipywidgets

- mitosheet/setup.py
Pins ipywidgets and jupyter-widgets packages to stable version with Mito. 
See errors caused [here](https://github.com/mito-ds/monorepo/issues/446)
Note [here](https://ipywidgets.readthedocs.io/en/8.0.1/migration_guides.html) works that we need to do to migrate to ipywidgets 8.0
> mitosheet: pin to stable ipywidgets mito version

- mitosheet/mitosheet/code_chunks/postprocessing/set_dataframe_format_code_chunk.py
- mitosheet/mitosheet/tests/step_performers/test_set_dataframe_format.py
- mitosheet/src/components/endo/GridData.tsx
- Mito appears to be 0 indexed, but the css selector used in the styler is 1 indexed. To keep them consistent, we flip the even and odd strings in the selector. 
Set the background color of the even and odd rows and make sure they match in the sheet & styler
> Dogfood 8-25

- mitosheet/package.json
- mitosheet/setup.py
- mitosheet/src/jupyter/widget.tsx
- mitosheet/src/plugin.tsx
- mitosheet/switch.py
We've observed users installing Mito on Python 3.10+ run into the same issues over and over. 
```
$ python -m mitoinstaller install --no-cache-dir
Starting install...
Upgrade mitoinstaller
Setting up environment
Check dependencies
Remove mitosheet3 if present
Install mitosheet
Activate extension
Traceback (most recent call last):
File "/Users/aarondiamond-reivich/opt/anaconda3/envs/mitoenv/lib/python3.10/site-packages/mitoinstaller/installer_steps/installer_step.py", line 44, in execute
self.execution_function()
File "/Users/aarondiamond-reivich/opt/anaconda3/envs/mitoenv/lib/python3.10/site-packages/mitoinstaller/installer_steps/mitosheet_installer_steps.py", line 77, in install_step_mitosheet_activate_notebook_extension
run_command([sys.executable, "-m", 'jupyter', 'nbextension', …
```
> Support Ipywidgets 8.0 to support Python 3.10

- mitosheet/mitosheet/errors.py
- mitosheet/mitosheet/step_performers/pivot.py
Just run `bash dev/macsetup.sh` and then test Mito to see if this works with a new version of pandas. 
Notably, since we now limit the type of aggregation the users can do on the frontend, we quite literally have not had a user hit this error path in the last 30 days: (see here: https://mixpanel.com/s/4yOuoY) so we can safely remove this error.
See above.
N/A.
> mitosheet: remove unnecessary error catch

- mitoinstaller/mitoinstaller/experiments/experiment_utils.py
- mitosheet/mitosheet/experiments/experiment_utils.py
This is a much better easier hack than the other hack we used to remove the experiment -- I'm super happy with this simplification!
We def need to iterate the AB test infrastructure, but given that we're using it, pretty low priority! I also noted that the experiment ended today in the tracker, so we don't get confused when it stops!
Test you get B!
No.
> mitosheet: make experiment always go to B

- mitosheet/mitosheet/code_chunks/postprocessing/set_dataframe_format_code_chunk.py
- mitosheet/mitosheet/step_performers/filter.py
- mitosheet/mitosheet/utils.py
- mitosheet/src/components/taskpanes/ConditionalFormatting/ConditionalFormattingCard.tsx
1. Fixes bug with some filter conditions leading to incorrectly conditional formats (and gives comment if this is the case in generated code). Feel free to rephrase comment.
2. Changes `filter` -> `condition` in the conditional format, as this is much more clear.
> mitosheet: cleanup per jakes usability test

- mitosheet/mitosheet/step_performers/graph_steps/plotly_express_graphs.py
- mitosheet/src/components/elements/TextButton.tsx
- mitosheet/src/components/taskpanes/Graph/GraphExportTab.tsx
- mitosheet/src/components/taskpanes/Graph/GraphSidebar.tsx
Per spec: https://www.notion.so/trymito/Download-graph-as-HTML-d43470a091e7465d98c8b705e0885364
Takes a slightly simpler approach of just appending the export code on the frontend, which is nice methinks!
Can you think of better text for these buttons?
Test both export options.
Minor updates necessary.
> mitosheet: add different export options for graphs

- mitosheet/mitosheet/code_chunks/step_performers/column_steps/change_column_dtype_code_chunk.py
- mitosheet/mitosheet/column_headers.py
- mitosheet/mitosheet/saved_analyses/step_upgraders/change_column_dtype.py
- mitosheet/mitosheet/saved_analyses/upgrade.py
- mitosheet/mitosheet/step_performers/column_steps/change_column_dtype.py
- mitosheet/mitosheet/tests/saved_analyses/test_upgrade.py
- mitosheet/mitosheet/tests/step_performers/column_steps/test_change_column_dtype.py
- mitosheet/mitosheet/tests/step_performers/test_pivot.py
- mitosheet/mitosheet/tests/test_format.py
- mitosheet/mitosheet/tests/test_step_format.py
- mitosheet/mitosheet/tests/test_utils.py
- mitosheet/src/components/Mito.tsx
- mitosheet/src/components/icons/DtypeIcon.tsx
- mitosheet/src/components/taskpanes/ControlPanel/FilterAndSortTab/DtypeCard.tsx
- mitosheet/src/components/toolbar/Toolbar.tsx
- mitosheet/src/jupyter/api.tsx
- mitosheet/src/types.tsx
- mitosheet/src/utils/actions.tsx
Implements: https://www.notion.so/trymito/Bulk-change-dtype-ea4de1d94c1b4f669bc8746568a8c2ad
There is one minor complexity: we can't really easily generate a single line of code too easily. It's not the most complicated heuristic to generate less lines of code, but it does get complex pretty quickly. 
I attempted implementing it, and it blew up to about 60 lines of pretty complex code - it's just really tricky b/c (for example), our conversion functions don't all allow you to pass a dataframe rather than just a single column header (e.g. the `to_float_series` function). This then requires complex logic about reasoning when you can group things, which seems both very complex and very error prone. 
Feel free to take a shot at it if you want to get a feel for it. I spent 20 minutes on all …
> Bulk change dtype

- mitosheet/package.json
- mitosheet/setup.py
- mitosheet/src/jupyter/widget.tsx
- mitosheet/switch.py
Moves from ipywidgets 8 -> 7 since ipywidgets 7 has been patched to support Python 3.10
See tests below. This is tested on
- All major versions of Python from 3.6 -> 3.10
- ipywidgets 7.6.3 and 7.7.2
- jupyterlab-widgets 1.0.2
- Notebook/Lab
- Windows/Mac
> Ipywidget 7

- mitosheet/mitosheet/api/api.py
- mitosheet/mitosheet/api/get_csv_files_metadata.py
- mitosheet/mitosheet/api/get_imported_files_and_dataframes_from_current_steps.py
- mitosheet/mitosheet/code_chunks/step_performers/import_steps/excel_import_code_chunk.py
- mitosheet/mitosheet/code_chunks/step_performers/import_steps/simple_import_code_chunk.py
- mitosheet/mitosheet/errors.py
- mitosheet/mitosheet/mito_widget.py
- mitosheet/mitosheet/preprocessing/preprocess_read_file_paths.py
- mitosheet/mitosheet/step_performers/import_steps/excel_import.py
- mitosheet/mitosheet/step_performers/import_steps/simple_import.py
- mitosheet/mitosheet/telemetry/telemetry_utils.py
- mitosheet/mitosheet/tests/decorators.py
- mitosheet/mitosheet/tests/step_performers/import_steps/test_excel_import.py
- mitosheet/mitosheet/tests/step_performers/import_steps/test_simple_import_step.py
- mitosheet/mitosheet/tests/test_ts_types.py
- mitosheet/mitosheet/tests/test_utils.py
- mitosheet/mitosheet/tests/updates/test_clear.py
- mitosheet/mitosheet/tests/updates/test_update_existing_import.py
- mitosheet/mitosheet/user/utils.py
- mitosheet/src/components/import/CSVImportConfigScreen.tsx
- mitosheet/src/components/import/FileBrowser/FileBrowser.tsx
- mitosheet/src/components/import/FileBrowser/FileBrowserBody.tsx
- mitosheet/src/components/import/XLSXImportConfigScreen.tsx
- mitosheet/src/components/taskpanes/FileImport/FileImportTaskpane.tsx
- mitosheet/src/components/taskpanes/FileImport/XLSXImportConfigTaskpane.tsx
- mitosheet/src/components/taskpanes/UpdateImports/UpdateImportsTaskpane.tsx
- mitosheet/src/types.tsx
- mitosheet/src/utils/packageVersion.tsx
- Adds the `decimal` configuration option to excel and csv imports
- Adds the `skiprows`configuration options to csv imports
- Refactors some of the simple import and excel import code to make adding params a bit easier in the future
- Logs user's pandas version as `version_pandas`
- Moves the package checking infrastructure to the frontend so we can just check it where we need it instead of having to continually add to the UserProfile.
Note: `decimal` was only added to read_excel in version 1.4 of pandas, so I only display that configuration option in the XLSX config taskpane when the user is post 1.4. 
- See the tests
- Import files using `dev` and then switch to this branch and make sure imports still work
- Make sure that the `decimal` config is only available in the Excel import …
> Import config improvements

- mitosheet/README.md
- mitosheet/dev/jswatch.sh
- mitosheet/dev/realinstall.sh
- mitosheet/dev/testinstall.sh
- mitosheet/mitosheet/mito_config.py
- mitosheet/mitosheet/mito_widget.py
- mitosheet/mitosheet/step_performers/import_steps/dataframe_import.py
- mitosheet/mitosheet/telemetry/telemetry_utils.py
- mitosheet/mitosheet/tests/test_mito_config.py
- mitosheet/mitosheet/tests/test_ts_types.py
- mitosheet/mitosheet/user/create.py
- mitosheet/mitosheet/user/utils.py
- mitosheet/src/types.tsx
- mitosheet/switch.py
- Moves the mito-configuration approach to using environment variables instead of the mitosheet-helper-config package. 
- Also spells the word `environment` correctly all over the codebase, lol. 
Note that if you create the environment variables in the notebook and then refresh the kernel the environment variables are no longer set. As per the investigation below: The order of operations matter -- the environment variables need to be added, then the jupyter server needs to be launched.
Set environment variables in the notebook and make sure Mito updates correctly: 
```
os.environ['MITO_CONFIG_VERSION_KEY'] = "1"
os.environ['MITO_CONFIG_SUPPORT_EMAIL_KEY'] = "aaron@sagacollab.com"
```
Then delete the environment variables and make sure Mito goes back to our defaults. 
```
del …
```
> Mito config 2

- mitosheet/src/components/endo/ColumnHeaderDropdown.tsx
When the user has multiple columns selected, and they right click on the column header to access the fill nan taskpane, this pr opens the taskpane with all of the selected columns toggled `on` in the fill nan taskpane. 
Try above. 
No.
> mitosheet: use all selected columns in fillnan taskpane

- mitosheet/src/utils/strings.tsx
Fixes bug with search in unique values tab where if the value was `6000` as int, so that Mito formatted it to `6,000`, searching for `6000` did not return the correct result. 
Try testing above scenario
No.
> mitosheet: fix search string in unique values tab

- mitosheet/src/components/endo/ColumnHeader.tsx
- mitosheet/src/components/endo/ColumnHeaderDropdown.tsx
- mitosheet/src/components/endo/EndoGrid.tsx
- mitosheet/src/components/endo/FormulaBar.tsx
- mitosheet/src/components/endo/celleditor/CellEditor.tsx
- mitosheet/src/components/endo/celleditor/cellEditorUtils.tsx
- mitosheet/src/utils/actions.tsx
When using the in grid cell editor, you can now switch to the formula bar cell editor and the formula is preserved instead of being deleted. 
Try switching cell editors
None.
> mitosheet: fix formula in formula bar

- .clabot
- .github/workflows/cla.yml
- CLA.md
- CONTRIBUTING.md
Sets up the the CLA assistant following the instructions [here](https://github.com/marketplace/actions/cla-assistant-lite)
Will test once we merge into dev
> Add cla infrastructure

- mitosheet/css/endo/ColumnHeaders.css
- mitosheet/src/components/endo/ColumnHeader.tsx
- mitosheet/src/components/endo/ColumnHeaders.tsx
- mitosheet/src/components/endo/EndoGrid.tsx
- mitosheet/src/components/endo/widthUtils.tsx
- mitosheet/src/hooks/useCallOnAnyClick.tsx
Allows you to double click on the column resizer to set the column at the min(column header, longest data cell). Performs operations for all selected columns and the column you double click on. 
Resize columns using the double click and make sure it works. 
Yeah, we should probably note this somewhere. Maybe we could create a spreadsheet navigation page?
> Full Width Columns

- mitosheet/src/components/taskpanes/Download/ExcelDownloadConfigSection.tsx
Adds a toggle all to the excel export taskpane
> mitosheet: add toggle all to export taskpane

- mitosheet/src/components/endo/widthUtils.tsx
- mitosheet/src/components/taskpanes/PivotTable/PivotTableKeySelection.tsx
- Changes the order of the pivot table time buckets to be more intuitive.
- Updates the algorithm to guess full width of columns <- I tried for about an hour to create divs and get the correct width from them, but it wasn't working properly and is way more complicated than this, so thought I would keep this for now. 
> mitosheet: update datetime bucket ordering and alg

- mitosheet/mitosheet/api/get_path_contents.py
Hides temporary files that start with `~$`
> mitosheet: filter out temp windows files

- mitosheet/src/hooks/useKeyboardShortcuts.tsx
If you have other selected things, we won't copy shit out of the mitosheet. This is a reasonable thing to do, methinks!
Test copying.
N/A.
> mitosheet: fix bug in copy if you had other selection

- mitosheet/mitosheet/mito_frontend.js
- mitosheet/mitosheet/tests/step_performers/test_filter.py
There was a new numpy release, `numpy 1.24.0` that broke a few filter tests. This PR fixes them. Specifically, I believe that it broke because of this PR https://github.com/numpy/numpy/pull/22357 where some dtypes got checked at runtime. 
However, according to the release notes [here](https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations), "This release supports Python versions 3.8-3.11." so we have to take special care to handle earlier versions of numpy by setting the dtype to float. 
- On dev, install numpy 1.24.0 and see that's don't pass
- On dev, install numpy 1.23.5 and see that tests do pass
- On this branch, see that tests pass on both versions of numpy. 
No.
> mitosheet: fix pytests for new numpy release

- mitoinstaller/mitoinstaller/commands.py
- mitoinstaller/mitoinstaller/installer_steps/final_installer_steps.py
- mitoinstaller/tests/test_launch_jupyter.py
Creates an optional argument to the installer that prevents the installer from automatically launching Jupyter at the end of the process, as this is breaking some users's startup scripts. https://github.com/mito-ds/monorepo/issues/578
Run installer locally with `python3 -m mitoinstaller install --turn-off-jupyter-launch` and make sure Jupyter does not start
@naterush is there an easy way to actually test this functionality. My test leaves room to be desired. 
Yes. We could add documentation for this and --user options
> mitoinstaller: create option for turning off automatic jupyter launch

- mitosheet/mitosheet/mito_frontend.js
- mitosheet/src/components/elements/Input.tsx
- mitosheet/src/components/import/CSVImportConfigScreen.tsx
- When the inputs in the CSVConfigTaskpane are focussed on, selects all of the text to make it obvious that there is a space in the case that the delimiter Mito detects is a space. This prevents users from updating the delimiter to `[space],` instead of just `,`. 
> Dogfood 1-8-23

- mitosheet/package.json
It is nicer for new developers to have a simple and straightforward API to build. No need to go in docs, understand how to build so forth an so on. package.json provides such API. This PR adds two new scripts to easily rebuild the functions documentation.
Run:
```
npm run build:docs:update_frontend
npm run build:docs:generate_markdown
```
> mitosheet: add npm scripts to build documentation

- mitosheet/mitosheet/enterprise/mito_config.py
- mitosheet/mitosheet/mito_frontend.js
- mitosheet/mitosheet/tests/test_mito_config.py
- mitosheet/src/components/Mito.tsx
- mitosheet/src/types.tsx
Adds an environment variable for turning off tours. Helpful for enterprise customers who run trainings and find the tour distracting during those sessions. 
Note: I did not update the Mito Config Version since we handle the default case where the Display Tours key is not set and nothing else changed. There's no benefit.  
Set these environment variables and make sure that the intro and spreadsheet formula tours do not appear.
```
import os
os.environ['MITO_CONFIG_DISABLE_TOURS'] = 'True'
os.environ['MITO_CONFIG_VERSION'] = '2'
```
> mitosheet: add env for turning off tours

- mitosheet/mitosheet/mito_frontend.js
- mitosheet/src/components/elements/MultiToggleBox.tsx
- mitosheet/src/components/import/XLSXImportConfigScreen.tsx
When an Excel file is password protected, no sheets are displayed in the multi toggle box. This has causes confusion to our users. Now if there are no sheets returned, we just let them know that it might be because the file is password protected. 80/20
Supporting password protected files is not straight forward in pandas, so if we want to actually support these files, we'll need to look for new import methods. 
Create a password protected Excel file and watch for the message. 
> Add a hint that a file is password protected to stop confusion

- mitosheet/mitosheet/code_chunks/snowflake_import_code_chunk.py
- mitosheet/mitosheet/code_chunks/step_performers/dataframe_steps/dataframe_rename_code_chunk.py
- mitosheet/mitosheet/code_chunks/step_performers/import_steps/excel_range_import_code_chunk.py
- mitosheet/mitosheet/code_chunks/step_performers/pivot_code_chunk.py
- mitosheet/mitosheet/step_performers/import_steps/excel_range_import.py
- mitosheet/mitosheet/step_performers/import_steps/snowflake_import.py
- mitosheet/mitosheet/tests/step_performers/dataframe_steps/test_dataframe_rename.py
- mitosheet/mitosheet/tests/step_performers/import_steps/test_excel_range_import.py
- mitosheet/mitosheet/tests/step_performers/import_steps/test_snowflake_import.py
Optimizes dataframe renames in a bunch of the most common cases. Very nice! Closes https://github.com/mito-ds/monorepo/issues/617
Do things, then rename.
No.
> mitosheet: have dataframe renames optimize

- mitoinstaller/mitoinstaller/installer_steps/mitosheet_installer_steps.py
This is an optional step for most of our users, so let's not fail on it. See investigation of other issues here: https://www.notion.so/trymito/2-6-23-4d92e602e0674eac98ca8fcfd9d86c97
Add an raise Exception in the steps you want to fail, and make sure the installer still terminates.
No.
> mitoinstaller: don't fail on notebook installer

- mitosheet/mitosheet/api/get_ai_completion.py
Moves to the new chatgpt api. 
Use the AI transformation taskpane. 
> mitosheet: move to chatgpt api

- mitosheet/mitosheet/steps_manager.py
- mitosheet/mitosheet/tests/updates/test_clear.py
Don't clear Excel range imports on Clear. 
See test 
> mitosheet: don't remove excel range imports on clear

- mitosheet/mitosheet/public/README.md
- mitosheet/mitosheet/public/v1/__init__.py
- mitosheet/mitosheet/tests/step_performers/import_steps/test_excel_range_import.py
This makes sure that users continuing new analyses on old versions of the public interface can access all the correct functions.
See new test.
No.
> mitosheet: ensure backwards compatibility

- mitosheet/mitosheet/mito_frontend.js
- mitosheet/src/components/icons/CodeSnippetIcon.tsx
- mitosheet/src/components/toolbar/Toolbar.tsx
- mitosheet/src/components/toolbar/utils.tsx
- mitosheet/src/utils/actions.tsx
Add toolbar button for code snippets if there is a custom code snippets url set. 
1. Set a custom code snippets url, see the code snippets button.
2. Remove the code snippets url, don't see the code snippets button. 
No.
> mitosheet: add code snippets toolbar button

- mitosheet/mitosheet/mito_frontend.js
- mitosheet/src/components/taskpanes/ExcelRangeImport/ExcelRangeImportTaskpane.tsx
1. Create a mitosheet where upper left corner value is 8A.
2. Import it using range import. 
In previous versions, this would get cast to 8, which would not be found. This should work currently. 
See above.
N/A.
> mitosheet: fix bug with 8A as first value

- mitosheet/mitosheet/enterprise/mito_config.py
There was a bug where mitosheet-private and enterprise users who set any mito config environment variable fell into the TRUE default case for `get_display_ai_transform`.
- At the top of the the mito_config file, set the package_name variable = 'mitosheet-private'
- Set the `MITO_CONFIG_SUPPORT_EMAIL` environment variable. 
- Create a mitosheet and make sure that AI button is not displayed. 
No.
> mitosheet: don't show AI button on mitosheet-private with mec

- mitosheet/mitosheet/parser.py
- mitosheet/mitosheet/public/v3/rolling_range.py
- mitosheet/mitosheet/public/v3/sheet_functions/utils.py
- mitosheet/mitosheet/tests/step_performers/column_steps/test_set_column_formula.py
- mitosheet/mitosheet/tests/test_parse.py
If we had the dataframe `df = pd.DataFrame({'A': [1,2,3], 'B': [4,5,6]})`, and we wrote the formula `=CONCAT(C:A)`, it would error because the dataframe sent to the rolling range would be empty. This occurred because we selected columns between C and A in the dataframe (which is none)
See tests
> mitosheet: fix bug with column headers in wrong order

- mitosheet/src/components/endo/EndoGrid.tsx
- mitosheet/src/components/endo/celleditor/CellEditor.tsx
- mitosheet/src/components/endo/celleditor/cellEditorUtils.tsx
Implements the keyboard formula navigation improvements from https://www.notion.so/trymito/Cell-Editing-UI-1955396ade8244f58cca4d2c55755de7
- Start writing a formula and write `:`, then use arrow keys to scroll in the grid instead of in the formula
- Use `=` to enter cell editing mode and notice that it creates a new formula that starts with `=` instead of appending `=` to the end of the cell editor. Just like Excel
- Press `F2` (function + F2) to enter cell editing mode. Notice that it opens the formula to the current formula without any changes. Just like Excel. However, we also support the same interaction with `Enter`
Tested on Mac + windows
> Keyboard Formula Navigation

- mitosheet/mitosheet/mito_frontend.js
- mitosheet/src/components/elements/Dropdown.tsx
We had a bug where we were previously creating a _new_ div on every rerender
of every dropdown. This bug has been in Mito for a very long time. It's not
clear that the observered bugs we found were a function of this issue - but 
it is def not good news! This PR fixes it up.
First, try the dev branch of Mito. Import some data. Open the console
and run the code `document.body.querySelectorAll('div').length`. Then scroll
around in Mito, and then run `document.body.querySelectorAll('div').length` 
again. You will see the number of divs has increased!
Now, try the same steps on this branch. You will see that here, we do not
increase the number of divs over time.
> mitosheet: stop making infinite divs for dropdowns

- trymito.io/components/Footer/Footer.tsx
- trymito.io/components/Header/Header.module.css
- trymito.io/components/Header/Header.tsx
- trymito.io/styles/globals.css
Fixes spacing issues on website by:
1. reducing complexity of header by getting rid of the middle header. It is now left aligned 
2. hiding some of the less important header items when it gets too small
3. removes the teams page from the header, which needs a new pass and doesn't really capture how we want to talk about teams anymore. 
Also, adds "we're hiring" to the header. 
Test this with different screens + mobile
No.
> mitosheet: cleanup header

- mitosheet/setup.py
I dug into  urllib3, and based on the issues (https://github.com/urllib3/urllib3/issues?q=is%3Aissue+sort%3Acomments-desc) this issue is a result of computer specific things and not common. At least, it's not a Mito specific issue, and I think we'll likely we'll get ourselves into more trouble by pinning url lib to a specific version - given other dependencies that might exist. My vote is we just don't pin for now.
Not sure. 
No.
> mitosheet: remove urllib pinning

- mitosheet/src/components/Mito.tsx
- mitosheet/src/components/taskpanes/ControlPanel/ControlPanelTaskpane.tsx
- mitosheet/src/components/taskpanes/ControlPanel/FilterAndSortTab/FormatCard.tsx
- mitosheet/src/components/toolbar/Toolbar.tsx
- mitosheet/src/utils/actions.tsx
- mitosheet/src/utils/format.tsx
1. Make a pivot that results in number column, keep pivot taskpane open
2. Try and increase or decrease precision of decimals
3. The pivot should close, since it's not the last step id
Previously, this would brick the pivot taskpane.
See above.
No.
> mitosheet: fix up bug with formatting during pivot tables

- mitosheet/.gitignore
- mitosheet/mitosheet/api/get_path_contents.py
- mitosheet/mitosheet/mito_backend.py
- mitosheet/mitosheet/steps_manager.py
- mitosheet/mitosheet/streamlit/streamlit.py
- mitosheet/mitosheet/streamlit/v1/spreadsheet.py
- mitosheet/mitosheet/tests/streamlit/test_hash.py
- mitosheet/src/jupyter/code.tsx
- mitosheet/src/jupyter/jupyterUtils.tsx
- mitosheet/src/jupyter/notebook/extensionUtils.tsx
- mitosheet/src/mito/Mito.tsx
- mitosheet/src/mito/api/api.tsx
- mitosheet/src/mito/components/elements/ErrorBoundary.tsx
- mitosheet/src/mito/components/import/FileBrowser/FileBrowser.tsx
- mitosheet/src/mito/components/import/FileBrowser/FileBrowserBody.tsx
- mitosheet/src/mito/components/import/FileBrowser/FileBrowserPathSelector.tsx
- mitosheet/src/mito/types.tsx
- mitosheet/src/plugin.tsx
- mitosheet/src/streamlit/MitoStreamlitWrapper.tsx
1. Adds our own hashing function. See issue on streamlit here that this is a workaround for: https://github.com/streamlit/streamlit/issues/7086
2. We were double delivering messages in multiple cases - because setComponentValue persists between runs, even if the backend changes. This fixes that. 
1. Renames aren't detected by the caching function in streamlit. We need to write our own caching function.
2. Two mitosheets that feed into eachother. Add column in first, then delete column in second, then add new column in first. The second sheet has code that is out of date with the sheet.
3. 
> Streamlit refactors

- mitosheet/mitosheet/api/get_dataframe_as_excel.py
- mitosheet/mitosheet/code_chunks/export_to_file_code_chunk.py
- mitosheet/mitosheet/column_headers.py
- mitosheet/mitosheet/public/v3/formatting.py
- mitosheet/mitosheet/step_performers/export_to_file.py
- mitosheet/mitosheet/tests/step_performers/test_export_to_file.py
- mitosheet/mitosheet/tests/test_transpile.py
- mitosheet/mitosheet/transpiler/transpile_utils.py
- mitosheet/mitosheet/utils.py
This adds the ability to export (through code chunks) conditional formats for the "greater than" condition. The generated code looks like this:
```
add_formatting_to_excel_sheet(writer, "df", df, 
conditional_formats=[
{'columns': ['A'], 'filters': [{'condition': 'greater', 'value': 5}], 'font_color': '#e72323', 'background_color': '#ffffff'},
{'columns': [], 'filters': [{'condition': 'not_empty', 'value': ''}], 'font_color': None, 'background_color': None}
]
)
```
> Add greater than conditional format to excel export

- mitosheet/mitosheet/streamlit/v1/spreadsheet.py
- mitosheet/src/mito/utils/location.tsx
We used to make it so if you change the import path, or any of the sheet functions, you had to restart the app to get the new stuff. This is obviously not correct, and this fixes that. 
N/A.
No.
> streamlit: make sure we cache on the right variables

- mitosheet/mitosheet/streamlit/streamlit.py
- mitosheet/mitosheet/streamlit/v1/spreadsheet.py
Makes it so different users don't share the same Mitosheet. Notably:
1. The clear on page refresh is exactly how other streamlit components work (e.g. buttons work like this!) -- so it's actually more legit than what we were doing before!
2. We can't use cache_data because the Mito backend is a) not serializable, and b) massive. It's literally every step, so it would be so slow for large datasets to serialize it. 
3. The only thing it would make sense to serialize with st.cache_data is the messages sent from the backend, but this requires then reprocessing _from the start_ for every edit, which is also very slow. 
All in all, this solution is pretty sweet and smooth and I am very happy with it!
Please provide a list of the ways you can "access" or use the functionality. Please try and be …
> streamlit: fix caching issues

- mitosheet/mitosheet/step_performers/import_steps/simple_import.py
- mitosheet/mitosheet/streamlit/streamlit.py
This fixes up Mito so it supports remote file paths that are at Urls. Notably, this will now work in a `mitosheet.sheet` call as well -- which is pretty cool!
See testing streamlit.py app!
No.
> streamlit: allow remote file paths

- mitosheet/mitosheet/mito_backend.py
- mitosheet/mitosheet/saved_analyses/upgrade.py
- mitosheet/mitosheet/state.py
- mitosheet/mitosheet/steps_manager.py
- mitosheet/mitosheet/streamlit/v1/spreadsheet.py
- mitosheet/mitosheet/tests/saved_analyses/test_upgrade.py
- mitosheet/mitosheet/tests/step_performers/test_export_to_file.py
- mitosheet/mitosheet/tests/test_mito_backend.py
- mitosheet/mitosheet/tests/test_transpile.py
- mitosheet/mitosheet/tests/test_utils.py
- mitosheet/mitosheet/transpiler/transpile.py
- mitosheet/mitosheet/transpiler/transpile_utils.py
- mitosheet/mitosheet/types.py
- mitosheet/src/mito/components/taskpanes/CodeOptions/CodeOptionsTaskpane.tsx
- mitosheet/src/mito/types.tsx
Ian into this when creating the recon app. If you are Mito Enterprise, and you want the function to transpile as code - you can configure through the Code > Code Options taskpane. 
However, in Streamlit, you often want this script to _not_ call the code it generates. This is pretty reasonable, I think -- so I added a configuration option for it. 
In the future, we should make the code options configurable through the `spreadsheet` interface - you should be able to by default turn on the function generation.
Use this feature, make sure it's not calling the function it generates.
We should add to docs
> mitosheet: add more code config options that make recon app easier

- mitosheet/mitosheet/api/get_dataframe_as_excel.py
- mitosheet/mitosheet/code_chunks/export_to_file_code_chunk.py
- mitosheet/mitosheet/saved_analyses/step_upgraders/__init__.py
- mitosheet/mitosheet/saved_analyses/upgrade.py
- mitosheet/mitosheet/step_performers/export_to_file.py
- mitosheet/mitosheet/tests/saved_analyses/test_upgrade.py
- mitosheet/mitosheet/tests/step_performers/test_export_to_file.py
- mitosheet/mitosheet/tests/test_step_format.py
- mitosheet/mitosheet/tests/test_utils.py
- mitosheet/src/mito/api/api.tsx
- mitosheet/src/mito/components/taskpanes/Download/DownloadTaskpane.tsx
- mitosheet/src/mito/components/taskpanes/ExportToFile/ExportToFileTaskpane.tsx
Adds a toggle to the download taskpane when the file type is excel:
(Maybe should be changed) CTA for non-pro users:
Todo:
- I tried adding a tooltip but the component we have is a little question mark icon and it looked a little weird next to the pro icon so I left it out. I can add that in if you think it's a good idea though!
Questions:
- How do we handle when CSV is the file type? (Right now it just only appears as a field to the user when excel is the file type)
- Keep as is
- What should the CTA be for non-pro users? Right now I have a really plain text that says "Upgrade to Pro" - not saying that should be the design but I'm not sure what should be 
- Solution: disabling the toggle
> Add toggle to export formatting for excel

- mitosheet/mitosheet/code_chunks/export_to_file_code_chunk.py
- mitosheet/mitosheet/tests/step_performers/test_export_to_file.py
Fixes a bug when dataframe names are long where the generated code for calling `to_excel` uses a different name for the dataframe from the call to `add_formatting_to_excel` and throws an error when run. This switches to using the same value between those two calls
> Fix format code chunk bug for long dataframe names

- mitosheet/mitosheet/streamlit/v1/spreadsheet.py
Exposes code options for streamlit. After having to write a bunch of code to simulate our function generation in Streamlit dashboards a few times -- I want to just use what we already have written!
Use it!
No.
> mitosheet: make code options public for streamlit

- mitosheet/mitosheet/step_performers/export_to_file.py
- mitosheet/mitosheet/tests/step_performers/test_export_to_file.py
Currently when the user selects "Download File when Executing Code", the code downloads when the user generates the code. This is not the expected behavior for the user, so I just removed it.
> Prevent export when 'export as code' is selected

- mitosheet/src/mito/Mito.tsx
- mitosheet/src/mito/components/endo/ColumnHeaderDropdown.tsx
- mitosheet/src/mito/components/taskpanes/taskpanes.tsx
- mitosheet/src/mito/hooks/useLiveUpdatingParams.tsx
- mitosheet/src/mito/pro/taskpanes/ConditionalFormatting/ConditionalFormattingCard.tsx
- mitosheet/src/mito/pro/taskpanes/ConditionalFormatting/ConditionalFormattingTaskpane.tsx
Adds an option to the context menu for adding a conditional format to the selected columns: 
And when the user clicks on that option, it opens the conditional formats panel with a new conditional format that has the selected column(s) pre-selected:
**Note**: Also changes the behavior of the conditional formats panel to by default open the first conditional format when the conditional format taskpane is opened, unless you're opening the taskpane from the context menu.
> Add a 'Conditional Formats' option to the column dropdowns

- mitosheet/mitosheet/tests/step_performers/test_sort_step.py
Fix tests for python 3.11
In the release of Python 3.11, sorting perf improvements caused tuple ordering to be ill-defined. In Python 3.11 the two 5's in these dataframes were sorted in different orders than in Python 3.8. 
See tests
No.
> mitosheet: fix tests for python 3.11

- mitosheet/mitosheet/code_chunks/step_performers/merge_code_chunk.py
- mitosheet/mitosheet/step_performers/merge.py
- mitosheet/mitosheet/tests/step_performers/test_merge.py
This fixes a long-standing bug where dataframes would fail to merge. I finally replicated it -- it's when the new dataframe doesn't have the same index as the old dataframe.
We calculate these differently now -- but it works good!
See new tests. **Also, this makes the unique in left and unique in right tests work properly -- they were never running before. Doh!.**
No.
> mitosheet: fix bug in unique in left/right calcs due to index issues

- mitosheet/mitosheet/tests/test_transpile.py
- mitosheet/mitosheet/transpiler/transpile_utils.py
We were including param definitions even if we didn't use them. 
See test.
No.
> mitosheet: make transpile as function not include params

- mitosheet/src/mito/Mito.tsx
This fixes a small bug where when the focus moves out of the cell editor, using "escape" to close the cell editor stops working. 
1. Open the cell editor
2. Click anywhere outside of the editor
3. Press "escape" 
4. The cell editor should close
> Fix escape from cell editor bug

- mitosheet/mitosheet/parser.py
- mitosheet/mitosheet/tests/test_parse.py
- mitosheet/src/mito/Mito.tsx
- mitosheet/src/mito/components/endo/ColumnHeader.tsx
- mitosheet/src/mito/components/endo/ColumnHeaderDropdown.tsx
- mitosheet/src/mito/components/endo/EndoGrid.tsx
- mitosheet/src/mito/components/endo/FormulaBar.tsx
- mitosheet/src/mito/components/endo/celleditor/CellEditor.tsx
- mitosheet/src/mito/components/endo/celleditor/CellEditorDropdown.tsx
- mitosheet/src/mito/components/endo/celleditor/FloatingCellEditor.tsx
- mitosheet/src/mito/components/endo/celleditor/cellEditorUtils.tsx
- mitosheet/src/mito/components/endo/selectionUtils.tsx
- mitosheet/src/mito/components/endo/utils.tsx
- mitosheet/src/mito/types.tsx
- mitosheet/src/mito/utils/actions.tsx
Adds the ability to select columns in different sheets **when the user is editing a VLOOKUP formula**. 
This changes the `editorState` to include `sheetIndex`.
Also updates the behavior of selecting a range of columns to allow for the user to shift and click another header to select the range. 
Todo:
> Add support for cross-sheet formulas on the frontend

- mitosheet/css/elements/SearchBar.css
- mitosheet/mitosheet/api/api.py
- mitosheet/mitosheet/api/get_total_number_matches.py
- mitosheet/mitosheet/tests/api/test_get_total_number_matches.py
- mitosheet/src/mito/Mito.tsx
- mitosheet/src/mito/api/api.tsx
- mitosheet/src/mito/components/SearchBar.tsx
- mitosheet/src/mito/utils/actions.tsx
This adds a backend API to get the total number of matches to a string for a given sheet, and displays it in the search bar like this: 
**Note**: When we add in jumping to the next match, the text displayed will update from "*m* matches" to "n of m".
> Add api for total number of matches

- mitosheet/css/elements/SearchBar.css
- mitosheet/mitosheet/code_chunks/replace_code_chunk.py
Fixes a bug that generated a column header map for renaming that was including *all* column headers instead of just the headers that were changing. 
* Search for a value that exists in a column header
* Replace with a value
* Check that the code chunk only includes the values that are being replaced.
> Fix code chunk to only include columns that need to be replaced

- mitosheet/src/mito/components/endo/celleditor/CellEditor.tsx
Fixes a bug that occurs with the cursor of the cell editor when selecting a range of columns in a cross-sheet reference. The cursor was using the `editorState` sheet's name to generate the cursor location when it should be using the current sheet index's name.
> Fix cursor bug

- mitosheet/mitosheet/mito_backend.py
- mitosheet/mitosheet/tests/test_transpile.py
- mitosheet/mitosheet/transpiler/transpile_utils.py
- mitosheet/mitosheet/types.py
- mitosheet/src/mito/components/taskpanes/CodeOptions/CodeOptionsParameters.tsx
Adds a function to the backend to get the transpiled code as a function (that isn't called) with all of the current parameterization added. This includes: 
```
[
'import_dataframe',
'file_name_export_excel',
'file_name_export_csv',
'file_name_import_excel',
'file_name_import_csv',
]
```
Added tests in `test_transpile.py` to check that the output is what we expect.
> Add function to backend to get fully parameterized function

- mitosheet/mitosheet/api/get_parameterizable_params.py
- mitosheet/mitosheet/mito_backend.py
- mitosheet/mitosheet/tests/test_transpile.py
- mitosheet/mitosheet/transpiler/transpile_utils.py
- mitosheet/mitosheet/types.py
Adds a `ParamData` type. Adds a `mito_backend.param_metadata` property. 
Adds a test with the `fully_parameterized_function_string` tests to check that the expected params show up in the `param_metadata` as well.
> Add ParamData type

- mitosheet/mitosheet/streamlit/streamlit.py
- mitosheet/mitosheet/streamlit/v1/__init__.py
- mitosheet/mitosheet/streamlit/v1/spreadsheet.py
- mitosheet/mitosheet/tests/streamlit/test_streamlit.py
Adds a class that can be used by streamlit developers to store / access information about an analysis. 
Updated the `streamlit.py` file to show usage. 
We should add documentation once we add some more functionality into this class.
> Add MitoAnalysis class

- trymito.io/components/Footer/Footer.module.css
- trymito.io/components/Footer/Footer.tsx
Having multiple `H1`s on a page delutes their SEO effect, so we don't want to waste an H1 on each page with that is just "Mito".
> trymito: remove h1 from footer

- mitosheet/mitosheet/public/v3/sheet_functions/misc_functions.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/misc_functions/test_vlookup.py
Excel's VLOOKUP is case insensitive, even if exact match is turned on. Matching this behavior is important! 
This PR makes our VLOOKUP formula case insensitive as well. 
See tests
No.
> mitohseet: make vlookup case insensitive

- mitosheet/mitosheet/streamlit/v1/spreadsheet.py
- mitosheet/mitosheet/tests/streamlit/test_mito_analysis.py
Adds a `to_json` and `from_json` method to the `MitoAnalysis` class for easier storage of the class in files. 
Added basic test in `test_mito_analysis.py`. 
This should be added with the documentation for streamlit.
> Add to_json and from_json to MitoAnalysis

- mitosheet/mitosheet/api/get_parameterizable_params.py
- mitosheet/mitosheet/code_chunks/export_to_file_code_chunk.py
- mitosheet/mitosheet/code_chunks/step_performers/import_steps/excel_import_code_chunk.py
- mitosheet/mitosheet/code_chunks/step_performers/import_steps/excel_range_import_code_chunk.py
- mitosheet/mitosheet/code_chunks/step_performers/import_steps/simple_import_code_chunk.py
- mitosheet/mitosheet/steps_manager.py
- mitosheet/mitosheet/streamlit/streamlit.py
- mitosheet/mitosheet/streamlit/v1/spreadsheet.py
- mitosheet/mitosheet/tests/streamlit/test_mito_analysis.py
- mitosheet/mitosheet/tests/test_transpile.py
- mitosheet/mitosheet/types.py
This makes the API clearer for streamlit developers to access the `param_metadata` by type. It also changes the `ParamType` to facilitate these changes to the API.
Added a test into the existing `MitoAnalysis` tests that checks that:
* When no type is passed, the entire array of param metadata is returned
* When 'import' type is passed, the imports are returned. 
* When 'export' type is passed, the exports are returned. 
* When 'export' type is passed but there are no export param metadata, an empty array is passed. 
This should be added when we add the `MitoAnalysis` / streamlit docs.
> Add get_param_metadata to MitoAnalysis class

- mitosheet/mitosheet/mito_backend.py
- mitosheet/mitosheet/tests/streamlit/test_mito_analysis.py
- mitosheet/mitosheet/tests/test_transpile.py
Allows for custom python imports in the `fully_parameterized_function` of the `mito_backend` so that the `MitoAnalysis` class can use custom sheet functions. 
See mito-ds/streamlit-recon-wizard#3.
> Update flag to include custom python imports in MitoAnalysis

- mitosheet/dash_app.py
- mitosheet/mitosheet/mito_dash/v1/spreadsheet.py
- mitosheet/mitosheet/streamlit/v1/spreadsheet.py
Adds `MitoAnalysis` into the `SpreadsheetResult` class:
* adds `analysis()` to access the `MitoAnalysis`
* adds 3 new arguments to the `SpreadsheetResult.init()` function to support initializing the `MitoAnalysis`. 
See `dash_app.py`. 
We'll want to add this into the dash docs!
> Add support for MitoAnalysis class in Dash

- mitosheet/mitosheet/streamlit/v1/spreadsheet.py
- mitosheet/mitosheet/tests/streamlit/test_runnable_analysis.py
Makes it so you can pass a dataframe to the `run` function for file path argument, and the `.run` function automatically converts it to a string that can be read by the pd.read_csv call in the function. 
In general, I think should continue to improve the flexibility of this interface. Users should be able to create an analysis from one datasource, and then rerun it easily off of another datasource.
See new test.
I think we can make this clear in the docs, just with a little section called **Input Flexibility**
> mitosheet: make runnable analysis take more flexible types

- trymito.io/components/CodeBlock/CodeBlock.tsx
- trymito.io/components/Footer/Footer.tsx
- trymito.io/components/Header/Header.tsx
- trymito.io/components/TextButton/TextButton.tsx
- trymito.io/excel-to-python-page-contents/ABS.json
- trymito.io/excel-to-python-page-contents/CONCAT.json
- trymito.io/excel-to-python-page-contents/COUNT.json
- trymito.io/excel-to-python-page-contents/HOUR.json
- trymito.io/excel-to-python-page-contents/IF.json
- trymito.io/excel-to-python-page-contents/ISNA.json
- trymito.io/excel-to-python-page-contents/LOWER.json
- trymito.io/excel-to-python-page-contents/RANK.json
- trymito.io/excel-to-python-page-contents/REPLACE.json
- trymito.io/excel-to-python-page-contents/SUM.json
- trymito.io/excel-to-python-page-contents/types.tsx
- trymito.io/pages/excel-to-python.tsx
- trymito.io/pages/excel-to-python/[...slug].tsx
- trymito.io/styles/ExcelToPython.module.css
- trymito.io/utils/excel-to-python.tsx
- Adds the home page for the Excel to Python glossary 
- Makes the related functions buttons works
- Adds this glossary to the `About` toolbar because it's pretty cool and useful
With this, I think we are finished all of the required infrastructure for these pages + we've implemented all of the most import page optimizations, so we are good to write more useful pages for functions that people are commonly looking to create! 
> Glossary functions page

- mitosheet/src/mito/components/toolbar/HomeTabContents.tsx
- mitosheet/src/mito/components/toolbar/Toolbar.tsx
- mitosheet/src/mito/components/toolbar/ToolbarButton.tsx
- mitosheet/src/mito/components/toolbar/utils.tsx
- mitosheet/src/mito/types.tsx
- mitosheet/src/mito/utils/actions.tsx
This adds an optional field into the `BaseAction` type to prepare for adding icons for many of the actions that are currently in the main menu at the top. Defaults to the `StepsIcon` because it looks pretty generic. 
Also, adds the default behavior for `disabledTooltip` into the `ToolbarButton` class to avoid a bunch of extra lines of code for passing it as a prop. 
Check that the toolbar has all of the icons you expect.
> Move icons into the action type

- mitosheet/mitosheet/public/v1/sheet_functions/types/utils.py
- mitosheet/mitosheet/tests/step_performers/column_steps/test_change_column_dtype.py
Closes https://github.com/mito-ds/mito/issues/1006, by making it so you can convert mixed types to date times.
Note that this doesn't fix the frontend display issue, for two reasons:
1. It's hard to do so in a performant way
2. Leaving it makes it more clear to these that they have to convert to a date time
See new tests.
N/A.
> Datetime fix

- mitosheet/mitosheet/tests/test_transpile.py
- mitosheet/mitosheet/transpiler/transpile_utils.py
Adds user defined editors to the import statement we create in generated code so that we can use them in automations! 
See tests
No.
> mitosheet: add custom edit imports

- mitosheet/src/mito/Mito.tsx
- mitosheet/src/mito/components/endo/ColumnHeader.tsx
- mitosheet/src/mito/components/endo/ColumnHeaderDropdown.tsx
- mitosheet/src/mito/components/endo/ColumnHeaders.tsx
- mitosheet/src/mito/components/endo/EndoGrid.tsx
- mitosheet/src/mito/components/toolbar/FormulaTabContents.tsx
- mitosheet/src/mito/components/toolbar/HomeTabContents.tsx
- mitosheet/src/mito/types.tsx
- mitosheet/src/mito/utils/actions.tsx
* Adds a new action for inserting a column to the left of the selection
* Updates the toolbar behavior to insert columns to the left
* Adds "Insert column left" and "Insert column right" as the first two buttons in the column header dropdown
> Add Insert column to left and right to the column header dropdown

- mitosheet/app.py
- mitosheet/css/toolbar.css
- mitosheet/src/mito/components/toolbar/Toolbar.tsx
- mitosheet/src/mito/components/toolbar/ToolbarButton.tsx
Adds a tab for the custom editors. If there are none, the tab doesn't appear.
> Add custom editors tab to the toolbar

- mitosheet/src/mito/components/icons/AddColumnIcon.tsx
- mitosheet/src/mito/components/toolbar/FormulaTabContents.tsx
- mitosheet/src/mito/components/toolbar/HomeTabContents.tsx
Changes the arrow in the insert icon to point right because it inserts the column to the right of the selected column.
> Change insert icon's arrow to point right

- mitosheet/src/mito/hooks/useEffectOnRedo.tsx
- mitosheet/src/mito/hooks/useEffectOnUndo.tsx
…ncorrectly
Closes: #1048 
Previously, things would break in Streamlit you:
1. Imported an XLSX file
2. Undid the import
3. Tried to import another XLSX file (without closing the import taskpane)
4. The sheets in the file never show up
The bug fixed here would cause a getParam api call to be sent at the same time as the excel file metadata -- which would cause the excel file metadata to be dropped. 
Test the series of steps above.
No.
> mitosheet: fix bug where use effect on undo and redo were triggered incorrectly

- mitosheet/css/toolbar.css
- mitosheet/dash_app.py
- mitosheet/mitosheet/mito_dash/v1/spreadsheet.py
- mitosheet/src/mito/components/toolbar/FormulaTabContents.tsx
- mitosheet/src/mito/utils/actions.tsx
* Updates the toolbar tooltips for:
* import / export dropdowns
* "More Functions" dropdown
* Updates the dash app to use the new spreadsheet API
* Removes underlining in the "Help" button at the top of the toolbar in notebook. 
* Fixes a focus issue where the cell editor didn't grab the focus when the user clicks on a formula dropdown item and the cell editor is already open. This was happening because the cell editor automatically grabs focus when it _opens_ but not when you change the formula. 
* Fixes #1024
> Dogfooding PR - toolbar tooltips and dash app update

- mitosheet/mitosheet/mito_dash/v1/spreadsheet.py
(...) makes a generator -- while [...] makes a list, which is the type we want, so we can e.g. detect length. This broke some existing Dash apps. 
I'm not sure why MyPy didn't catch this -- it totally should have!
Testing our dash apps manually.
No.
> dash: from generator to list

- .github/workflows/test-mitosheet-frontend.yml
- tests/README.md
- tests/data/test.csv
- tests/jupyterlab_ui_tests/jupyterlab.mitosheet.spec.ts
- tests/jupyterlab_ui_tests/mitosheet.spec.ts
- tests/playwright.config.js
- tests/requirements.txt
- tests/streamlit-test.py
- tests/streamlit_ui_tests/streamlit.spec.ts
Adds tests for home-bar items. This is supposed to be testing that all basic functionality works -- and doing so in a way that is robust and easy to maintain.
See tests. We want them to pass the following criteria:
1. All tests can run in parallel with no issues (two in parallel) currently.
2. Across 10 test runs (which we add with the following), we pass with *no flakeyness*
```
strategy:
matrix:
run_count: [1, 2, ..., 10]
```
3. The tests themselves should run in <1 minute. This includes only the *testing* time -- this is true currently.
No.
> tests: add streamlit tests for most home bar items

- mitosheet/src/mito/Mito.tsx
- mitosheet/src/mito/components/endo/EndoGrid.tsx
- mitosheet/src/mito/utils/actions.tsx
Fixes #1060.
* Updates the behavior when the user does a ctrl+click to select the cell /header / row that was clicked on, and opens the context menu.
* Adds handling for closing dropdowns when the user presses "escape"
> Update behavior of ctrl+click to open context menu

- mitosheet/mitosheet/public/v3/sheet_functions/misc_functions.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/misc_functions/test_vlookup.py
Fix bug caused by vlookup-ing when lookup values series has different indexes from `where` dataframe. 
```
import pandas as pd
df1 = pd.DataFrame({
'A': [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
'B': [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
})
df2 = pd.DataFrame({
'A': [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
'C': [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
})
mitosheet.sheet(df1, df2)
```
- Filter B to just include 0
- Use the formula in df1 VLOOKUP(A1,df2!A:C, 2)
Also, see regression tests. 
No
> mitosheet: fix filter then vlookup

- mitosheet/src/mito/components/toolbar/FormulaTabContents.tsx
Uses the formula description as the tooltip in the toolbar 
1. Test with a regular function
2. Test with a custom function that has documentation
3. Test with a custom function that does not have documentation
This is too detailed of a test for frontend tests right now. 
No.
> mitosheet: use formula description as tooltip

- mitosheet/css/toolbar.css
- mitosheet/mitosheet/step_performers/utils/user_defined_function_utils.py
- mitosheet/src/mito/Mito.tsx
- mitosheet/src/mito/components/endo/ColumnHeader.tsx
- mitosheet/src/mito/components/endo/GridData.tsx
- mitosheet/src/mito/components/endo/IndexHeaders.tsx
- mitosheet/src/mito/components/endo/visibilityUtils.tsx
- mitosheet/src/mito/components/taskpanes/UpdateImports/UserDefinedImportScreen.tsx
- mitosheet/src/mito/components/taskpanes/UserDefinedImport/UserDefinedFunctionDocumentationSection.tsx
- mitosheet/src/mito/components/taskpanes/UserDefinedImport/UserDefinedImportConfig.tsx
- mitosheet/src/mito/components/toolbar/DataTabContents.tsx
- mitosheet/src/mito/components/toolbar/HomeTabContents.tsx
- mitosheet/src/mito/components/toolbar/ToolbarButton.tsx
- mitosheet/src/mito/types.tsx
- mitosheet/src/mito/utils/actions.tsx
- mitosheet/src/mito/utils/strings.tsx
1. Fixes https://github.com/mito-ds/mito/issues/1078
2. Adds domain for user defined function (not the full version for now, but this is fine)
3. Includes documentation for user defined functions
Tried hard and failed to cut the subtext at two lines, feel free to give it a shot.
Use this streamlit app:
```
from mitosheet.streamlit.v1 import spreadsheet
import pandas as pd
import streamlit as st
st.set_page_config(layout="wide")
def no_docstring(x: int, y: int, z: int, f: int, long_variable_name: str):
return pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
def importer_test_domain():
"""
This is the first importer in the domain Retail. It has a long description, and we're going to see what 
happens when you go on for a while. 
This has multiple lines, and some of them should probably be …
```
> mitosheet: add domain to user defined types, add importer name to data tab

- mitosheet/src/mito/components/endo/FormulaBar.tsx
Fixes #1080. Checks whether the cell editor is open when opening the formula bar's cell editor so that the cell editor state isn't lost.
> Fix cross-sheet reference bug

- mitosheet/src/mito/components/endo/EndoGrid.tsx
- mitosheet/src/mito/components/endo/utils.tsx
- mitosheet/src/mito/components/toolbar/ToolbarButton.tsx
- mitosheet/src/mito/types.tsx
- mitosheet/src/mito/utils/actions.tsx
- mitosheet/src/mito/utils/keyboardShortcuts.tsx
- mitosheet/src/plugin.tsx
- tests/streamlit_ui_tests/streamlit.spec.ts
Adds keyboard shortcut in parentheses after the tooltip text for toolbar buttons and context menu items
> Add keyboard shortcut hint to toolbar button tooltip

- mitosheet/mitosheet/code_chunks/step_performers/dataframe_steps/dataframe_rename_code_chunk.py
- mitosheet/mitosheet/code_chunks/step_performers/merge_code_chunk.py
- mitosheet/mitosheet/saved_analyses/step_upgraders/merge.py
- mitosheet/mitosheet/saved_analyses/upgrade.py
- mitosheet/mitosheet/step_performers/merge.py
- mitosheet/mitosheet/step_performers/pivot.py
- mitosheet/mitosheet/tests/saved_analyses/test_upgrade.py
- mitosheet/mitosheet/tests/step_performers/test_merge.py
- mitosheet/mitosheet/tests/test_step_format.py
- mitosheet/mitosheet/tests/test_utils.py
Adds an optional param `destination_sheet_index` to the merge step performer / merge code chunk to enable editing existing merges. 
Adds a test for the basic usage of the edit.
> Add destination sheet index to merge

- trymito.io/pages/sitemap.xml.tsx
Add `www` to sitemap for functions pages so that the final urls are used. This makes it easier for Google to index the pages. 
Check the URLs
No
> trymito: add www to sitemap

- mitosheet/css/taskpanes/DefaultTaskpane.css
- mitosheet/src/mito/Mito.tsx
- tests/streamlit_ui_tests/streamlit.spec.ts
Adds a div between the `EndoGrid` and the `Taskpane` that allows the user to resize the taskpane on drag.
> Add ability to resize taskpane

- mitosheet/css/elements/MultiToggleBox.css
- mitosheet/src/mito/components/elements/ExpandableWarning.tsx
- mitosheet/src/mito/components/elements/MultiToggleColumns.tsx
- mitosheet/src/mito/components/taskpanes/Merge/MergeKeysSelection.tsx
- mitosheet/src/mito/components/taskpanes/Merge/MergeTaskpane.tsx
- mitosheet/src/mito/components/toolbar/ToolbarButton.tsx
- We were previously showing "(undefined)" after tooltips for toolbar buttons, if there were no keyboard shortcuts
- Fixes bug where dismissing errors in merge didn't rerender merge taskpane properly (see video below)
https://github.com/mito-ds/mito/assets/21002431/6d972c52-4bd7-4a50-8578-00a5428e5a22
Check toolbar buttons. Check merge errors (all of them)
No.
> Jan 5 dogfood

- mitosheet/mitosheet/code_chunks/step_performers/dataframe_steps/dataframe_rename_code_chunk.py
- mitosheet/mitosheet/code_chunks/step_performers/merge_code_chunk.py
- mitosheet/mitosheet/step_performers/merge.py
- mitosheet/mitosheet/step_performers/pivot.py
- mitosheet/mitosheet/telemetry/anonymization_utils.py
- mitosheet/mitosheet/telemetry/private_params_map.py
- mitosheet/mitosheet/telemetry/telemetry_utils.py
- mitosheet/mitosheet/tests/step_performers/test_merge.py
- tests/streamlit_ui_tests/features/merge.spec.ts
Replays edits on merge. 
Note that this PR is dramatically improved once we merge the PR https://github.com/mito-ds/mito/pull/1115 -- as the column insertion code at the end of the dataframe gets much more robust in this case. This is particularly useful in the case of merge, where editing is very likely to change the number of columns in the dataframe.
See new tests. Maybe write a few. 
No.
> Mitosheet: replay edits on merge

- mitosheet/src/mito/Mito.tsx
- mitosheet/src/mito/components/endo/selectionUtils.tsx
- mitosheet/src/mito/components/taskpanes/Graph/GraphSidebar.tsx
- mitosheet/src/mito/components/taskpanes/Graph/GraphStyleTab.tsx
- mitosheet/src/mito/components/taskpanes/Graph/graphUtils.tsx
- mitosheet/src/mito/utils/actions.tsx
- tests/streamlit_ui_tests/streamlit.spec.ts
Uses the selected columns to populate the axes in the graph configuration. Only covers the cases for bar charts, scatter plots, and line graphs because they are the only charts that can be created new. 
- Bar charts, line graphs : 
- If the leftmost column is anything but a number, it is the x axis
- If the y axes aren’t all the same type,
- else only populate the y axis
- scatter plot:
- one column: only populate y axis
- multiple columns: first column is the x axis, rest of columns are the y axis
> Create graph from selection in dataframe

- mitosheet/src/mito/components/elements/Dropdown.tsx
- mitosheet/src/mito/components/elements/DropdownItem.tsx
- mitosheet/src/mito/components/endo/IndexHeaderContextMenu.tsx
- mitosheet/src/mito/components/icons/CheckmarkIcon.tsx
- mitosheet/src/mito/components/icons/RightArrowIcon.tsx
* Adds props to `DropdownItem`: `subMenu?: JSX.Element` and `onMouseEnter`. The creator of the dropdown is expected to keep track of the state for displaying submenus, because we want to make it easy to switch between submenus without bugginess. 
* Adds `position?: 'vertical' | 'horizontal'` prop to `Dropdown` so that the position can be determined correctly for submenus. We want the submenu to always appear directly to the right of the dropdown item, so the handling for `position === 'horizontal'` is just to set the bounding box to be directly to the right of the dropdown item, regardless of the position. 
* Adds a dummy example to `IndexHeaderContextMenu.tsx` for testing purposes. 
* **Note: also adds support for checkmarks in dropdowns.**
* Adds `hasCheckmark` and `canHaveCheckmark` …
> Add ability to make multi-level dropdowns

- tests/streamlit_ui_tests/features/merge.spec.ts
Fix flakey merge test by making sure the merged dataframe is created before trying to add a column to it. 
See test
No.
> tests: fix flakey merge test

- mitosheet/mitosheet/api/get_search_matches.py
- mitosheet/mitosheet/tests/api/test_get_search_matches.py
Escapes special characters before compiling regex to search for values. 
Adds 1 test. 
No.
> Fix $ in search bug

- mitosheet/src/mito/components/taskpanes/Graph/GraphSidebar.tsx
- mitosheet/src/mito/components/taskpanes/Graph/graphUtils.tsx
- mitosheet/src/mito/components/toolbar/GraphTabs/AddChartElementButton.tsx
Fixes #1181. 
* Adds `ReactDOM.createPortal` to the popup so that it can be on top of the toolbar. 
* Adds calculation to keep the position of the popup from going to far up if the title is very long.
> Fix graph title editor popup bug

- mitosheet/css/elements/DropdownItem.css
Fixes text alignment in dropdowns. Multi line dropdown item subtext was appeared centered like this. Now they are left aligned!
Try it out. 
No.
> mitosheet: left align dropdown item subtext

- mitosheet/src/mito/Mito.tsx
- mitosheet/src/mito/components/taskpanes/Graph/GraphSidebar.tsx
- mitosheet/src/mito/components/taskpanes/Graph/graphUtils.tsx
- mitosheet/src/mito/components/toolbar/GraphTabs/AddChartElementButton.tsx
- tests/streamlit_ui_tests/graph.spec.ts
Adds context menus to the graph, x, and y axis titles:
> Add context menus for graph titles

- mitosheet/src/jupyter/code.tsx
- mitosheet/src/jupyter/jupyterUtils.tsx
- mitosheet/src/jupyter/notebook/extensionUtils.tsx
- mitosheet/src/mito/Mito.tsx
- mitosheet/src/plugin.tsx
Updates the execute function of `writeGeneratedCodeToCell` to take `oldCode` as an input and prevent overwriting changes if the code in the cell is different from the Mito generated code. This required adding a `ref` to keep track of the last mito-generated code in the analysis json and updating it after the call to `writeGeneratedCodeToCell`.
> Prevent overwriting code when the user has made changes to the generated code cell

- mitosheet/mitosheet/ai/recon.py
- mitosheet/mitosheet/tests/step_performers/test_ai_transformation.py
If pandas was accessed in a lambda function, global scope was not captured correctly in our usage of exec. This resulted in code that was correct like:
```
import pandas as pd
df1 = pd.DataFrame({'Date': pd.to_datetime(['1997-07-16T19:20'])})
df1[['Date', 'Time']] = df1['Date'].apply(lambda x: pd.Series([x.date(), x.time()]))
```
Erroring because pandas was not defined (thought it clearly was).
See new test to catch this in the future.
No.
> mitosheet: fix pd. usage in lambda functions in ai generated code

- trymito.io/pages/index.tsx
- trymito.io/utils/plausible.tsx
- Adds plausible class for the pip install mitosheet command on the homepage
Try it out. 
No.
> trymito: add plausible link for pip install mitosheet

- tests/streamlit_ui_tests/features/column_control_panel.spec.ts
- tests/streamlit_ui_tests/utils.ts
- Changing column dtype
- Adding a filter
- Sorting
- Changing the number type
- Filtering values through the values tab
- Loading summary stats
Adds utilities for:
- opening the column control panel
- changing the dtype
- changing the number type
- checking that column cells have expected values
- checking the control panel's value tab has expected values
> Add column control panel tests

- tests/streamlit_ui_tests/features/column_control_panel.spec.ts
- tests/streamlit_ui_tests/taskpanes/graph.spec.ts
- tests/streamlit_ui_tests/utils.ts
Adds `fillInput` and `updateSelectedValue` functions, which takes the `title` of an input (which is assumed to be in a `.spacing-row` div with the input), and fills with the given `value`. This allows for more precision and cleaner code when looking for inputs to fill. This allows us to avoid relying on things like the "nth" input.
> Add utils for filling input and selects

- mitosheet/mitosheet/parser.py
- mitosheet/mitosheet/tests/test_parse.py
Fixes #1243. The issue was that the parser was only using the first index that matched a given sheet name to identify cross-sheet formulas, so the resulting code wasn't identifying any sheets after the first.
> Fix multiple vlookup bug

- mitosheet/src/mito/components/elements/TextButton.tsx
- mitosheet/src/mito/components/import/FileBrowser/FileBrowser.tsx
- mitosheet/src/mito/components/layout/Row.tsx
- mitosheet/src/mito/components/taskpanes/DefaultTaskpane/DefaultTaskpaneFooter.tsx
* Updates some of the css in the import taskpane so that the buttons don't overlap. 
* Updates the `DefaultTaskpaneFooter` css so that the tabs at the bottom of the filter taskpane don't have awkward looking white space
* Fixes #1216.
> Fix import taskpane button alignment

- mitosheet/src/mito/utils/actions.tsx
- tests/streamlit_ui_tests/grid/keyboard_shortcuts.spec.ts
Adds extra logic into the action handler for open previous/next sheet when user presses opt+arrow to check for graph tabs.
> Update keyboard shortcut for navigating between tabs to include graph tabs

- mitosheet/mitosheet/parser.py
- mitosheet/mitosheet/tests/step_performers/column_steps/test_set_column_formula.py
- mitosheet/mitosheet/tests/test_parse.py
Fixes #1230. Removes addition of `.loc` call in the parsing of cell formulas with specific index labels. Not sure why that was added but it appears to not be necessary.
> Fix bug in parsing specific index labels

- mitosheet/css/FormulaBar.css
When the formula bar was empty, it became not clickable because the height became 0. This sets the height manually (and then adds correct adjustment to make sure that the formula is justified correctly). This css is copied from the `.formula-bar-column-header` style. 
Fixes #614. Fixes #1254.
> Fix bug switching between cell editor and formula bar

- mitosheet/mitosheet/steps_manager.py
- trymito.io/pages/plans.tsx
Makes column definitions require a liscence 
Test it with the sample app
No.
> Column def pro

- mitosheet/css/taskpanes/SplitTextToColumns/SplitTextToColumns.css
> Fix scroll bar bug in windows

- mitosheet/src/mito/Mito.tsx
- tests/streamlit_ui_tests/graph.spec.ts
Fixes #1092. The issue describes a different bug (which I assume was fixed somewhere?) but in trying to reproduce it I caught a different bug. The bug I saw was that pressing undo would get rid of the graph, but not close the graph editor. There would be no graph, but because the graph editor is designed to create a new graph when it sees the graph editor is open, it would just create a new graph. I chose to solve this by adding a `useEffect` that would check in the `Mito` component when the `graphDataArray` changed, and if the graphDataArray was empty but the graph taskpane was open, it just closes that taskpane.
> Fix bug when opening graph editor then pressing undo

- trymito.io/pages/excel-to-python/[...slug].tsx
Adds a popup to the excel to python glossary pages that offers a free Pandas Cheat Sheet if the user adds shares their email and company. 
For testing, it is configured to appear 5 seconds after page load on each page load. If we're happy with it, I'll change the settings so each user only gets it once per session
No.
> Python cheat sheet form

- trymito.io/components/Header/Header.module.css
- trymito.io/components/Header/Header.tsx
- trymito.io/pages/index.tsx
Adds a promo banner to the top of the header that links to the pyoneer waitlist typeform. 
Check the preview
> trymito: add pyoneer promotion to website

- mitosheet/mitosheet/enterprise/telemetry/mito_log_uploader.py
- mitosheet/mitosheet/tests/test_mito_log_uploader.py
Error severity codes are used to help enterprise admins triage errors. When managing the Mito environment of 1000's of users, error severity codes are useful for building dashboards to identify changes in the user experience and prioritize improvements. 
See new tests. 
Update docs before merging.
> mitosheet: add error log severity codes

- mitosheet/mitosheet/code_chunks/step_performers/column_steps/change_column_dtype_code_chunk.py
- mitosheet/mitosheet/public/v1/sheet_functions/types/utils.py
- mitosheet/mitosheet/tests/step_performers/column_steps/test_change_column_dtype.py
Fixes bug where pandas object columns that are full of datetime values does not convert to datetime. This commonly occurs in the following case:
1. Import a dataset that has several rows of comments at the top of the file followed by a table of data. One of the columns contains datetime values
2. Delete the comments and promote the first row of the table to the header of the dataframe. Although each individual cell data type is now a datetime, the entire column is still recognized as an object column, so dates are not formatted correctly. 
3. Convert the date column to a datetime dtype. 
4. Previously this would error because Mito was looking for string values in the column to convert to datetime and not finding any. 
See the new pytest
Not needed.
> mitosheet: fix convert to datetime with mixed dtype column

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
Fixes bug where the following would occur: 
1. Send message
2. Clear Chat
3. Click explain code
4. See first chat message reappear. 
This would happen because the COMMAND_MITO_AI_SEND_MESSAGE is registered in a useEffect on initial render, which will always use the initial state values. Now, we access the chat history manager via a function to ensure we always get the most recent chat history, even when the command is executed later.
Add a test for this: 
1. Send message
2. Clear Chat
3. Click explain code
4. See first chat message reappear. **It should not have the original message**
Not yet
> mito-ai: fix bug with registering command in UseEffect

- .github/workflows/test-mitosheet-frontend.yml
- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/ChatMessage.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/Extensions/AiChat/CodeDiffDisplay.tsx
- mito-ai/src/Extensions/CellToolbarButtons/CellToolbarButtonsPlugin.tsx
- mito-ai/src/Extensions/ErrorMimeRenderer/ErrorMimeRendererPlugin.tsx
- mito-ai/src/commands.tsx
Creates a separate code path for each type of AI completion. Each time we send a message to the AI there are three steps. 
1. Create a message. Some types of messages (like generating code) are more context hungry than others (explain active code cell). This step is responsible for building the write prompt with the right context for the specific message type.
2. Send the message to the AI and handle errors properly. This is the same for all types of AI messages. 
3. Post process. Currently, the only post processing step we have is showing code diffs. We want to do this in all cases except explaining code which should not return new code. 
Try it out + see tests. 
No.
> mito-ai: create separate prompt for each type of interaction

- .gitignore
- mito-ai/Untitled.ipynb
- mito-ai/src/Extensions/AiChat/ChatMessage/CodeBlock.tsx
The Mito AI taskpane now only shows the Accept/Deny buttons on the last message. Previous message will only display the option to copy code. 
N/A
> Added check for isLastAiMessage

- .github/workflows/test-mito-ai.yml
- .github/workflows/test-mitosheet-frontend.yml
test-mitosheet-frontend will only be triggered if changes are made to `mitosheet/` or `tests/`; while test-mito-ai will cover changes made to the `mito-ai/` dir. 
N/A
> Moved mito-ai tests into separate workflow

- mito-ai/style/PythonCode.css
Updated margin and padding for `.code-message-part-python-code pre` to include the `!important` keyword. This fixes the issue where code snippets in the AI taskpane are offset. 
CSS changes, visually tested on local machine (using Chrome).
N/A
> Updated margin and padding

- mito-ai/style/PythonCode.css
1. Updates the text wrapping in the AI chat taskpane so that one line of code does not wrap to a second line in the code preview. Instead, you can scroll to see the full line of code. I think this makes the code more readable. 
2. Uses the jupyter default code family so if the user changes their settings, its reflected in our code preview
3. Set the font size to 12px so it takes up less space. 
Try it out. 
No.
> update font size and line wrap of chat code

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
Fixes bug where dynamic calculation of chat input height was sometimes resulting in too small of an input. 
This bug would only some of the times, and only when first opening the chat input without any messages already sent.  Try opening the chat input a few times and making sure you never see this bug. 
No.
> mito-ai: fix small chat input bug

- mito-ai/README.md
- mito-ai/mito-ai/utils/create.py
- mito-ai/mito-ai/utils/db.py
- mito-ai/mito-ai/utils/open_ai_utils.py
- mito-ai/mito-ai/utils/schema.py
- mito-ai/mito-ai/utils/utils.py
- mito-ai/mito-ai/utils/version_utils.py
- mito-ai/src/utils/handler.ts
Reuses the mito accounts infrastructure to rate limit open source usage of the Mito AI server. When users hit the free tier limit, they must either upgrade to Mito pro or set their own open ai api key.
Yes, we need some new docs on getting started with mito-ai
> Accounts v1

- mito-ai/mito-ai/utils/open_ai_utils.py
- mito-ai/mito-ai/utils/telemetry_utils.py
- mito-ai/src/Extensions/AiChat/ChatMessage/ChatDropdown.tsx
- mito-ai/src/Extensions/VariableManager/VariableInspector.tsx
- Adds an error param for `mito_free_tier_limit_reached` so we can differentiate why errors occur. 
- Improves lambda function logging
- Prevents the variable manager from completely failing when 
- Lets users press `tab` to select an element from the @ mention dropdown. (I instinctually tried using tab a few times today and noticed that other tools like Zulip let you press tab or enter to accept).
- Removes `FUNCTIONS` from the @ mention dropdown. This is just exported from mitosheet and is a dict with all the mitosheet functions. The user has no need to interact with this. 
Try out all of the above. 
No.
> Dogfood 11 26 24

- mito-ai/package.json
- mito-ai/yarn.lock
Small PR to fix JupyterLab version pins. Inconsistent pinning of dependencies was leading to type errors (see below).
This PR makes sure that all of JupyterLab-related packages are using the same version of @jupyterlab/cells by updating the version pinning in the package.json.
Build the extension and see passing tests. 
No.
> sync jupyter lab version pins

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatMessage.tsx
- mito-ai/style/ChatTaskpane.css
- mito-ai/style/base.css
Makes the markdown variables pop. I think this is much more polished looking. 
Also, adds the css variables for more colors so we can continue to create uniform, polished features. These colors are also loaded into Figma :) 
Check it out. 
At some point we can update the photos in docs to reflect more polished UI.
> Improve markdown styling

- deployment/bump_version.py
Updated `get_pypi_version` to use the PyPi JSON endpoint. This should fix the issue when deploying, which can be seen in during [this deployment](https://github.com/mito-ds/mito/actions/runs/12202857186/job/34046429424#step:7:54). 
Open [bump_version.py](https://github.com/mito-ds/mito/blob/dev/deployment/bump_version.py) and run `bump_version`. There are some print statement which you can use to validate. 
N/A
> Using JSON endpoint to get latest package version number 

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatDropdown.tsx
- mito-ai/style/ChatTaskpane.css
Fixes https://github.com/mito-ds/mito/issues/1383
Create a variable with a really exotic type, and then try to access it using `@variable_name_here`. The type should be truncated. 
As an example, try:
```python
import numpy as np
array_int = np.array([1, 2, 3])
array_float = np.array([1.0, 2.0, 3.0])
```
N/A
> Fix: Variable Types Truncated 

- evals/README.md
- evals/asserts/equal_globals.py
- evals/eval_types.py
- evals/main.py
- evals/notebook_states.py
- evals/requirements.txt
- evals/test_cases/code_gen_tests/dataframe_transformation_tests.py
- evals/test_cases/code_gen_tests/function_tests.py
- evals/test_cases/smart_debug_tests/__init__.py
- evals/test_cases/smart_debug_tests/function_tests.py
- evals/test_cases/smart_debug_tests/import_tests.py
- evals/test_cases/smart_debug_tests/matplotlib_tests.py
- evals/test_cases/smart_debug_tests/pandas_tests.py
- evals/test_cases/smart_debug_tests/smart_debug_tests.py
- evals/test_runners/smart_debugger_test_runner.py
First 45 smart debugger tests
I tried for a while to support testing package installations and ran into a few problems. Primarily:
1. In order to run package installation commands like `!pip install matplotlib`, we need to be inside of a ipython kernel. This is doable and maybe we should move to this anyways because it more closely mirrors Jupyter. 
2. But, `!pip install` commands are not an in-memory operation—it’s a file system operation. Running it places files into the environment’s site-packages. That means, when we run a  `!pip install` command for the expected code, it ends up storing that package forever. This means successive runs of our test suite won't actually test if the Ai generated the right code without first resetting the environment. 
For now, let's not test package …
> Smart Debugger Evals

- .github/workflows/test-mitosheet-frontend.yml
Changes made in `mitoai_ui_tests` should no longer trigger mitosheet tests. This should speed up PR, getting rid of irrelevant tests. Currently, there are 59 tests that run when making a change in `mitoai_ui_tests`, most of which are mitosheet related, and unaffected. 
You could simulate Github actions locally, but for this it's probably best to keep an eye on the next PR. Any changes made to the `mitoai_ui_tests` dir should only trigger tests related to Mito AI.   
N/A
> Ignoring mitosheet Tests 

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatMessage.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/CodeBlock.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- tests/mitoai_ui_tests/mitoai.spec.ts
- tests/mitoai_ui_tests/utils.ts
Renamed the _Apply_ button to _Preview_. Hopefully this makes it clearer to users. 
Test a basic Mito AI workflow. Nothing should have changed, except the button names. 
Update this page on next release: https://docs.trymito.io/mito-ai/chat
> Renamed Apply Button to Preview

- .github/workflows/test-mitosheet-frontend.yml
The goal of #1409 was to not run mitosheet tests when changes were mad to mito-ai. However, I did not realize that when using `paths-ignore` you could only have one path and one ignored path listed. This would not have worked, since `paths` has two dirs listed. 
The solution was to remove `paths-ignore`, and use a `!` in `paths`.   
Screenshot of error:
Trigger Github actions, or wait for next PR and monitor. 
N/A
> Fixed Incorrectly Configured paths-ignore

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/commands.tsx
- tests/mitoai_ui_tests/mitoai.spec.ts
- tests/mitoai_ui_tests/shortcuts.spec.ts
CMD+Y now triggers preview, when appropriate. Also, moved shortcut tests to their own file. 
Note that the way key bindings are registered have been changed. We are now disposing bindings every time `codeReviewStatus` is updated. Here's a quick Claude explanation of why this is best practice:
1. Memory Leaks: Without disposing of key bindings, each time the useEffect runs (whenever codeReviewStatus changes), new key bindings are added without removing the old ones. This can lead to memory leaks and multiple bindings for the same keys.
2. Duplicate Handlers: Multiple active bindings for the same key combination can cause unexpected behavior, with multiple handlers firing for a single keystroke.
3. Cleanup Best Practices: React's useEffect cleanup function (returned function) is the proper …
> Added Preview Code Shortcut

- mito-ai/mito_ai/utils/open_ai_utils.py
- mito-ai/mito_ai/utils/telemetry_utils.py
Expanded logging for server key users. Additionally, we're now tracking the full prompt. 
Comment out `OPENAI_API_KEY` from your env vars, and send a few messages, use code explain and Start Debug. Then look in Mixpanel for the logs.  
N/A
> Expanded logging for server key users

- mito-ai/src/Extensions/emptyCell/EmptyCellPlugin.ts
- mito-ai/src/index.ts
- tests/jupyter_utils/jupyterlab_utils.ts
- tests/mitoai_ui_tests/mitoai.spec.ts
- tests/mitoai_ui_tests/utils.ts
Improves the robustness of our tests by adding a short timeout in between entering cell editing mode and beginning to type. This short timeout ensures that the cell is ready to accept user input. Prior to this, we would type and nothing would appear in the cell. 
The tests are all now passing locally, but not on the CI.. 
Nope
> Fix frontend tests

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatMessage.tsx
- mito-ai/src/components/TextButton.tsx
- mito-ai/style/ChatTaskpane.css
- mito-ai/style/TextAndIconButton.css
Switch the overwrite and copy buttons to grey so that the Apply or Reject buttons stand out more. 
Dark Mode:
Light Mode:
Try them out
Not yet
> Grey overwrite button

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatDropdown.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/ChatInput.tsx
- mito-ai/src/Extensions/AiChat/CodeDiffDisplay.tsx
- mito-ai/style/ChatDropdown.css
Address this issue https://github.com/mito-ds/mito/issues/1444
<details>
<summary> Improve diffs on dark mode by switching to Jupyter Lab colors. </summary>
</details>
<details>
<summary> Improve variable dropdown on dark mode by switching to Jupyter Lab colors. </summary>
</details>
Just try it out. 
Not yet
> improve dark mode diffs

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/style/TextAndIconButton.css
- mito-ai/style/base.css
- tests/mitoai_ui_tests/mitoai.spec.ts
- tests/mitoai_ui_tests/utils.ts
Updates the cell toolbar css strategy so that when we want to display the Accept and Reject buttons we always can. 
Read the css docstring for a more thorough explanation. 
Try it out + see tests. 
No
> Always show accept reject buttons

- mito-ai/src/Extensions/AiChat/AiChatPlugin.ts
- mito-ai/src/Extensions/ErrorMimeRenderer/ErrorMimeRendererPlugin.tsx
- tests/mitoai_ui_tests/mitoai.spec.ts
Do not focus on the chat input when using the Smart Debug button. We have already sent the message, so the user does not need to type anything. Without doing this, the active cell preview appears and is confusing. 
See test + try it out. 
No.
> No focus on smart debug

- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/AlertBlock.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/ChatMessage.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/style/ChatTaskpane.css
Logging the error type in the `chatHistorymanager`. This error type is then used in the newly created `AlertBlock` component to display richer messages:
Use a server key, and make sure you've used up all your free requests. Then make a request to trigger the error message.
N/A
> Added alert block for nicer error messages

- .github/workflows/test-mito-ai-backend.yml
- mito-ai/mito_ai/providers.py
- mito-ai/mito_ai/tests/open_ai_utils_test.py
- mito-ai/mito_ai/tests/providers_test.py
- mito-ai/mito_ai/utils/open_ai_utils.py
- mito-ai/setup.py
Added the following tests:
1. OS user, Mito Server, Below Limit
2. OS user, Mito Server, Over Limit
3. OS user, OpenAI key set, Below Limit
4. OS user, OpenAI key set, Over Limit
5. Pro user, Mito Server, Below Limit
6. Pro user, Mito Server, Over Limit
7. Pro user, OpenAI key set, Below Limit
8. Pro user, OpenAI key set, Over Limit
Note that I am only running tests on Python 3.10 and 3.11. I had to remove 3.8, because you cant use patches within a `with` loop. However, this shouldn't be too much of an issue since the code in question is only used for testing.
Full explanation from ChatGPT:
> The issue lies in the way you are using patch.dict and patch together in a with statement. In Python 3.8, patch.dict and patch objects are not context managers when combined using parentheses and do …
> Added Tests for Server Quota

- .github/workflows/prerelease-tests.yml
- .github/workflows/test-mito-ai.yml
- .github/workflows/test-mitosheet-frontend.yml
- mitosheet/mitosheet/scheduling/schedule_utils.py
Bumps upload-artifacts@v3 to v4 because v3 is deprecated: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
See that the tests still pass
No
> Bump upload artificats

- mito-ai/src/Extensions/InlineCompleter/index.ts
Fixes https://github.com/mito-ds/mito/issues/1479
This is an issue we've seen happen at least twice, where the default shortcut for accepting an inline completion was not set to `Tab`. To avoid this, we're simply setting the Tab key as the default for the `inline-completer:accept` command. This happens right after a user enables Mito AI for the first time. 
To keep this as nondestructive as possible, we're only using the `.jp-mod-inline-completer-active` selector, and setting the shortcut once. 
Disable Mito AI by updating `.jupyter/serverconfig/mitoaiconfig.json` so that `settingsChecked` is false. Then start the server, and look for the "enable Mito AI notification." 
https://docs.trymito.io/mito-ai/autocomplete#updating-keyboard-shortcuts
> Manually setting shortcut for inline-completer:accept

- .github/workflows/prerelease-tests.yml
- .github/workflows/test-mito-ai-backend.yml
- .github/workflows/test-mito-ai.yml
- .github/workflows/test-mitosheet-frontend.yml
- evals/eval_types.py
- evals/notebook_states.py
- evals/prompts/inline_code_completion_prompts/__init__.py
- evals/prompts/inline_code_completion_prompts/prod_prompt_v3.py
- evals/prompts/inline_code_completion_prompts/prod_prompt_v4.py
- evals/test_cases/inline_code_completion_tests/dataframe_transformation_tests.py
- evals/test_cases/inline_code_completion_tests/function_tests.py
- evals/test_cases/inline_code_completion_tests/loops.py
- evals/test_cases/inline_code_completion_tests/misc_tests.py
- evals/test_cases/inline_code_completion_tests/variable_tests.py
- evals/test_runners/code_gen_test_runner.py
- mito-ai/src/Extensions/InlineCompleter/provider.ts
- mito-ai/src/prompts/InlinePrompt.tsx
- tests/mitoai_ui_tests/aiInlineCompleter.spec.ts
Improves our autocomplete responses by changing what we're asking of the AI. Previously, we heavily relied on the Ai to only return the new code that the user should type. This wasn't working well. Now, we ask the AI to return the complete line of code and then deduplicate it with the end of the prefix and beginning of the suffix. 
To do so, autocomplete prompts in our evals can now optionally implement a post processing step. 
This PR also fixes a few broken evals and adds some new evals based on the prefix issues documented here https://github.com/mito-ds/mito/issues/1414
On the new set of evals our v3 prompt (with some of bug fixes suggested by @ngafar) scored an average of 63% across three runs and the new v4 prompt with this prefix/suffix stripping strategy scored an average 65.6% of …
> Do not repeat prefix and suffix in autocomplete

- mitosheet/css/elements/TextButton.css
- mitosheet/css/endo/GridData.css
- mitosheet/css/footer.css
- mitosheet/css/taskpanes/ControlPanel/ControlPanelTaskpane.css
- mitosheet/css/toolbar.css
- mitosheet/src/mito/components/elements/GetSupportButton.tsx
- mitosheet/src/mito/components/elements/TextButton.tsx
- mitosheet/src/mito/components/icons/SelectedSheetTabDropdownIcon.tsx
- mitosheet/src/mito/components/toolbar/PlanButton.tsx
- mitosheet/src/mito/utils/colors.tsx
Updates the colors used in the Mito Spreadsheet to use the Jupyter colors. This allows us to better support Dark Mode and to more seamlessly integrate into Jupyter. 
Old Light Mode:
New Light Mode:
Old Dark Mode: (The same as light mode since we didn't inherit colors from Jupyter themes)
New Dark Mode: 
Try it out and make sure all the colors work well. 
I don't think we need to update now.
> Update mitosheet to use Jupyter colors

- .github/workflows/deploy-mitosheet-mitoinstaller.yml
- .github/workflows/prerelease-tests.yml
- .github/workflows/test-mito-ai.yml
- .github/workflows/test-mitoinstaller.yml
- .github/workflows/test-mitosheet-frontend.yml
- .github/workflows/test-mitosheet-mypy.yml
- .github/workflows/test-mitosheet-python.yml
- mito-ai/setup.py
- mitosheet/mitosheet/ai/recon.py
- mitosheet/mitosheet/code_chunks/melt_code_chunk.py
- mitosheet/mitosheet/mito_backend.py
- mitosheet/mitosheet/tests/api/test_get_available_snowflake_options_and_defaults.py
- mitosheet/mitosheet/tests/step_performers/test_melt.py
- mitosheet/mitosheet/tests/step_performers/test_merge.py
- mitosheet/setup.py
- tests/requirements.txt
Drops Python 3.8 from our CI since it has reached End of Life. 
See that tests pass. 
Yes. We now support Python 3.9 and higher.
> .github: remove python 3.8 for end of life

- mito-ai/src/Extensions/InlineCompleter/index.ts
- tests/mitoai_ui_tests/basicInlineComplete.spec.ts
The user downloading Mito AI is enough of an expression of them opting in to wanting Mito AI. So now we don't ask them to turn on the feature since we saw that the vast majority of people did not notice the notification.
Let's test this thoroughly and then merge directly into main so we can get this deployed asap and see if it helps numbers.
Reset your environment and make sure Mito AI turns on. 
No.
> New auto enable mito ai

- mito-ai/src/Extensions/InlineCompleter/index.ts
- tests/mitoai_ui_tests/basicInlineComplete.spec.ts
The user downloading Mito AI is enough of an expression of them opting in to wanting Mito AI. So now we don't ask them to turn on the feature since we saw that the vast majority of people did not notice the notification. 
@ngafar I would be down to test this thoroughly and then merge directly into main so we can get this deployed asap and see if it helps numbers. 
Clear your mito-ai server config and then make sure Mito AI is correctly turned on. 
No
> Auto enable mito-ai without waiting for Enable Button

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
Fixes https://github.com/mito-ds/mito/issues/1452
Send a message using Mito AI chat, then accept. The cursor should now be in the active cell, allowing you to run the cell right away.
N/A
> Return focus to active cell after accept

- mito-ai/src/Extensions/ErrorMimeRenderer/CollapsibleWarningBlock.tsx
- mito-ai/src/Extensions/ErrorMimeRenderer/ErrorMimeRendererPlugin.tsx
- mito-ai/src/Extensions/ErrorMimeRenderer/OutputBlock.tsx
- mito-ai/style/ErrorMimeRendererPlugin.css
- mito-ai/style/base.css
- tests/mitoai_ui_tests/misc.spec.ts
Addresses https://github.com/mito-ds/mito/issues/1453
Run code that creates warning, some examples:
```python
import warnings
warnings.warn("This is a warning message.")
```
```python
import numpy as np
data = np.random.random(100000).reshape(10, 100, 100) * np.nan
np.seterr(all="ignore")
np.nanmedian(data, axis=[1, 2])
```
No
> Collapsable warnings

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/components/DropdownMenu.tsx
- mito-ai/style/DropdownMenu.css
Update DropdownMenu to allow secondary action icons on the right, similarly how other apps do it
The dropdown items then would look like this:
```
| primparyIcon | label | ... | secondaryActions |
```
_Inspiration: VSCode Copilot_
_Example usage (from upcoming feature)_
> Secondary icons in dropdown

- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/ChatInput.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/ChatMessage.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- tests/mitoai_ui_tests/agent.spec.ts
1. When you edit an agent:planning step, don't add the active cell as context.
2. Don't clear that chat when switching to agent planning mode
3. Scroll to the new message returned from the agent, the agent:execute code in the chat right away. Currently, we don't scroll to it until after we apply and execute the code I think.
Test out the three scenarios above. 
N/A
> Agent Mode: v1 Polish

- mito-ai/mito_ai/prompt_builders/agent_planning_prompt.py
- mito-ai/mito_ai/utils/telemetry_utils.py
- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/ChatInput.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/ChatMessage.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/style/ChatInput.css
- mito-ai/style/ChatTaskpane.css
- tests/mitoai_ui_tests/agent.spec.ts
- Added `user_input` field when logging agent mode prompts. We no longer have to go though the `full_prompt` to see the user's question.
- Editing the original agent mode prompt will erase all plans, and generate a new plan. Previously, this would just add a new message to the chat, and the user would have to scroll to see the new plan. 
- Agent plan messages now default to `grey-900`. Using the Jupyter colors meant that plans were unreadable in dark mode.
While it is an extension of chat, we also want to make sure users understand that it is a slightly different paradigm. To this extent:
- Added purple border to agent mode input.
- Added glow animation when switching to agent mode. 
Try it out.
N/A
> Agent Mode: Pre-Release Polish

- mito-ai/src/utils/agentActions.tsx
- mito-ai/src/utils/notebook.tsx
This update fixes a bug in agent mode's smart debugging: if a cell produces both a warning and an error message, the debugging feature would fail. Now, smart debugging works correctly even when both types of messages are output.
1. Enter agent mode
2. Create any plan. 
3. Edit the plan so that one of the steps reads, "Using python, create a warning and an error message."
When the plan is run, you should see that the cell with the warning and error will trigger the smart debug workflow.  
N/A
> Agent: Fix for warnings + errors

- mito-ai/style/ChatInput.css
Fixes https://github.com/mito-ds/mito/issues/1550
Also fixes issue where the @ mention dropdown is not visible when the selected cell has no code.  
Create a df with tons of cols, use the @ mention dropdown.
N/A
> Fix Mentions Scrolling

- mito-ai/mito_ai/utils/open_ai_utils.py
Set a timeout on the actual http request to give it enough time for the Open AI API. The default was 20 seconds, which was out of sync with the OpenAI timeout and max retries we were setting. 
I'm not sure how to test this exactly...
> mito-ai: update http request timeout

- mito-ai/mito_ai/handlers.py
- mito-ai/mito_ai/message_history.py
- mito-ai/mito_ai/models.py
- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/utils/websocket/models.ts
- Moves the system prompt creation into the backend so we can create a different system prompt for different thread types. In the near future, we will create a big system prompt for agent mode.
- Creates a ThreadID type so we can more easily differentiate when an variable is a ThreadID and when it is just a string
All tests are passing
None needed
> System prompt backend only

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatMessage.tsx
- mito-ai/style/MarkdownMessage.css
Brings back the styling for these code blocks in markdown. The styling got accidentally deleted in a refactor I did. 
At some point, we can add screenshot testing for things like this. 
Just make sure that it works! 
Nope.
> mito-ai: bring back markdown code styling

- mito-ai/mito_ai/completion_handlers/agent_auto_error_fixup_handler.py
- mito-ai/mito_ai/completion_handlers/agent_execution_handler.py
- mito-ai/mito_ai/completion_handlers/chat_completion_handler.py
- mito-ai/mito_ai/completion_handlers/code_explain_handler.py
- mito-ai/mito_ai/completion_handlers/smart_debug_handler.py
Display optimized messages were reconstructed from metadata incorrectly on the backend as a result of recent refactors of chat completions. The way the display prompts constructed diverged from the way they are constructed on the front end leading to change when restoring from chat history
> Fix display prompts reconstruction on backend

- mito-ai/mito_ai/completion_handlers/open_ai_models.py
- mito-ai/mito_ai/providers.py
- mito-ai/mito_ai/tests/open_ai_utils_test.py
- mito-ai/mito_ai/tests/providers_test.py
- mito-ai/mito_ai/tests/server_limits_test.py
- mito-ai/mito_ai/utils/db.py
- mito-ai/mito_ai/utils/open_ai_utils.py
- mito-ai/mito_ai/utils/schema.py
- mito-ai/mito_ai/utils/server_limits.py
- mito-ai/src/Extensions/AiChat/ChatMessage/AlertBlock.tsx
- mito-ai/src/Extensions/InlineCompleter/provider.ts
- mito-ai/src/Extensions/status/index.tsx
- mito-ai/style/ChatMessage.css
- trymito.io/pages/plans.tsx
- Updates the free tier so that it now resets each month. The purpose of this is to let casual users continue to use Mito Ai for free and let power users get unlimited access to Mito AI. 
- Updates the upgrade to Mito Pro CTA 
- Updates the pricing page. 
1. Try out the different configuration options + look at all of the new tests to make sure this functionality works as expected since it is more complicated. 
2. Make sure the Mito Pro CTA in the notification and the taskpane look correct
3. Checkout the new pricing page
We should make sure the docs reflect this
> Monthly limit

- mito-ai/mito_ai/utils/open_ai_utils.py
- mito-ai/src/Extensions/InlineCompleter/provider.ts
Added a flag to make sure we are only showing the inline completion error notification once per session. If the user closes it, they won't see it again, nor will it stack up as they keep typing. 
Update `MITO_AI_PROD_URL` in `open_ai_utils.py`, and break the URL. Then start typing. 
N/A
> Single error notification for inline completion

- mito-ai/mito_ai/completion_handlers/agent_execution_handler.py
- mito-ai/mito_ai/completion_handlers/chat_completion_handler.py
- mito-ai/mito_ai/models.py
- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/utils/websocket/models.ts
Somewhere between the refactors, the extension lost the ability to properly edit the message. Message index was missing from the agent metadata and not transmitted for chat metadata; no action to truncate message history on the backend was taken. This PR fixes that issue by
- updating backend/frontend models to include message index where needed
- send message index when editing a message on the frontend
- call to truncate message function when index is present in the received message on the backend
> Fix message editing

- .github/workflows/deploy-mito-ai.yml
- .github/workflows/deploy-mitosheet-mitoinstaller.yml
- .github/workflows/lint-mito-ai-typescript.yml
- .github/workflows/lint-mitosheet-typescript.yml
- .github/workflows/prerelease-tests.yml
- .github/workflows/test-mito-ai-backend.yml
- .github/workflows/test-mito-ai-frontend.yml
- .github/workflows/test-mito-ai-jest.yml
- .github/workflows/test-mito-ai-mypy.yml
- .github/workflows/test-mitoinstaller.yml
- .github/workflows/test-mitosheet-frontend.yml
- .github/workflows/test-mitosheet-mypy.yml
- .github/workflows/test-mitosheet-python.yml
- mitosheet/mitosheet/scheduling/schedule_utils.py
This PR:
- bumps Ubuntu image in actions from 20.04 to 24.04. The motivation is that 20.04 support in actions in going away starting  4/1/25: https://github.com/actions/runner-images/issues/11101.
- update GitHub Actions versions to to latest versions
> Update GitHub Actions to use Ubuntu 24.04 and latest action versions

- .github/workflows/test-mitoinstaller.yml
`3.10` is interpreted as a float. Therefore it will result in installing Python 3.1 as seen in 
https://github.com/mito-ds/mito/actions/runs/14134579170/job/39603093834?pr=1595
Version should always be typed as string.
> CI: Fix Python version should be string

- .github/workflows/lint-mito-ai-typescript.yml
- .github/workflows/lint-mitosheet-typescript.yml
- .github/workflows/prerelease-tests.yml
- .github/workflows/test-mito-ai-backend.yml
- .github/workflows/test-mito-ai-frontend.yml
- .github/workflows/test-mito-ai-jest.yml
- .github/workflows/test-mito-ai-mypy.yml
- .github/workflows/test-mitoinstaller.yml
- .github/workflows/test-mitosheet-frontend.yml
- .github/workflows/test-mitosheet-mypy.yml
- .github/workflows/test-mitosheet-python.yml
This a maintenance PR that drops `styfle/cancel-workflow-action` in favor for builtin GitHub CI feature, [concurrency](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency)
> Use concurrency instead of styfle cancel action

- mito-ai/src/Extensions/ContextManager/VariableInspector.tsx
Removes the Mito exported functions from the variables we pass to the LLM. These are mostly irrelevant and the LLM can probably figure it out if it needs too. 
Making the Defined Variables in my testing notebook go from 5608 to 993 characters 
In retrospect, not sure this was really worth the 35 mins it took... I don't think this is where users are running into messages being too long
Try it out! 
No
> mito-ai: do not add mito functions to context

- mito-ai/mito_ai/providers.py
- mito-ai/mito_ai/utils/telemetry_utils.py
Just makes it so when an error occurs, it also ways what the attempted operation was. 
Just raise an exception in `request_completions`
Nope
> Slightly improved error tracking

- mito-ai/mito_ai/prompt_builders/agent_system_message.py
- mito-ai/src/Extensions/AiChat/ChatMessage/MarkdownBlock.tsx
Switches the format of the citation to help the AI generate citations more consistently. Previously, we were asking for the citation in this format: `{"type": "citation", "cell_id": "<cell_id>", "line": "<line_number>"}`, but often the agent starts to send a citation the AI response ends at `{`. 
Switching to the format `[MITO_CITATION:cell_id:line_number]` seems to fix this issue. 
Try it out. 
No.
> mito-ai: switch citation structure

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatInput.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/ChatMessage.tsx
- mito-ai/src/tests/AiChat/ChatInput.test.tsx
Fixes https://github.com/mito-ds/mito/issues/1592. No code cell preview is shown in agent mode. 
Create a cell with code in it. Then switch to agent mode, and start typing. You should notice that no active cell preview is shown.
N/A
> No Cell Preview in Agent Mode

- mito-ai/mito_ai/tests/server_limits_test.py
- mito-ai/mito_ai/utils/server_limits.py
Don't count naming the chat against the user's quota. 
Double check that when we automatically name the chat, we don't count that against the user's quota so they actually get a chance to use the tool :) 
Nope
> Quota accounting

- mito-ai/mito_ai/providers.py
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/tests/AiChat/ChatMessage.test.tsx
- mito-ai/src/utils/websocket/websocketClient.ts
- Fix for issue where upgrade message not shown when streaming.
- Updating Mito Server quota for streaming messages.
Make sure you are using the server key, and open the user file. Next, send messages until you hit the limit.
You should notice that (1.) usage is incremented, and (2.) the upgrade message is shown when limit is reached. 
N/A
> Display Upgrade Message on Quota Hit (Streaming Fix)

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
Since defaulting to agent mode, chat messages started to show up in the agent tab. However, this should fix that issue. We will still default to opening in agent mode, assuming there is no chat history, or the last thread was not a chat thread. 
1. Delete all chat history, then start the server. You should notice that we still open to agent mode.
2. Create an agent message, and refresh. Should open in agent mode.
3. Send a chat message, and refresh. Should open in chat mode.  
N/A
> Messages show up in correct tab

- mito-ai/mito_ai/handlers.py
- mito-ai/src/utils/websocket/websocketClient.ts
In situation where JupyterLab is running behind OAuth 2, like in JupyterHub with HTTPS enabled, the HEAD method is not supported. We use HEAD request to check the connection before opening a websocket. This PR replaces HEAD request with a query parameter in the main GET request thus enabling the extension to work with OAuth 2 flow.
1. Added error handling to the `initialize()` method to better report connection failures
2. Implemented a flag `_initializationInProgress` to prevent multiple concurrent initialization attempts
3. Added proper cleanup of existing sockets before creating new ones
4. Added a connection timeout to detect stalled connections
5. Reset reconnection counters after failures to ensure future attempts can succeed
6. Created a more robust error propagation
> Fix issues with webscockets

- mito-ai/mito_ai/providers.py
- mito-ai/style/GetCellOutputToolUI.css
Fixes https://github.com/mito-ds/mito/issues/1620. Updated the CSS for the agent output tool. 
Also, fixed a bug in `providers.py` --  we we're referencing a variable that does note exists (`_models`).  
Send a message that will require the agent to confirm the output. For example, create a `name` variable, and ask the Agent to "print name and make sure it says..." 
Once you have the get output `GetCellOutputToolUI` component on screen, toggle between the different themes.   
N/A
> Agent output tool - dark mode fix

- mito-ai/mito_ai/prompt_builders/agent_smart_debug_prompt.py
- mito-ai/mito_ai/prompt_builders/smart_debug_prompt.py
- mito-ai/mito_ai/providers.py
Fixes https://github.com/mito-ds/mito/issues/1627. Adds instructions on how the Agent can install packages it needs. 
Uninstall matplotlib:
```bash
!pip uninstall matplotlib
```
Then ask the Agent to "make a chart." 
The Agent should assume matplotlib is already installed, and start to create a chart. When it runs the code you should get a ModuleNotFoundError. 
Alternatively, you could ask the Agent to use a library you don't have installed (seaborn, pytorch, etc). However, it may install the package before getting started. To avoid this behavior you may need to prompt it to not install anything until it hits an error. 
N/A
> Agent mode can install packages

- mito-ai/mito_ai/utils/telemetry_utils.py
This PR adds new telemetry metrics to track:
- `is_jupyterhub` -- detect if the user is running in JupyterHub
- `is_mito_jupyterhub` -- detect if the user is running on Mito's own infrastructure
- Install in JupyterHub
- Send a completion
- Check telemetry logs
- JupyterHub detection should work automatically
> Add JupyterHub detection to telemetry

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
Addresses https://github.com/mito-ds/mito/issues/1628.
Smart debug and code will now be added to the current chat history. This way you can continue to work and debug in the same thread. 
Send a few messages, create an error, debug the error. You should see the smart debug message in the same chat. 
N/A
> Smart debug not creating new chat

- mito-ai/src/Extensions/AiChat/ChatMessage/Citation.tsx
Fixes https://github.com/mito-ds/mito/issues/1653
Before we used to scroll to the center of the cell. This would get the highlighted line in focus most of the time. 
This PR introduces a way of dynamically determine the scroll position by determining where the line is located within the cell. If the line is above the halfway mark, we scroll to the start of the cell, and if the line is below the half way mark, we scroll to the end. 
Create a few cells with lots of content, make sure you need to scroll to see cells. Then ask a question that will return a citation. If the cell is higher up in the cell, the window should scroll so that the top of the cell is reached.
N/A
> Citation scroll position dynamically set

- mito-ai/setup.py
This resolves this bug we were seeing.
> mito-ai: update jupyterlab version requirements

- mito-ai/src/Extensions/ContextManager/ContextManagerPlugin.ts
- mito-ai/src/tests/ContextManager/ContextManagerPlugin.test.tsx
Fixes https://github.com/mito-ds/mito/issues/1718
When the kernel is refreshed, the variable manager is set to an empty array. 
1. Create a notebook with some variables. 
2. Take note of what is in the Context Manager. 
3. Then refresh the kernel.
4. The Context Manager's `_variable` field should be empty. 
N/A
> Clearing Variable Manager on Kernel Refresh 

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatInput.tsx
Addresses https://github.com/mito-ds/mito/issues/1540
Files from the Context Manager are now included in the `@` dropdown in chat task pane. 
Add a csv file, then use the `@` feature in the chat task pane. From the dropdown menu, you should see the csv file.  
Yes, can we can add to https://docs.trymito.io/mito-ai/chat#using-variable-mentions
> Added Files in Dropdown

- mito-ai/src/Extensions/ToolbarButtons/ToolbarButtonsPlugin.tsx
This is a small change to the label of the `Build App` button which is used to convert the outputs to a streamlit dashboard.
> Modifying the label of button from 'Build App' to 'Deploy App'

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatMessage.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/CodeBlock.tsx
- mito-ai/src/Extensions/ToolbarButtons/ToolbarButtonsPlugin.tsx
- mito-ai/src/tests/AiChat/ChatMessage.test.tsx
- mito-ai/src/tests/AiChat/CodeBlock.test.tsx
Updates the taskpane so that it does not show the `Overwrite` or `Copy` button until the entire code cell is generated by the AI. This is useful for streaming when where we don't want the user to apply the code to the cell before it's done generating. If they do, it leads to pretty confusing behavior. 
I saw a user do this yesterday where they:
1. Pressed apply before the code was done generating
2. Ran the code and it errored
3. Pressed the `fix in ai chat` button
4. Got the AI response and the the original code was still rendering at the same time, leading to a bunch of unstyled code that was just very hard for them to understand what was going on. 
Note: Sometimes the Ai generated code is displayed in markdown instead of the code cell until the entire code cell is done rendering. We …
> Apply when code is generated

- mito-ai/style/ChatTaskpane.css
Removes outer scrollbar on windows that serves no purpose.
> mito-ai: fix remove double scrollbar on taskpane

- mito-ai/mito_ai/completions/providers.py
- mito-ai/mito_ai/utils/telemetry_utils.py
- Update `log_ai_completion_success` function to accept and log model parameter
- Add model field to telemetry data for tracking model popularity in Mixpanel dashboards
- Update all call sites in `providers.py` to pass model information
> Add model tracking to AI completion telemetry

- mito-ai/mito_ai/completions/prompt_builders/chat_prompt.py
- mito-ai/mito_ai/completions/prompt_builders/chat_system_message.py
- mito-ai/mito_ai/completions/prompt_builders/prompt_constants.py
This is an effort to fix: https://github.com/mito-ds/mito/issues/1790
Added "CRITICAL CODE UPDATE RULES" section - This creates a prominent, separate section that stands out from other instructions
This is not entirely bulletproof (again, as it's a prompt engineering method).
- The current chat prompt already mentions returning "the full code cell" but the language may not be emphatic enough about the replacement behavior
- Occam's Razor: The simplest solution is often the best
- The fact that Agent mode doesn't have this issue suggests it's primarily a prompting problem, not an architectural one.
- Multiple reinforcing statements ensure the message is clear from different angles
> Full code cell response in chat mode

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
Fix for: [Don't auto scroll to bottom when user is scrolled up in chat to read](https://github.com/mito-ds/mito/issues/1717)
N/A
> Disabled autoscroll when the user has scrolled up

- trymito.io/components/CTAButtons/CTAButtons.tsx
- trymito.io/pages/index.tsx
- Fix the cta on small screens. It used to overflow like this: 
- Removes the streamlit app gallery since that is not what we want users paying attention to. 
Try it out!
> Fix cta on small screens

- mito-ai/mito_ai/constants.py
- mito-ai/src/components/ModelSelector.tsx
- mito-ai/src/tests/AiChat/ModelSelector.test.tsx
This resolves the issue of default model selection on a private window which simulates a new user. 
> Fixed the OpenAI bug and also changed the default model

- mito-ai/mito_ai/anthropic_client.py
I tested chat on a user provided example that had a large code cell. Anthropic stopped responding because it hit the max_tokens limit. We don't want that to happen, so I just bumped the max_tokens to be extra high. 
Try it out. There should be no difference on small responses.
Nope.
> Update anthropic max_tokens limit

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/utils/waitForNotebookReady.ts
When using the website to start a conversation with mito-ai. There is still sometimes a race condition where we try to build the map of cells before the cells are loaded (is my understanding). This just makes sure that the cells are loaded before hand. 
We don't have the infra to properly test this before releasing it because we don't have a dev JHuB set up right now. 
No.
> Update wait for notebook

- .github/workflows/test-mito-ai-backend.yml
- .github/workflows/test-mitosheet-python.yml
- mitosheet/setup.py
Update the CI to test Python 3.13 also drops support for old pandas versions that are no longer maintained.
See that the tests pass + try using Python 3.13 with mitosheet + mito-ai
No
> .github: add CI testing for 3.13

- mito-ai/src/tests/AiChat/AssistantCodeBlock.test.tsx
- mito-ai/src/tests/AiChat/ChatInput.test.tsx
- mito-ai/src/tests/AiChat/ChatMessage.test.tsx
Added new unit tests:
- Make sure AssistantCodeBlock can not be edited.
- Double click to edit ChatMessage. 
- Checking for cell preview in ChatInput.
- Cell preview is updated when active cell is updated.
Make sure Jests tests are passing.
N/A
> More chat unit tests

- mito-ai/mito_ai/anthropic_client.py
- mito-ai/mito_ai/constants.py
- mito-ai/mito_ai/gemini_client.py
- mito-ai/mito_ai/openai_client.py
- mito-ai/mito_ai/tests/message_history/test_generate_short_chat_name.py
- mito-ai/mito_ai/tests/providers/test_anthropic_client.py
- mito-ai/mito_ai/tests/providers/test_azure.py
- mito-ai/mito_ai/tests/providers/test_gemini_client.py
- mito-ai/mito_ai/tests/providers/test_model_resolution.py
- mito-ai/mito_ai/tests/providers/test_openai_client.py
- mito-ai/mito_ai/utils/anthropic_utils.py
- mito-ai/mito_ai/utils/gemini_utils.py
- mito-ai/mito_ai/utils/open_ai_utils.py
- mito-ai/mito_ai/utils/provider_utils.py
- mito-ai/mypy.ini
Creates a helper function for deciding if we need to use a fast model or the selected model. In doing so, we make the decision criteria based on the message type instead of if there is response_format_info provided or not. And moves all of the decision logic into the client utils to keep the clients clean. 
See the new tests + try it out. 
Nope.
> Set model in helper

- .github/workflows/test-mito-ai-frontend.yml
Try to speed up installing dependencies in GitHub actions by caching node modules
> .github: cache node modules

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/websockets/completions/CompletionModels.ts
In the backend `(mito-ai/mito_ai/completions/models.py line 33)`, the field is defined as `get_cell_output_cell_id: Optional[str]`, but in the front end `(mito-ai/src/websockets/completions/CompletionModels.ts line 47)`, it's defined as `cell_id?: string`
This mismatch means that when the agent sends a get_cell_output response, the frontend is looking for `agentResponse.cell_id` but the backend is sending `get_cell_output_cell_id`.
Before this PR, the evals failed:
- 9/10 times for claude models
- 4/10 times for gemini
- 4/10 times for gpt
After this PR, the evals failed:
- 2/10 times for claude models
- 1/10 times for gemini
- …
> BugFix: Get cell output was not actually getting the cell output

- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/tests/AiChat/ChatHistoryManager.test.tsx
Fixes https://github.com/mito-ds/mito/issues/1869
Start a new Agent chat, work with it, and keep a note of the assumptions the Agent makes. You should not see duplicate assumptions.
You can switch branches, and refresh the chat to see the number of assumptions that were removed as part of the deduplication process. 
No, all changes are behind the scenes.
> Remove Duplicate Agent Assumptions 

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatInput.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/tests/AiChat/ChatInput.test.tsx
- mito-ai/style/ChatInput.css
Passing the agent execution status to `ChatInput` and using the status to disable the input when the agent is working. 
Send a message in Agent mode, make sure you can't type while the agent is working. 
N/A
> Disable Chat Input When Agent is Working

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatInput.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/ChatMessage.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/tests/AiChat/ChatMessage.test.tsx
Trying to fix an error where a user is seeing:
```python
builtins.TypeError: AgentExecutionMetadata.__init__() got an unexpected keyword argument 'selectedRules'"
```
I can not recreate this issue without manually editing `agentExecutionMetadata` in the ChatHistoryManager, and adding a `selectedRules` field. 
However, I did notice that there are a few areas where `selectedRules` was being used as a variable name, when it should have been called `additionalContext`. The changes in this PR should not affect functionality, I've only renamed the variables for the sake of clarity. 
Also fixed a bug that was removing any context added on edit. 
- Send an agent message with a rule.
- Edit an agent message with a rule. 
No, behind the scenes change.
> selectedRules Bug Fix

- mito-ai/mito_ai/streamlit_conversion/streamlit_system_prompt.py
When you make a configuration change in the app, it will now show the streamlit loading indicator in the top right so you know the app is loading and not just broken! 
.
> mito-ai: bring back streamlit loading indicator

- mito-ai/src/Extensions/ToolbarButtons/ToolbarButtonsPlugin.tsx
- tests/mitoai_ui_tests/app_builder.spec.ts
I want to do a release today, but the preview app feature needs more testing, so moving it back to beta mode. 
Make sure only available in beta mode.
> mito-ai: move preview app back to beta

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatInput.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/ChatMessage.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/components/SelectedContextContainer.tsx
- mito-ai/src/tests/AiChat/ChatInput.test.tsx
- mito-ai/src/tests/AiChat/ChatMessage.test.tsx
- mito-ai/style/SelectedContextContainer.css
Removed the active cell preview (in Chat mode), and replaced it with an _Active Cell_ card in the Selected Context Container. 
- In chat mode you should be able to see the Active Cell card.
- In chat mode you should be able to click on the card, and go to the active cell.
- In Agent mode the card should not be visible. 
No, this should be self-explanatory.
> Active Cell Context Card

- mito-ai/mito_ai/__init__.py
Fixes this warning from appearing when trying to see matplotlib graphs
0. On dev, create a matplotlib graph and see that you get this warning instead of seeing the graph
1. Switch to this branch and rerun the graph, see the graph now! 
No
> mito-ai: set matplotlib inline

- mito-ai/src/Extensions/AiChat/ChatMessage/AlertBlock.tsx
- mito-ai/style/ChatMessage.css
Remakes the Alert that we show users when there is trouble with Mito. It now does a few things:
1. Gives them some instructions on how to fix things. Often, they just need to relaunch Jupyter because something funky happened. 
2. Adds a bit of logging so when something goes wrong, we at least know about it. 
3. Makes it look a bit better, I think. 
Add this line to the mito_server_utils.py file and then send a message
```raise ProviderCompletionException("431 Request Header Fields Too Large", 'OpenAI', 'LLMProviderError')```
No.
> mito-ai: better alert blocks

- mito-ai/.gitignore
- mito-ai/src/Extensions/ContextManager/VariableInspector.tsx
Fix for shapefiles blowing up the context window. When adding samples to the context manager, the VariableInspector will only add the first 50 characters. 
Add a shapefile, and have the Agent open it. You can then print the `contextManager` and look at the samples. 
No
> Truncating long samples in VariableInspector

- mito-ai/mito_ai/__init__.py
Tries to improve reliability of matplotlib graphs rendering by forcing Matplotlib to use the Jupyter inline backend.
Background: importing Streamlit sets os.environ["MPLBACKEND"] = "Agg" very early. In a Jupyter kernel, that selects a non‑interactive canvas and can trigger: "UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown" which prevents figures from rendering in notebook outputs. We preempt this by selecting the canonical Jupyter inline backend BEFORE any Matplotlib import, so figures render inline reliably. This must run very early. See: https://github.com/streamlit/streamlit/issues/9640
Should fix this: https://github.com/mito-ds/mito/issues/1918
Let's pay attention to this as we are developing. It doesn't seem to happen all the time, so if we see that the …
> mito-ai: use backend_inline matplotlib backend

- mito-ai/src/Extensions/AiChat/AiChatPlugin.ts
- mito-ai/src/Extensions/AiChat/jupyterSettingsManager.ts
Fixes https://github.com/mito-ds/mito/issues/1921
The root cause of this issue (as we expected) is that the virtual cell rendering was incorrectly calculating the height of cells + outputs and causing the notebook footer to be in the wrong place. Lesson learned here that if we see issues like this, we should try to see if there are Jupyter config options we can set to improve it! I should've checked that a long time ago :) 
https://github.com/user-attachments/assets/0a625005-48c7-4621-9e4f-d0df850fd06d
1. Make sure that you are automatically set onto defer mode by going to Jupyter settings and looking for `window`
2. Open a notebook with some graphs in it and a bunch of cells and then see that in `defer` mode there is no issue, but in `full` mode there is overlapping! This is easiest to …
> mito-ai: set default window mode to defer

- mito-ai/mito_ai/constants.py
- mito-ai/mito_ai/utils/mito_server_utils.py
Resolves: https://github.com/mito-ds/mito/issues/1925
When streaming responses failed, the frontend received a Runtime.StreamError with base64-encoded error body:
```
Lambda-Runtime-Function-Error-Type: Runtime.StreamError
Lambda-Runtime-Function-Error-Body: ZXJyb3lgcmVhZGluZyBhIGJvZHkgZnJvbSBjb25uZWN0aW9u
```
It looked like this: 
The generate_response_stream function was yielding a dictionary object when an error occurred:
```
yield {"error": f"There was an error accessing the OpenAI API: {str(e)}"}
```
FastAPI's StreamingResponse expects strings/bytes, not dictionaries. When it tried to encode the dict, it failed with: AttributeError: 'dict' object has no attribute 'encode'
Updated the error handling to yield a string with an error marker that the frontend can detect and parse:
``` …
```
> mito-ai: better stream error handling with v2 lambda

- mito-ai/mito_ai/app_manager/handlers.py
- mito-ai/mito_ai/app_manager/models.py
- mito-ai/mito_ai/app_manager/utils.py
- mito-ai/src/Extensions/AppManager/AppsList.tsx
- mito-ai/src/Extensions/AppManager/ListAppsAPI.ts
- mito-ai/src/tests/AppManager/AppsList.test.tsx
- mito-ai/src/tests/AppManager/ListAppsAPI.test.tsx
- mito-ai/src/websockets/appManager/appManagerModels.ts
- mito-ai/style/AppsList.css
This PR includes changes in info provided to the user about his/her apps. Instead of showing when the app was first created, we now show when it was last deployed.
This PR is supported by another PR in the monorepo as well which is going to modify the status of the app with the last_deployed field.
\-
> Displaying "Last deployed at" instead of "Created at" in the manage apps pane

- mito-ai/mito_ai/completions/completion_handlers/agent_execution_handler.py
- mito-ai/mito_ai/completions/completion_handlers/chat_completion_handler.py
- mito-ai/mito_ai/completions/completion_handlers/utils.py
- mito-ai/mito_ai/completions/models.py
- mito-ai/mito_ai/completions/prompt_builders/utils.py
- mito-ai/mito_ai/file_uploads/handlers.py
- mito-ai/mito_ai/tests/completions/completion_handlers_utils_test.py
- mito-ai/mito_ai/tests/file_uploads/test_handlers.py
- mito-ai/src/Extensions/AiChat/ChatMessage/ChatInput.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/Extensions/AiChat/utils.tsx
- mito-ai/src/components/AttachFileButton.tsx
- mito-ai/src/websockets/completions/CompletionModels.ts
This PR fixes two bugs:
1. Large images break the websocket connection - When a large image is uploaded (>1mb), the Base64 encoding is so large that sending it all in one request to the backend will cause a websocket disconnect. To fix this, we are encoding the image on the backend. 
2. File types hardcoded - When we are creating the final prompt message on the backend, we were prefixing everything with "image/png." For OpenAI requests, this was not issue. However, for Claude, you need to use the correct type.  
Also, because we've drastically simplified the encoding logic, I was able to add support for multiple image uploads. 
Upload a few image, use different providers. Make sure your images are large, ideally >5mb. 
N/A, bug fix.
> Image Upload Size and Type Fix

- mito-ai/style/ChatInput.css
- mito-ai/style/SelectedContextContainer.css
Previously, the chat input UI component would overflow horizontally when a file with a long name was attached, causing the action buttons ("Attach File", "@ Add Context") and file pills to break the layout. This made the chat input difficult to use and visually inconsistent, especially with multiple context items or long file names.
- Updated the CSS for the `.context-container` class in ChatInput.css:
- Added `display: flex;`, `flex-wrap: wrap;`, and `gap: 8px;` to ensure that context buttons and file pills wrap to the next line instead of overflowing.
- This change keeps the chat input layout clean and usable, regardless of the number or length of attached files and context items.
- Verified in JupyterLab:
- Attached files with long names and multiple context items.
- Confirmed that …
> feat:fix for context buttons overflow chat input

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatDropdown.tsx
- mito-ai/src/tests/AiChat/ChatDropdown.test.tsx
- mito-ai/style/ChatDropdown.css
Fixes https://github.com/mito-ds/mito/issues/1945 by ensuring that only three of each type (rule, csv, etc.) is shown by default. 
Search, and make sure what you are looking for shows up in the context menu dropdown. Test both the button and the `@` tag. 
It might also be helpful to create a bunch of CSVs to make sure they don't take over the default dropdown window. 
No, should not need an explanation.
> Context Menu Limits

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatInput.tsx
- mito-ai/style/ChatInput.css
Fixes https://github.com/mito-ds/mito/issues/1909
This PR introduces a hight limit for the chat input, so that really long content does not break scrolling. 
Go to [lipsum.com](https://www.lipsum.com/) and generate 15 paragraphs of text, then paste it into the chat task pane. You should see that the height is capped to 350px, and vertical scrolling is enabled. 
N/A
> Set Max Height For Chat Input

- mito-ai/src/Extensions/AppPreview/utils.ts
Auto-closes preview notification after 5s. This way users don't have a stack of notifications as they rebuild their app during development.
Rebuild the app, make sure the notification dissapears.
N/A
> Auto-Close Preview Notification 

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatInput.tsx
- mito-ai/style/ChatInput.css
Fix for huge amounts of white space that appears on top of messages when editing:
Why this is happening, from Cursor:
> The `margin-top: auto` in the .chat-input-container CSS is used to push the chat input to the bottom of its flex container.
Send a message, edit, make sure the message does not have whitespace on top.
N/A
> Fix For Excessive Whitespace When Editing Message

- mito-ai/src/Extensions/AppDeploy/DeployAppNotification.tsx
- mito-ai/src/Extensions/AppDeploy/DeployStreamlitApp.ts
- mito-ai/src/tests/AppDeploy/NotebookToStreamlit.test.tsx
On clicking the deploy app button, the in-progress notification wasnt immediate, causing some confusion as to whether the process is running. This PR fixes that by immediately showing an in-progress notification
\-
> changes to immediately show the app deploy notifications
