mito-ds/mito

- mitosheet/package.json
- mitosheet/setup.py
- mitosheet/switch.py
> license: set pypi licenses properly, link to correct websites

- mitosheet/mitosheet/saved_analyses/save_utils.py
- mitosheet/mitosheet/saved_analyses/schema_utils.py
- mitosheet/mitosheet/saved_analyses/upgrade.py
- mitosheet/mitosheet/transpiler/transpile.py
- mitosheet/mitosheet/updates/append_user_field.py
- mitosheet/mitosheet/updates/checkout_step_by_idx.py
- mitosheet/mitosheet/updates/replay_analysis.py
- mitosheet/mitosheet/updates/set_user_field_update.py
- mitosheet/mitosheet/updates/update_feedback_v2_object.py
> mitosheet: add more types for better type checking

- mitosheet/installer/mitoinstaller/commands.py
- mitosheet/installer/mitoinstaller/installer_steps/mitosheet_installer_steps.py
- mitosheet/installer/tests/test_upgrades.py
> mitoinstaller: automatically move from mitosheet3 -> mitosheet

- docs/README.md
- docs/getting-started/installing-mito/README.md
- docs/getting-started/installing-mito/common-install-errors.md
- docs/getting-started/tutorial.md
- docs/how-to/creating-a-mitosheet/README.md
- docs/how-to/importing-data-to-mito.md
- docs/how-to/interacting-with-your-data/README.md
See title. I added this callout to the top three docs pages we get by traffic (where it also seemed unobtrusive/helpful there). Let me know what you think.
N/A.
See title.
> docs: add links to our github, and move all old hubspot links to discord

- trymito.io/pages/_app.tsx
- trymito.io/pages/index.tsx
- trymito.io/pages/plans.tsx
I also added it to gitbooks as well, check that too.
Note we have to wait to deploy this until we do the mega-deploy of everything - which is one disadvantage of the monorepo + our current deployment process currently.
Test the plans page on Vercel.
No.
> Add intercom to the plans page

- mitosheet/src/components/elements/Input.tsx
- mitosheet/src/components/modals/SignupModal.tsx
Fixes the autofocus in inputs, and removes some complexity around forward ref (which we no longer need). Test signup to, as autofocus works here now as well!
Closes #56 
Test pivot dropdown, and signup.
No.
> mitosheet: fix autofocus on inputs

- mitosheet/src/components/Mito.tsx
Closes #59 
Import same df twice. Edit one column and open unique values. Switch to other sheet. Will reload.
No.
> mitosheet: fix bug when sheets share column id

- mitosheet/mitosheet/step_performers/filter.py
- mitosheet/mitosheet/tests/steps_performers/test_filter.py
Resolves https://github.com/mito-ds/monorepo/issues/102
This is actually a really small change, but because I now have Black automatic styling, it fixed up a ton of lines of code... 
The only places you need to care about are:
1. The new test starting on ine 628 of test_filter.py
2. Lines 122-126 of filter.py
See test case in issue 
No.
> Fix bug in filtering mixed data types using contains filter

- mitosheet/mitosheet/updates/replay_analysis.py
See title.
Do something, edit the UUID to something random, and make sure log is generated.
No.
> mitosheet: log not existant replay analysis

- mitosheet/mitosheet/steps_manager.py
- mitosheet/src/components/Mito.tsx
Tries to narrow down the issues with arg updates by providing more logs and error messages. Will help address #88 
Make sure nothing broken.
No.
> mitosheet: add better logging for race conditon failures on commands

- mitosheet/mitosheet/mito_widget.py
Since I'm secure in the vs code and collab checking, we can log that here.
After we merge into dev, we can test this!
No.
> mitosheet: add better error messages when certainly in wrong location

- mitosheet/src/plugin.tsx
Fixes https://github.com/mito-ds/monorepo/issues/123
Follow steps in issue
None.
> Generate code even if no code cell exists

- mitosheet/mitosheet/mito_analytics.py
- mitosheet/mitosheet/mito_widget.py
- mitosheet/src/components/endo/ColumnHeaders.tsx
This PR fixes two minor bugs:
1. Adding a column with no data would lead to a confusing log. 
2. Reordering columns while editing a pivot table could break ur pivot table.
See takeaways from new logging here: https://www.notion.so/trymito/New-Log-Analysis-55c94d274bcb43ca8fdeb066ccc56d5f
Make sure all the new aggregate logs are getting generated. Make sure new processing logs are generated. Test that the two bugs that existed before are no longer happening (checking logs for the first, and making sure that reordering closes a pivot table).
No.
> mitosheet: update logging approach based on new logs

- mitosheet/src/components/endo/utils.tsx
- mitosheet/src/components/taskpanes/ControlPanel/ControlPanelTaskpane.tsx
- mitosheet/src/components/taskpanes/ControlPanel/SummaryStatsTab/ColumnSummaryStatistics.tsx
- mitosheet/src/components/taskpanes/ControlPanel/ValuesTab/ValuesTab.tsx
Closes #135 
Check with all different column types, and different formats. Both the summary stats and the unique values tab.
None.
> mitosheet: format summary stats and unique values tab

- mitosheet/mitosheet/step_performers/graph_steps/graph.py
- mitosheet/mitosheet/tests/steps_performers/graph_steps/test_graph.py
- mitosheet/mitosheet/tests/test_utils.py
> mitosheet: fix bug in pandas processing time, improve graphing tests

- mitosheet/src/components/toolbar/Toolbar.tsx
- mitosheet/src/components/toolbar/ToolbarButton.tsx
- mitosheet/src/plugin.tsx
Closes #130 
Test on Mac. @aarondr77 can you also test on windows?
Also make sure to test with multiple mitosheets.
We should add this to the docs somewhere. Where?
> mitosheet: make undo and redo work with shortcuts

- mitosheet/mitosheet/step_performers/column_steps/rename_column.py
An easy fix!
Test rename column logs processing time now!
Nope.
> mitosheet: fix bug in pandas processing time causing negative numbers

- docs/how-to/graphing.md
- mitosheet/src/components/taskpanes/Graph/GraphSetupTab.tsx
So we can get data on notebook versions by EOW, this PR is here. Everything works great, except I changed the name of the color breakdown to color by column for clarity (per a hallway usability test with my dad).
Yup. Test it.
See changes. We'll need to do a lot more this week.
> Dogfood 3-20

- mitosheet/mitosheet/tests/test_ts_types.py
- mitosheet/src/api.tsx
- mitosheet/src/components/footer/SheetTab.tsx
- mitosheet/src/components/taskpanes/PivotTable/PivotTableValueAggregationCard.tsx
- mitosheet/src/components/taskpanes/PivotTable/PivotTableValueSelection.tsx
- mitosheet/src/components/taskpanes/PivotTable/PivotTaskpane.tsx
- mitosheet/src/components/taskpanes/PivotTable/pivotUtils.tsx
- mitosheet/src/components/taskpanes/taskpanes.tsx
- mitosheet/src/hooks/useEffectOnUpdateEvent.tsx
- mitosheet/src/types.tsx
Closes #175 
Should be identical in behavior. Test with editing, opening edited tables, etc!
No.
> mitosheet: cleanup and modernize pivot code, thank god

- .github/workflows/lint-mitosheet-typescript.yml
- mitosheet/mitosheet/steps_manager.py
- mitosheet/pyproject.toml
There were actually two dependency issues that came up here. I fixed both of them, and hopefully they will not trouble us again. 
I tried to pin things that would break again, but I'm sure in the coming months we'll have a dependency break again. I'm getting better addressing them, so it's ok. But it's kinda wacky. 
Check out the changes.
No.
> mitosheet: fix package builders

- trymito.io/pages/plans.tsx
> trymito.io: add new styling params to website

- mitosheet/setup.py
> mitosheet: check out setup.py

- mitosheet/setup.py
> further changes

- mitoinstaller/mitoinstaller/installer_steps/initial_installer_steps.py
- mitoinstaller/mitoinstaller/user_install.py
Fixes #186 
Test locally. 
No.
> mitoinstaller: make sure you can go pro after you have installed

- mitosheet/mitosheet/code_chunks/code_chunk.py
- mitosheet/mitosheet/code_chunks/code_chunk_utils.py
- mitosheet/mitosheet/code_chunks/step_performers/column_steps/delete_column_code_chunk.py
- mitosheet/mitosheet/code_chunks/step_performers/column_steps/rename_columns_code_chunk.py
- mitosheet/mitosheet/pro/code_chunks/code_chunk_pro_utils.py
> mitosheet: move optimize to pro, add missing init

- mitosheet/src/components/endo/ColumnHeaders.tsx
See title.
Make sure reorder works.
No.
> mitosheet: dont reorder if column not moved

- docs/getting-started/installing-mito/installing-mito-inside-a-virtual-environment.md
- docs/misc/release-notes.md
- mitoinstaller/README.md
- mitosheet/README.md
- mitosheet/css/elements/Dropdown.css
- mitosheet/css/elements/DropdownItem.css
- mitosheet/src/components/elements/Dropdown.tsx
- Fixes scrollbar issues that were made more whacky by the non-overlapping scrollbar w/ text fix
- Adds release notes
- Clarifies that the command for starting a virtual environment that we provide are for command prompt, not powershell
The only thing that we might want to do is to add documnetation for the optimize code stuff / add it to the website in more than just the bullet point, but I'll wait for the spec that Jake is creating
> dogfood 4-19-22

- mitosheet/mitosheet.json
- mitosheet/setup.py
> mitosheet: add missing datafiles

- docs/misc/release-notes.md
- mitoinstaller/mitoinstaller/commands.py
- mitoinstaller/mitoinstaller/create_startup_file.py
- mitoinstaller/tests/test_installs.py
- mitosheet/css/elements/Dropdown.css
- mitosheet/css/taskpanes/ControlPanel/SortCard.css
- mitosheet/src/components/modals/SignupModal.tsx
- mitosheet/src/components/taskpanes/Import/FileBrowser.tsx
1. Removed unnecessary print in installer.
2. Focus on search input in file browser once you click on new folder
3. Fixes a massive bug in signup flow where modal was not visible, and buttons were all wacky.
> Dogfood: 4-21

- mitosheet/README.md
- mitosheet/setup.py
- mitosheet/src/components/modals/SignupModal.tsx
fixes the signup flow for notebooks. Just go through the signup flow on notebooks and jlab once.
Nope!
> Fix signup flow

- .github/workflows/deploy-mitosheet-private.yml
- deployment/bump_version.py
> Improve deployment process for mitosheet-private

- mitosheet/mitosheet/user/utils.py
> mitosheet: turn off upgrade prompt for mitosheet-private

- .github/workflows/deploy-mitosheet-private.yml
> Turn off upgrade prompt for mitosheet-private

- mitoinstaller/mitoinstaller/create_startup_file.py
- mitosheet/css/elements/TextButton.css
- mitosheet/mitosheet/startup/startup_utils.py
1. Run notebook.
2. Render dataframe (not in Mito)
3. Notice error as button tries to get called, so I just make it so it exit outs early.
> Notebook button fix 1

- .github/workflows/test-mitosheet-mypy.yml
- deployment/bump_version.py
- deployment/deploy.py
- mitoinstaller/mitoinstaller/create_startup_file.py
- mitosheet/css/elements/TextButton.css
- mitosheet/mitosheet/startup/startup_utils.py
- mitosheet/src/components/modals/UpgradeModal.tsx
Fixes upgrade modal issue that has been deployed for the past week. Simply test that it looks correct now. 
@aarondr77 good work catching this. In the future, when you run into it, if you can investigate and try and fix it up asap I think it would be good -- just for visual bugs this big that encounter this many users (and are so clearly a regression), I think it's better to just hop on it rather than waiting a week. 
See how it looks!
Also check out the signup flow. It looks fine.
Nope!
> mitosheet: fix upgrade modal

- mitosheet/src/components/taskpanes/Graph/GraphSidebar.tsx
- mitosheet/src/jupyter/api.tsx
> Plotly log

- mitosheet/src/components/taskpanes/Graph/GraphSidebar.tsx
- mitosheet/src/jupyter/api.tsx
> Final merge

- binder/postBuild
> My binder try

- trymito.io/pages/plans.tsx
- trymito.io/styles/Plans.module.css
Per feedback.
Check preview link.
N/A.
> trymito.io: decrease max width for readability

- mitosheet/css/sitewide/text.css
- mitosheet/mitosheet/telemetry/private_params_map.py
- mitosheet/src/components/Mito.tsx
- mitosheet/src/components/elements/MultiToggleBox.tsx
- mitosheet/src/components/elements/MultiToggleItem.tsx
- mitosheet/src/components/endo/ColumnHeaderDropdown.tsx
- mitosheet/src/components/endo/selectionUtils.tsx
- mitosheet/src/components/taskpanes/ControlPanel/ControlPanelTaskpane.tsx
- mitosheet/src/components/taskpanes/ControlPanel/SummaryStatsTab/ColumnSummaryStatistics.tsx
- mitosheet/src/components/taskpanes/ControlPanel/ValuesTab/ValuesTab.tsx
- mitosheet/src/components/taskpanes/FillNa/FillNaTaskpane.tsx
- mitosheet/src/components/taskpanes/FillNa/OpenFillNaN.tsx
- mitosheet/src/components/taskpanes/taskpanes.tsx
- mitosheet/src/components/toolbar/ToolbarColumnsDropdown.tsx
- mitosheet/src/components/toolbar/ToolbarDataframesDropdown.tsx
- mitosheet/src/utils/actions.tsx
Makes changes here: https://www.notion.so/trymito/Jake-DR-Fill-NaN-79e1ddaee6e44a5eb050ed2ce2c38eb3
Check the changes listed above!
N/A.
> Fill nan usability

- mitosheet/css/elements/MultiToggleBox.css
- mitosheet/src/components/elements/Dropdown.tsx
- mitosheet/src/components/elements/MultiToggleBox.tsx
- mitosheet/src/components/taskpanes/FillNa/FillNaTaskpane.tsx
Just scrolls into view, and better text.
Use some multi toggle boxes.
No.
> mitosheet: fill nan improvements two

- mitosheet/setup.py
Check and make sure this is in fact the correct version that we were sent over!
pip install this version, and test the graphing (one graph type doesn't work, which is fine, see recent issue)
Nope.
> mitosheet: change required plotly version down

- docs/misc/release-notes.md
> Change Plotly version

- mitosheet/src/components/endo/ColumnHeaderDropdown.tsx
Found while testing the split columns PR.
On windows, a large dataset, this shouldn't be laggy.
No.
> mitosheet: fix windows performance bug due to log

- mitosheet/src/components/Mito.tsx
- mitosheet/src/components/endo/EmptyGridMessages.tsx
- mitosheet/src/components/endo/EndoGrid.tsx
- mitosheet/src/components/modals/SignupModal.tsx
- mitosheet/src/components/taskpanes/Import/FileBrowser.tsx
- mitosheet/src/components/taskpanes/Import/FileBrowserElement.tsx
- mitosheet/src/components/taskpanes/Import/importUtils.tsx
Makes changes here: https://www.notion.so/trymito/Import-Redux-0010ce5218c543a5b95f08fcc4bd45d5
Test these changes! 
N/A.
> Import improvements

- mitosheet/src/components/elements/Dropdown.tsx
- mitosheet/src/components/footer/DataSheetTabActions.tsx
- mitosheet/src/components/footer/GraphSheetTabActions.tsx
Fixes https://github.com/mito-ds/monorepo/issues/331
> mitosheet: fix the sheet tab action from closing the rename

- mitosheet/src/components/elements/Dropdown.tsx
- mitosheet/src/components/footer/DataSheetTabActions.tsx
- mitosheet/src/components/footer/GraphSheetTabActions.tsx
> Revert "mitosheet: fix the sheet tab action from closing the rename"

- mitosheet/src/components/elements/Dropdown.tsx
- mitosheet/src/components/endo/ColumnHeaderDropdown.tsx
- mitosheet/src/components/footer/DataSheetTabActions.tsx
- mitosheet/src/components/footer/GraphSheetTabActions.tsx
> mitosheet: add supress focus on close to another place

- mitosheet/css/taskpanes/Import/FileBrowser.css
- mitosheet/css/taskpanes/Import/ImportTaskpane.css
- mitosheet/mitosheet/code_chunks/step_performers/import_steps/excel_import_code_chunk.py
- mitosheet/src/components/Mito.tsx
- mitosheet/src/components/elements/MultiToggleBox.tsx
- mitosheet/src/components/icons/BackArrowIcon.tsx
- mitosheet/src/components/taskpanes/DropDuplicates/DropDuplicates.tsx
- mitosheet/src/components/taskpanes/FillNa/FillNaTaskpane.tsx
- mitosheet/src/components/taskpanes/Import/FileBrowser.tsx
- mitosheet/src/components/taskpanes/Import/FileBrowserElement.tsx
- mitosheet/src/components/taskpanes/Import/ImportTaskpane.tsx
- mitosheet/src/components/taskpanes/Import/XLSXImport.tsx
- mitosheet/src/components/taskpanes/Import/importUtils.tsx
- mitosheet/src/components/taskpanes/SplitTextToColumns/SplitTextToColumnsTaskpane.tsx
- mitosheet/src/hooks/useSendEditOnClick.tsx
- mitosheet/src/jupyter/api.tsx
- mitosheet/src/types.tsx
- mitosheet/src/utils/copy.tsx
Fixes bugs here: https://www.notion.so/trymito/Jake-DR-Copy-and-Paste-Split-Text-to-Column-ea4dbe3e15774b8bbd9e025654719dfe
Note that this merged in PR #326 -- just wanted to call out how WIP being present effects things.
Test the changes!
N/A.
> Hallway usability test

- mitosheet/dev/macsetup.sh
- mitosheet/dev/testinstall.sh
Test the scripts! Don't merge until this is working :-) 
N/A.
> mitosheet: update scripts to work with Aarons computer

- mitosheet/mitosheet/code_chunks/delete_row_code_chunk.py
- mitosheet/mitosheet/tests/step_performers/test_delete_row.py
- mitosheet/mitosheet/utils.py
1. Makes indexes work with timedelta and datetime
2. Fixes duplicate indexes bug when optimizing
Test these things!
N/A. Need to write delete row docs before deploying!
> Delete row fixes

- mitosheet/mitosheet/api/get_unique_value_counts.py
- mitosheet/mitosheet/code_chunks/promote_row_to_header_code_chunk.py
- mitosheet/mitosheet/errors.py
- mitosheet/mitosheet/step_performers/promote_row_to_header.py
- mitosheet/mitosheet/steps_manager.py
- mitosheet/mitosheet/tests/step_performers/test_promote_row_to_header.py
- mitosheet/mitosheet/tests/test_utils.py
- mitosheet/mitosheet/utils.py
- mitosheet/src/components/endo/IndexHeaderDropdown.tsx
- mitosheet/src/components/endo/IndexHeaders.tsx
- mitosheet/src/jupyter/api.tsx
- mitosheet/src/types.tsx
- mitosheet/src/utils/actions.tsx
This PR implements this spec: https://www.notion.so/trymito/Promote-Row-to-header-6bcc410eb9154ea3a13a0d74a33d81a2
With the meta-programming code that had already been written, this took 30 minutes start to finish. Get ready for a whole new world of productivity gain on new step types!
Just test it.
Need to write docs for this, and delete row.
> Promote row to header

- mitosheet/mitosheet/code_chunks/promote_row_to_header_code_chunk.py
- mitosheet/mitosheet/errors.py
- mitosheet/mitosheet/state.py
- mitosheet/mitosheet/step_performers/promote_row_to_header.py
- mitosheet/src/components/toolbar/Toolbar.tsx
- mitosheet/src/components/toolbar/ToolbarRowsDropdown.tsx.tsx
- mitosheet/src/types.tsx
Makes these changes: https://www.notion.so/trymito/Jake-DR-Delete-Row-Promote-Row-ceaccb600f9345dd9b9dce69b5b86c77
Test these changes (make sure to test new error).
Check doc for both Promote Row to Header and Delete Rows. Make any changes, then I'll finish dogfooding and we'll get this merged!
> Dogfood 6 6

- mitosheet/src/components/elements/Dropdown.tsx
See description. Closes #352 
Use fullscreen mode. Test on windows too!
N/A.
> mitosheet: update dropdown positioning will fullscreen

- mitoinstaller/mitoinstaller/__main__.py
- mitoinstaller/mitoinstaller/installer_steps/initial_installer_steps.py
- mitoinstaller/tests/conftest.py
- mitosheet/src/components/modals/SignupModal.tsx
Closes #358 
Test the new print is correctly spelled.
N/A.
> mitoinstaller: fix misspelled word through the codebase

- mitosheet/mitosheet/parser.py
- mitosheet/mitosheet/step_performers/column_steps/set_column_formula.py
- mitosheet/mitosheet/tests/step_performers/column_steps/test_set_column_formula.py
Fixes https://github.com/mito-ds/monorepo/issues/347
Write some formulas w/ em.
No.
> mitosheet: add timedelta and datetime support to formulas

- mitosheet/mitosheet/parser.py
- mitosheet/mitosheet/tests/test_parse.py
See the test case - this fixes bug from a user MJ we received in email recently.
See test case, test their dataset.
N/A.
> mitosheet: fix bug in formulas when searching for strings

- mitosheet/src/components/taskpanes/Melt/MeltTaskpane.tsx
- mitosheet/src/components/toolbar/ToolbarDataframesDropdown.tsx
Per Jake's hallway usability test: https://www.notion.so/trymito/Jake-Melt-Test-79f62b0115264d568339e75587cd218d
Check out the new minor changes.
Check out new docs for:
1. Melt
2. Merge
I merged them in, so feel free to edit them and then LGTM.
> Release 6/21

- mitosheet/mitosheet/api/get_params.py
- mitosheet/mitosheet/saved_analyses/save_utils.py
- mitosheet/mitosheet/steps_manager.py
- mitosheet/mitosheet/tests/fuzz.py
- mitosheet/mitosheet/tests/saved_analyses/test_save_utils.py
- mitosheet/mitosheet/tests/step_performers/column_steps/test_reorder_column.py
- mitosheet/mitosheet/tests/step_performers/graph_steps/test_graph.py
- mitosheet/mitosheet/tests/step_performers/graph_steps/test_graph_delete.py
- mitosheet/mitosheet/tests/step_performers/graph_steps/test_graph_duplicate.py
- mitosheet/mitosheet/tests/step_performers/graph_steps/test_graph_rename.py
- mitosheet/mitosheet/tests/step_performers/import_steps/test_simple_import_step.py
- mitosheet/mitosheet/tests/step_performers/test_filter.py
- mitosheet/mitosheet/tests/step_performers/test_pivot.py
- mitosheet/mitosheet/tests/test_steps_manager.py
- mitosheet/mitosheet/tests/test_utils.py
- mitosheet/mitosheet/tests/updates/test_checkout_step_by_idx.py
- mitosheet/mitosheet/tests/updates/test_clear.py
- mitosheet/mitosheet/tests/updates/test_undo.py
- mitosheet/mitosheet/transpiler/transpile.py
- mitosheet/mitosheet/updates/checkout_step_by_idx.py
Just a better name.
Tests pass.
N/A
> mitosheet: name steps better

- mitosheet/src/components/elements/ColorInput.tsx
- mitosheet/src/components/elements/DataframeSelect.tsx
- mitosheet/src/components/taskpanes/Download/CSVDownloadConfigSection.tsx
- mitosheet/src/components/taskpanes/Download/DownloadTaskpane.tsx
- mitosheet/src/components/taskpanes/DropDuplicates/DropDuplicates.tsx
- mitosheet/src/components/taskpanes/FillNa/FillNaTaskpane.tsx
- mitosheet/src/components/taskpanes/Graph/GraphSetupTab.tsx
- mitosheet/src/components/taskpanes/Melt/MeltTaskpane.tsx
- mitosheet/src/components/taskpanes/PivotTable/PivotTaskpane.tsx
- mitosheet/src/components/taskpanes/PivotTable/pivotUtils.tsx
- mitosheet/src/components/taskpanes/SplitTextToColumns/SplitTextToColumnsTaskpane.tsx
Adds a nice, shiny, new component that slaps. Look at the lines it cuts (while also being so easy to read!).
Test the taskpanes.
N/A.
> mitosheet: add a dataframe select component

- mitosheet/src/components/taskpanes/Import/CSVImport.tsx
> mitosheet: add tab support to csv config

- mitosheet/mitosheet/api/get_csv_files_metadata.py
- mitosheet/mitosheet/api/get_dataframe_as_excel.py
- mitosheet/src/components/elements/Input.tsx
- mitosheet/src/components/footer/SheetTab.tsx
Fixes:
- https://www.notion.so/trymito/7-19-22-3d5111b24a254936a72c22db2607deb8
- https://github.com/mito-ds/monorepo/issues/366
Changes.
No.
> Error reduction 7 15

- mitosheet/css/sitewide/margins.css
- mitosheet/mitosheet/tests/test_utils.py
- mitosheet/mitosheet/tests/updates/test_checklist_update.py
- mitosheet/mitosheet/updates/checklist_update.py
- mitosheet/mitosheet/user/upgrade.py
- mitosheet/src/components/Mito.tsx
- mitosheet/src/components/checklists/Checklist.tsx
- mitosheet/src/components/elements/BottomLeftPopup.tsx
- mitosheet/src/components/toolbar/OpenChecklistButton.tsx
- mitosheet/src/components/toolbar/Toolbar.tsx
- mitosheet/src/jupyter/api.tsx
1. Made button to reopen onboarding checklist. This only exists during your first usage... that good?
2. For the bulk of the checklist, made it so it opens the feature. This is sweet. It doesn't do the same for the later links, but I think it's fine. Also, what do for those that aren't active (b/c no imported data?) -- I think it could be fine to just leave and usability test.
3. Make the installer not upgrade the user.json if it shouldn't!
Test all these things. You'll have to clear your user.json to pretent to be a first time user.
No.
> 7 26 usability

- mitosheet/css/sitewide/margins.css
- mitosheet/css/toolbar.css
- mitosheet/mitosheet/tests/test_utils.py
- mitosheet/mitosheet/tests/updates/test_checklist_update.py
- mitosheet/mitosheet/updates/checklist_update.py
- mitosheet/mitosheet/user/upgrade.py
- mitosheet/src/components/Mito.tsx
- mitosheet/src/components/checklists/Checklist.tsx
- mitosheet/src/components/elements/BottomLeftPopup.tsx
- mitosheet/src/components/endo/EmptyGridMessages.tsx
- mitosheet/src/components/endo/EndoGrid.tsx
- mitosheet/src/components/modals/SignupModal.tsx
- mitosheet/src/components/toolbar/OpenChecklistButton.tsx
- mitosheet/src/components/toolbar/Toolbar.tsx
- mitosheet/src/components/toolbar/ToolbarButton.tsx
- mitosheet/src/jupyter/api.tsx
- mitosheet/src/utils/actions.tsx
Implements: https://www.notion.so/trymito/Import-Improvements-bb65727e1ba1479ea91ed176077fe589
Check signup, check button messages.
No.
> mitosheet: change buttons to disabled when sheet is empty

- mitosheet/mitosheet/mito_widget.py
Fixes https://github.com/mito-ds/monorepo/issues/417
Check your previous test case.
No.
> mitosheet: fix user json not existing bug

- mitosheet/src/utils/code.tsx
```
import mitosheet as ms
ms.sheet()
```
Now works!
Test this.
No.
> mitosheet: fix bug where import mitosheet as ms didn't work

- mitosheet/src/components/taskpanes/Graph/GraphSetupTab.tsx
- mitosheet/src/components/taskpanes/Graph/GraphStyleTab.tsx
- mitosheet/src/components/taskpanes/Graph/graphUtils.tsx
- mitosheet/src/types.tsx
Adds some fancy types and helpers to dramatically reduce the amount of filler graph code. Nice!
Test the params.
No.
> mitosheet: graph helper cleanup

- .github/workflows/deploy-mitosheet-private.yml
- mitosheet/mitosheet/telemetry/telemetry_utils.py
- mitosheet/mitosheet/user/utils.py
- mitosheet/setup.py
- mitosheet/src/components/checklists/Checklist.tsx
- mitosheet/switch.py
> Private main

- mitosheet/mitosheet/user/upgrade.py
See description of issue in chat. 
We need to fix the user.json ASAP. This is what I'll be doing for part of my time off... as it's a huge problem now. 
Merge if it makes sense, and then I'll deploy and test (you prolly should as well)....
No.
> Private spreadsheet fix

- trymito.io/pages/index.tsx
- trymito.io/pages/plans.tsx
> mitosheet: make website changes

- mitosheet/setup.py
> mitosheet: bump to 2.0

- mitosheet/src/jupyter/notebook/pluginUtils.tsx
> mitosheet: insert cell after

- mitosheet/src/jupyter/notebook/pluginUtils.tsx
> Fix pandas

- mitoinstaller/mitoinstaller/print_utils.py
- mitosheet/mitosheet/errors.py
- mitosheet/mitosheet/preprocessing/preprocess_check_args_type.py
- mitosheet/mitosheet/tests/step_performers/test_merge.py
- mitosheet/mitosheet/tests/test_mito_widget.py
- mitosheet/package-lock.json
- mitosheet/src/components/taskpanes/Graph/GraphSetupTab.tsx
Investigation here: https://www.notion.so/trymito/9-20-22-99326e7707f7431281cf925f848fc4e3
Closes https://github.com/mito-ds/monorepo/issues/466
Closes https://github.com/mito-ds/monorepo/issues/416
Need more info on: https://github.com/mito-ds/monorepo/issues/450 (@aarondr77 do you remember what you meant?)
This is one too hard: https://github.com/mito-ds/monorepo/pull/425
Test all these changes.
N/A.
> Error reduction 9/20

- mitoinstaller/mitoinstaller/installer_steps/final_installer_steps.py
- mitoinstaller/mitoinstaller/installer_steps/installer_step_utils.py
- mitoinstaller/mitoinstaller/installer_steps/mitosheet_installer_steps.py
- mitoinstaller/mitoinstaller/print_utils.py
- mitosheet/mitosheet/errors.py
- mitosheet/mitosheet/preprocessing/preprocess_check_args_type.py
- mitosheet/mitosheet/tests/step_performers/test_merge.py
- mitosheet/mitosheet/tests/test_mito_widget.py
- mitosheet/package-lock.json
- mitosheet/src/components/taskpanes/Graph/GraphSetupTab.tsx
See here: https://www.notion.so/trymito/9-21-22-4cc50797022742c499d0c809bdfaad34
Check out the dashboard. The new, prettier installer is approx 0% better at successful installs, but it adds lots of complexity and makes it hard to prompt the user to do --user installs (which is the most common install error). 
Test installer. Testing user install is tricky - but do your best to fudge the error (in the install_pip_packages function).
N/A.
> Installer fix 9/21

- mitosheet/mitosheet/code_chunks/postprocessing/set_dataframe_format_code_chunk.py
- mitosheet/mitosheet/utils.py
- mitosheet/src/components/taskpanes/ConditionalFormatting/ConditionalFormattingCard.tsx
- mitosheet/src/components/taskpanes/ControlPanel/FilterAndSortTab/filter/filterConditions.tsx
- Adds better error messages
- Makes new filter conditions more clear (this was the best I could think of, feel free to change if you have something better).
- Makes error handling a bit more defensive to try and avoid crashes
Test new conditional format error messages!
Before release, I have to write these docs!
> Conditional format usability fix

- mitosheet/src/components/taskpanes/ControlPanel/FilterAndSortTab/DtypeCard.tsx
> mitosheet: remove subtext from dropdown to make selecting easier

- mitosheet/src/components/taskpanes/Graph/GraphExportTab.tsx
> mitosheet: add more support for creating html file

- .github/ISSUE_TEMPLATE/installation-issue---post-in--install-help-on-discord.md
- CONTRIBUTING.md
- README.md
- mitoinstaller/mitoinstaller/commands.py
- mitoinstaller/mitoinstaller/starter_notebook.py
- mitosheet/src/components/elements/ErrorBoundary.tsx
- mitosheet/src/components/modals/ErrorModal.tsx
- mitosheet/src/components/modals/ReplayAnalysisModals.tsx
- mitosheet/src/data/documentationLinks.tsx
- mitosheet/src/utils/actions.tsx
- mitosheet/yarn.lock
- trymito.io/components/Footer/Footer.tsx
Moves most of the Discord links to Slack links. 
Make sure the Slack link works + adds you to the channels general, install-help, python-support, feature-ideas. Make sure you cannot see any private channels. 
Once this is tested, I'll update the docs too.
> Add slack 2

- trymito.io/pages/plans.tsx
> trymito: correct website language

- mitosheet/mitosheet/saved_analyses/step_upgraders/set_dataframe_format.py
- mitosheet/mitosheet/saved_analyses/upgrade.py
- mitosheet/mitosheet/step_performers/set_dataframe_format.py
- mitosheet/mitosheet/tests/saved_analyses/test_upgrade.py
- mitosheet/mitosheet/tests/test_step_format.py
- mitosheet/src/components/Mito.tsx
- mitosheet/src/components/modals/SignupModal.tsx
- trymito.io/pages/plans.tsx
Remove this from some other places. Doesn't touch the popup to avoid merge conflicts, in case we merge in #501 
Check that the tour pops up first time only!
Nope.
> Continue removing checklist

- mitosheet/src/components/elements/GetSupportButton.tsx
- mitosheet/src/utils/actions.tsx
Just adds subject line to emails
> mitosheet: add subject line

- mitosheet/mitosheet/saved_analyses/schema_utils.py
- mitosheet/mitosheet/step.py
- mitosheet/mitosheet/tests/saved_analyses/test_upgrade.py
- mitosheet/mitosheet/tests/step_performers/column_steps/test_rename_column.py
Makes some small developer experience improvements:
1. Changes the print for steps so that it displays helpful information instead of the object address
2. Makes the variable names of `is_prev_version` function easier to understand. 
**Note branches off nan-column-headers to make it easy to see differences.**
> Small dx improvements

- mitosheet/mitosheet/transpiler/transpile_utils.py
- mitosheet/src/components/elements/LabelAndTooltip.tsx
- mitosheet/src/components/import/CSVImportConfigScreen.tsx
- mitosheet/src/components/import/DataframeImportScreen.tsx
- mitosheet/src/components/import/XLSXImportConfigScreen.tsx
- mitosheet/src/components/taskpanes/Concat/ConcatTaskpane.tsx
- mitosheet/src/components/taskpanes/Graph/GraphSetupTab.tsx
- mitosheet/src/components/taskpanes/Melt/MeltTaskpane.tsx
- mitosheet/src/components/taskpanes/PivotTable/PivotTableFilterSection.tsx
- mitosheet/src/components/taskpanes/PivotTable/PivotTableKeySelection.tsx
- mitosheet/src/components/taskpanes/PivotTable/PivotTableValueSelection.tsx
- mitosheet/src/components/taskpanes/PivotTable/PivotTaskpane.tsx
- mitosheet/src/components/taskpanes/UpdateImports/UpdateDataframeImportTaskpane.tsx
- mitosheet/src/pro/taskpanes/SetDataframeFormat/SetDataframeFormatTaskpane.tsx
- Fix pd.np deprecation warning
- Add LabelAndTooltip component, so things look cleanup everywhere we use tooltips.
See changes.
I need to update pivot docs.
> Dogwood 11/15

- mitosheet/mitosheet/code_chunks/step_performers/column_steps/delete_column_code_chunk.py
- mitosheet/mitosheet/code_chunks/step_performers/pivot_code_chunk.py
- mitosheet/mitosheet/tests/step_performers/column_steps/test_delete_column.py
- mitosheet/mitosheet/tests/step_performers/test_pivot.py
- Optimizes pivot table code chunks, if you edit them immediately
- Optimizes our reorder if you delete column
- Optimizes our rename if you delete these columns
The above. Add a test or two if you can think of any good ones!
No.
> Optimize code chunks more

- .github/workflows/cla.yml
- .github/workflows/deploy-mitosheet-mitoinstaller.yml
- .github/workflows/lint-mitosheet-typescript.yml
- .github/workflows/test-mitoinstaller.yml
- .github/workflows/test-mitosheet-frontend.yml
- .github/workflows/test-mitosheet-mypy.yml
- .github/workflows/test-mitosheet-python.yml
Fixes up our GitHub actions from temporarily failing due to Ubuntu issues. See https://github.com/actions/setup-python/issues/162
> .github: fix ubuntu bug

- mitosheet/esbuild.js
> mitosheet: dont minimize

- mitosheet/mitosheet/mito_backend.py
- mitosheet/mitosheet/tests/test_mito_frontend.py
Fixes bug found in call w/ MB this morn.
See new tests added. They might get skipped on server, but run locally, so ok for now.
N/A.
> mitosheet: make sure to escape slashes

- mitosheet/mitosheet/mito_frontend.js
- mitosheet/src/jupyter/notebook/extension.tsx
- mitosheet/src/plugin.tsx
Do it properly this time!
Open a bunch of notebooks, click a bunch of buttons.
Nope!
> mitosheet: fix button so it always displays

- mitosheet/mitosheet/mito_frontend.js
- mitosheet/src/components/elements/ErrorBoundary.tsx
- mitosheet/src/components/elements/GetSupportButton.tsx
- mitosheet/src/utils/actions.tsx
> mitosheet: move back to Discord

- mitosheet/css/sitewide/cursor.css
- mitosheet/css/toolbar.css
- mitosheet/mitosheet/mito_frontend.css
- mitosheet/mitosheet/mito_frontend.js
- mitosheet/src/components/elements/GetSupportButton.tsx
- mitosheet/src/components/footer/Footer.tsx
- mitosheet/src/components/footer/SheetTab.tsx
- mitosheet/src/components/toolbar/PlanButton.tsx
- Fixes the spacing of the toolbar menu items
- Uses the correct cursor type in more places
> mitosheet: fix spacing of toolbar

- mitoinstaller/mitoinstaller/commands.py
- mitoinstaller/mitoinstaller/starter_notebook.py
Moves the installer from slack to discord
> mitoinstaller: move to discord link

- mitosheet/mitosheet/code_chunks/code_chunk.py
- mitosheet/mitosheet/code_chunks/step_performers/pivot_code_chunk.py
- mitosheet/mitosheet/tests/step_performers/test_pivot.py
We optimize out edits to pivot tables in code, if the pivot table is later overwritten.
Do the edits. Maybe add a test.
No.
> mitosheet: better optimization when editing pivot tables

- trymito.io/components/Footer/Footer.tsx
- trymito.io/components/Header/Header.tsx
> trymito.io: add links to our blog

- mitosheet/mitosheet/code_chunks/step_performers/import_steps/excel_range_import_code_chunk.py
- mitosheet/mitosheet/step_performers/import_steps/excel_range_import.py
- mitosheet/mitosheet/tests/test_utils.py
> mitosheet: fix code chunk merge conflicts

- mitosheet/package.json
- mitosheet/switch.py
> mitosheet: add documentation build to switch

- trymito.io/components/CTAButtons/CTAButtons.module.css
- trymito.io/components/CTAButtons/CTAButtons.tsx
- trymito.io/pages/index.tsx
- trymito.io/pages/plans.tsx
- trymito.io/pages/security.tsx
- trymito.io/pages/teams.tsx
- trymito.io/styles/Plans.module.css
- trymito.io/styles/Title.module.css
Written with our user and buyer profiles in mind!
Read it all.
No.
> trymito.io: language pass

- mitosheet/mitosheet/step_performers/dataframe_steps/dataframe_duplicate.py
- mitosheet/mitosheet/tests/step_performers/test_set_dataframe_format.py
Fixes  https://github.com/mito-ds/monorepo/issues/620
Try the issue again.
No.
> mitosheet: fix bug on set format, rename, duplicate

- mitosheet/src/components/elements/MultiToggleBox.tsx
- mitosheet/src/components/elements/MultiToggleColumns.tsx
- mitosheet/src/components/elements/MultiToggleDataframes.tsx
- mitosheet/src/components/import/XLSXImportConfigScreen.tsx
- mitosheet/src/components/taskpanes/Download/ExcelDownloadConfigSection.tsx
- mitosheet/src/components/taskpanes/DropDuplicates/DropDuplicates.tsx
- mitosheet/src/components/taskpanes/ExportToFile/ExportToFileTaskpane.tsx
- mitosheet/src/components/taskpanes/FillNa/FillNaTaskpane.tsx
- mitosheet/src/components/taskpanes/Melt/MeltTaskpane.tsx
- mitosheet/src/components/taskpanes/Merge/MergeTaskpane.tsx
- mitosheet/src/components/taskpanes/SnowflakeImport/SnowflakeImportTaskpane.tsx
- mitosheet/src/pro/taskpanes/ConditionalFormatting/ConditionalFormattingCard.tsx
1. Closes https://github.com/mito-ds/monorepo/issues/598
2. Introduces a MultiToggleColumns component - which is _sooo_ much cleaner!
Also opened this issue: https://github.com/mito-ds/monorepo/issues/625 (which is unrelated to this PR)
Test all the toggles that are changes. I did!
No.
> mitosheet: standardize column toggle all

- mitosheet/mitosheet/mito_frontend.js
- mitosheet/mitosheet/parser.py
- mitosheet/mitosheet/tests/step_performers/column_steps/test_set_column_formula.py
Set a specific cell index to a constant. 
Try doing it. Note that we don't do type casting, which is a bit of a regression, but I think it's okey...
N/a
> mitosheet: allow users to set constants in formulas

- .github/workflows/test-mitosheet-python.yml
- mitosheet/mitosheet/code_chunks/step_performers/filter_code_chunk.py
- mitosheet/mitosheet/errors.py
- mitosheet/mitosheet/step_performers/filter.py
- mitosheet/mitosheet/tests/step_performers/test_filter.py
- mitosheet/mitosheet/tests/test_utils.py
- mitosheet/mitosheet/types.py
Per your work with users @aarondr77, this refactors filters so if multiple are applied to the same sheet, they are combined into one. 
Note that to do this, I refactored our pivot code to 1) use types (nice!), and 2) support infinitely nested pivot groups. This is a nice and sensible cleanup!
Do some filtering.
No.
> Optim double filter

- mitosheet/mitosheet/step_performers/reset_index.py
> mitosheet: fix reset index on different sheet

- trymito.io/pages/teams.tsx
Fixes bug on website. 
**Note that this is merged directly into main**
> mitosheet: fix ascii issue

- mitosheet/mitosheet/errors.py
- mitosheet/mitosheet/mito_frontend.js
- mitosheet/mitosheet/step_performers/pivot.py
- mitosheet/src/components/taskpanes/PivotTable/PivotTableFilterSection.tsx
- mitosheet/src/components/taskpanes/PivotTable/PivotTaskpane.tsx
Fixes: https://github.com/mito-ds/monorepo/issues/523
Add some raise Exceptions and see errors get reported in the right place. Would be nice if we had stronger types on errors, I think!
No.
> mitosheet: add in place pivot errors

- mitosheet-helpers/mitosheet_helper_enterprise/LICENSE
- mitosheet-helpers/mitosheet_helper_enterprise/README.md
- mitosheet-helpers/mitosheet_helper_enterprise/pyproject.toml
- mitosheet-helpers/mitosheet_helper_enterprise/setup.cfg
- mitosheet-helpers/mitosheet_helper_pro/LICENSE
- mitosheet/mitosheet/enterprise/mito_config.py
- mitosheet/mitosheet/mito_backend.py
- mitosheet/mitosheet/mito_frontend.js
- mitosheet/mitosheet/tests/test_mito_config.py
- mitosheet/mitosheet/tests/user/conftest.py
- mitosheet/mitosheet/user/schemas.py
- mitosheet/mitosheet/user/upgrade.py
- mitosheet/mitosheet/user/utils.py
- mitosheet/src/components/Mito.tsx
- mitosheet/src/components/elements/MitoProUpgradePrompt.tsx
- mitosheet/src/components/import/FileBrowser/FileBrowserBody.tsx
- mitosheet/src/components/taskpanes/DefaultTaskpane/DefaultTaskpaneBody.tsx
- mitosheet/src/components/taskpanes/SnowflakeImport/SnowflakeImportTaskpane.tsx
- mitosheet/src/components/taskpanes/UpgradeToPro/UpgradeToProTaskpane.tsx
- mitosheet/src/components/taskpanes/taskpanes.tsx
- mitosheet/src/components/toolbar/PlanButton.tsx
- mitosheet/src/jupyter/api.tsx
- mitosheet/src/types.tsx
- mitosheet/src/utils/actions.tsx
Implements: https://www.notion.so/trymito/Mito-Enterprise-User-Profile-edab23285c214322ad54d59d01a350fb?pvs=4
Try:
1. Enterprise and not pro through the user profile
2. Enterprise and pro through the user profile
3. Pro and not enterprise through user profile
4. Turning on Snowflake with Pro only through config
5. Turning on Enterprise with helper package.
Probably fine for now, we can document enterprise config.
> mitosheet: add isEnterprise designation

- mitosheet/mitosheet/ai/prompt.py
- mitosheet/mitosheet/tests/ai/test_prompt.py
- mitosheet/mitosheet/transpiler/transpile_utils.py
- mitosheet/mitosheet/types.py
Adds a `get_prompt` function that always is within the length bounds, intelligently. We will, of course, continue to improve this over time.
Add some other tests.
No.
> mitosheet: add prompt that never is too long

- .github/workflows/deploy-mitosheet-mitoinstaller.yml
- .github/workflows/deploy-mitosheet-private.yml
- .github/workflows/lint-mitosheet-typescript.yml
- .github/workflows/test-mitosheet-frontend.yml
- .github/workflows/test-mitosheet-mypy.yml
- .github/workflows/test-mitosheet-python.yml
- mitosheet/README.md
- mitosheet/mitosheet/ai/recon.py
- mitosheet/mitosheet/code_chunks/ai_transformation_code_chunk.py
- mitosheet/mitosheet/mito_frontend.js
- mitosheet/src/components/LoadingIndicator.tsx
> mitosheet: fix up readme

- mitosheet/mitosheet/enterprise/mito_config.py
- mitosheet/mitosheet/mito_frontend.js
- mitosheet/mitosheet/tests/test_mito_config.py
- mitosheet/src/components/toolbar/Toolbar.tsx
- mitosheet/src/components/toolbar/ToolbarCodeDropdown.tsx
- mitosheet/src/components/toolbar/ToolbarDataframesDropdown.tsx
- mitosheet/src/components/toolbar/utils.tsx
- mitosheet/src/types.tsx
- mitosheet/src/utils/actions.tsx
It leaves the in the dropdown, which is a nice compromise.
Set the variables.
We can define them.
> Add variables for turning off display of SQL and AI Transform in toolbar.

- mitosheet/mitosheet/enterprise/mito_config.py
- mitosheet/mitosheet/mito_frontend.js
- mitosheet/src/components/toolbar/ToolbarHelpDropdown.tsx
- mitosheet/src/utils/actions.tsx
> mitosheet: disable better

- mitosheet/mitosheet/mito_frontend.js
- mitosheet/src/components/taskpanes/CodeSnippets/CodeSnippetsTaskpane.tsx
Add code snippet name to mailto link 
Generate the email. 
No.
> mitosheet: add code snippet name to mailto link

- mitosheet/mitosheet/errors.py
- mitosheet/mitosheet/public/v3/errors.py
- mitosheet/mitosheet/public/v3/sheet_functions/bool_functions.py
- mitosheet/mitosheet/public/v3/sheet_functions/number_functions.py
- mitosheet/mitosheet/public/v3/sheet_functions/string_functions.py
- mitosheet/mitosheet/public/v3/sheet_functions/utils.py
- mitosheet/mitosheet/public/v3/types/decorators.py
- mitosheet/mitosheet/public/v3/types/int.py
- mitosheet/mitosheet/public/v3/types/sheet_function_types.py
- mitosheet/mitosheet/public/v3/types/str.py
- mitosheet/mitosheet/public/v3/types/utils.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/number_functions/test_max.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/string_functions/test_concat.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/string_functions/test_left.py
This PR adds a LEFT function, with some really nice error handling infrastructure that does dynamic type checking using the specified types. 
This is kinda epic.
See tests.
No.
> mitosheet: add LEFT function, error handling

- mitosheet/mitosheet/api/get_available_snowflake_options_and_defaults.py
- mitosheet/mitosheet/public/v3/errors.py
- mitosheet/mitosheet/public/v3/sheet_functions/string_functions.py
- mitosheet/mitosheet/public/v3/types/sheet_function_types.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/string_functions/test_clean.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/string_functions/test_find.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/string_functions/test_left.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/string_functions/test_len.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/string_functions/test_lower.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/string_functions/test_mid.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/string_functions/test_proper.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/string_functions/test_right.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/string_functions/test_substitute.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/string_functions/test_text.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/string_functions/test_trim.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/string_functions/test_upper.py
Adds v3 of string functions. 
I tried to test every combo, but I am sure I forgot some. Maybe try and add 2 tests per?
N/a.
> V3 string functions

- mitosheet/mitosheet/api/get_available_snowflake_options_and_defaults.py
- mitosheet/mitosheet/mito_frontend.js
- mitosheet/mitosheet/saved_analyses/step_upgraders/snowflake_import.py
- mitosheet/mitosheet/saved_analyses/upgrade.py
- mitosheet/mitosheet/step_performers/import_steps/snowflake_import.py
- mitosheet/mitosheet/tests/api/test_get_available_snowflake_options_and_defaults.py
- mitosheet/mitosheet/tests/saved_analyses/test_upgrade.py
- mitosheet/mitosheet/tests/step_performers/import_steps/test_snowflake_import.py
- mitosheet/mitosheet/types.py
- mitosheet/src/components/taskpanes/SnowflakeImport/SnowflakeImportTaskpane.tsx
- mitosheet/src/components/taskpanes/UpdateImports/UpdateImportCard.tsx
Supports querying views from the snowflake import taskpane. 
See tests + try importing from the new view "SIMPLE_PYTEST_TABLE_VIEW"
Update docs to say we support views.
> mitosheet: support views in snowflake

- .github/workflows/test-mitosheet-python.yml
- mitosheet/mitosheet/parser.py
- mitosheet/mitosheet/public/v1/sheet_functions/control_functions.py
- mitosheet/mitosheet/public/v1/sheet_functions/date_functions.py
- mitosheet/mitosheet/public/v3/sheet_functions/date_functions.py
- mitosheet/mitosheet/tests/decorators.py
- mitosheet/mitosheet/tests/public/v1/sheet_functions/date_functions/test_week.py
- mitosheet/mitosheet/tests/public/v1/sheet_functions/misc_functions/test_type.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/date_functions/test_day.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/date_functions/test_hour.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/date_functions/test_minute.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/date_functions/test_month.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/date_functions/test_quarter.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/date_functions/test_second.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/date_functions/test_week.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/date_functions/test_weekday.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/date_functions/test_year.py
- mitosheet/mitosheet/tests/step_performers/column_steps/test_rename_column.py
- mitosheet/mitosheet/tests/step_performers/import_steps/test_excel_range_import.py
- mitosheet/mitosheet/tests/step_performers/test_fill_na.py
- mitosheet/mitosheet/tests/step_performers/test_one_hot_encoding.py
- mitosheet/mitosheet/tests/step_performers/test_pivot.py
- mitosheet/mitosheet/tests/test_format.py
- mitosheet/mitosheet/tests/test_parse.py
Adds support for pandas 2.0.
`pip install "pandas==2.0.0"`. We can't add to GH action yet, sadly - it's not supported. Coming as soon as it does.
Also use the tool.
Nope.
> Pandas 2.0

- tests/README.md
- tests/ui_tests/jupyterlab.mitosheet.spec.ts
- tests/ui_tests/mitosheet.spec.ts
- tests/ui_tests/utils.ts
Adds a few frontend tests. Some of them are hard to add, but some of them work pretty well. We'll see how robust these are for a week or so before adding more. 
Let them run!
No.
> tests: add more front-end tests

- mitosheet/mitosheet/public/v3/types/datetime.py
- mitosheet/mitosheet/public/v3/types/utils.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/date_functions/test_month.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/date_functions/test_quarter.py
> Speed date parsing

- trymito.io/pages/plans.tsx
> mitosheet: add ai to website

- mitosheet/mitosheet/code_chunks/step_performers/import_steps/excel_range_import_code_chunk.py
- mitosheet/mitosheet/mito_frontend.js
- mitosheet/mitosheet/public/v1/__init__.py
- mitosheet/mitosheet/public/v2/__init__.py
- mitosheet/mitosheet/public/v2/excel_utils.py
- mitosheet/mitosheet/public/v3/__init__.py
- mitosheet/mitosheet/saved_analyses/step_upgraders/excel_range_import.py
- mitosheet/mitosheet/saved_analyses/upgrade.py
- mitosheet/mitosheet/step_performers/import_steps/excel_range_import.py
- mitosheet/mitosheet/tests/saved_analyses/test_upgrade.py
- mitosheet/mitosheet/tests/step_performers/dataframe_steps/test_dataframe_rename.py
- mitosheet/mitosheet/tests/step_performers/import_steps/test_excel_range_import.py
- mitosheet/mitosheet/tests/test_step_format.py
- mitosheet/mitosheet/tests/test_utils.py
- mitosheet/mitosheet/tests/updates/test_clear.py
- mitosheet/src/components/import/CSVImportConfigScreen.tsx
- mitosheet/src/components/taskpanes/ExcelRangeImport/ExcelRangeImportTaskpane.tsx
Configure a CSV, and you'll be able to import.
Do it do it.
Not necessary right now.
> Preprocess csv as excel

- mitosheet/mitosheet/mito_frontend.js
- mitosheet/src/components/endo/celleditor/CellEditor.tsx
Just makes the text area not expandable. Test on different browsers. I think it's an ok solution for now!
On different browsers.
No.
> Fix formula bar 2

- mitosheet/mitosheet/mito_frontend.js
- mitosheet/mitosheet/step_performers/import_steps/excel_import.py
- mitosheet/mitosheet/tests/step_performers/import_steps/test_excel_import.py
- mitosheet/src/components/import/FileBrowser/FileBrowser.tsx
- mitosheet/src/components/import/FileBrowser/FileBrowserBody.tsx
- mitosheet/src/components/import/FileBrowser/FileBrowserElement.tsx
- mitosheet/src/components/taskpanes/ExcelRangeImport/ExcelRangeImportTaskpane.tsx
- mitosheet/src/components/taskpanes/FileImport/importUtils.tsx
Enables importing .xlsm files. 
See test + import the new .xlsm file in our testing files. 
Just say we support this
> mitosheet: enable xlsm import

- mitosheet/mitosheet/code_chunks/step_performers/import_steps/excel_range_import_code_chunk.py
- mitosheet/mitosheet/mito_frontend.js
- mitosheet/mitosheet/public/v2/excel_utils.py
- mitosheet/mitosheet/tests/step_performers/import_steps/test_excel_range_import.py
- mitosheet/src/components/taskpanes/ExcelRangeImport/ExcelRangeDynamicImportSection.tsx
Adds new row end condition. Check out how easy it was. I add the condition on the frontend, on the backend, and then I specify how to find it. Took < 20 minutes.
Add a test!
No.
> mitosheet: add row entirely empty end condition

- mitosheet/setup.py
> mitosheet: cleanup setup.py

- mitosheet/src/components/toolbar/Toolbar.tsx
- mitosheet/src/utils/actions.tsx
Update language 
See language 
Yes.
> Export language

- trymito.io/components/Footer/Footer.tsx
Add new job page. 
Click it
No.
> trymito.io: add footer job description

- trymito.io/pages/plans.tsx
Updates some language on the pricing page
> tryito: plans page

- mitosheet/mitosheet/api/get_ai_completion.py
Merge https://github.com/mito-ds/monorepo-old/pull/877 and then test this.
> mitosheet: add user input to mito ai server

- mitosheet/src/components/taskpanes/AITransformation/AITransformationTaskpane.tsx
Stops that double display bug.
Check there's no double messages!
No.
> mitosheet: stop double message display in ai transformation

- trymito.io/components/CTAButtons/CTAButtons.module.css
- trymito.io/components/CTAButtons/CTAButtons.tsx
- trymito.io/components/CTACards/ContactCTACard.tsx
- trymito.io/components/CTACards/DownloadCTACard.tsx
- trymito.io/pages/index.tsx
- trymito.io/pages/plans.tsx
- trymito.io/pages/security.tsx
Just makes the JupyterLite the default.
> trymito.io: move to jupyterlite

- trymito.io/pages/plans.tsx
Update price. Also merge: https://github.com/mito-ds/monorepo-old/pull/879
> trymito: change price

- trymito.io/vercel.json
> trymito.io: add vercel.json

- trymito.io/vercel.json
> Reverse proxy

- trymito.io/components/CTACards/ContactCTACard.tsx
- trymito.io/components/CTACards/DownloadCTACard.tsx
- trymito.io/pages/industries/financial-services.tsx
- trymito.io/pages/python-ai-tools.tsx
A few small fixes from the SEO teams found during their audit of our new foundational pages.
> trymito: seo foundational page fixes

- mitosheet/src/mito/components/taskpanes/Merge/MergeTaskpane.tsx
> mitosheet: fix merge typo

- mitosheet/src/mito/components/endo/celleditor/cellEditorUtils.tsx
Updates the initial suggestions for formulas from these suggestions:
To these: 
Based on user data of the most commonly used formulas.
> Update cell editor formula suggestions

- trymito.io/components/Footer/Footer.module.css
- trymito.io/components/Footer/Footer.tsx
Make the footer a bit more robust to different length items
mobile + desktop
No.
> trymito: make footer more robust

- mitosheet/mitosheet/api/get_dataframe_as_excel.py
- mitosheet/mitosheet/pro/download/formatting.py
- mitosheet/mitosheet/public/v3/__init__.py
- mitosheet/mitosheet/public/v3/formatting.py
- mitosheet/mitosheet/tests/api/get_dataframe_as_excel.py
- mitosheet/yarn.lock
Adds the ability to export the background color and the font color of the header row when exporting to excel. 
Todo:
Before and after the PR:
> Add support for exporting header color to xlsx

- mitosheet/mitosheet/public/v3/formatting.py
- mitosheet/mitosheet/tests/step_performers/test_export_to_file.py
Adds these conditionals for number fields to the exported formats for excel: 
* less than
* less than or equal
* greater than or equal
* equal
* not equal
> Add other number comparison conditional formats to export with excel

- mitosheet/css/sitewide/margins.css
- mitosheet/css/sitewide/text.css
- mitosheet/mitosheet/mito_backend.py
- mitosheet/mitosheet/streamlit/streamlit.py
- mitosheet/mitosheet/tests/user/test_utils.py
- mitosheet/mitosheet/user/__init__.py
- mitosheet/mitosheet/user/utils.py
- mitosheet/src/mito/Mito.tsx
- mitosheet/src/mito/components/modals/StreamlitSignupModal.tsx
- mitosheet/src/mito/components/modals/modals.tsx
Adds a signup flow specific to streamlit. 
Signup on streamlit.
No.
> Streamlit signup flow

- mitosheet/css/mito.css
- mitosheet/css/taskpanes/Graph/LoadingSpinner.css
- Makes the New Mitosheet button the right color 
- Makes the graph loading spinner respect the theme 
See both 
No.
> mitosheet: two more polishes

- mitosheet/css/toolbar.css
- mitosheet/mitosheet/streamlit/streamlit.py
- mitosheet/mitosheet/streamlit/v1/spreadsheet.py
- mitosheet/mitosheet/tests/step_performers/column_steps/test_change_column_dtype.py
- mitosheet/src/mito/components/endo/celleditor/cellEditorUtils.tsx
- mitosheet/src/mito/components/import/CSVImportConfigScreen.tsx
- mitosheet/src/mito/components/import/FileBrowser/FileBrowserBody.tsx
- mitosheet/src/mito/components/import/XLSXImportConfigScreen.tsx
- mitosheet/src/mito/components/taskpanes/CodeOptions/CodeOptionsTaskpane.tsx
- mitosheet/src/mito/components/taskpanes/ExcelRangeImport/ExcelRangeImportTaskpane.tsx
- mitosheet/src/mito/components/taskpanes/Merge/MergeSheetSelection.tsx
- mitosheet/src/mito/components/taskpanes/Merge/MergeTaskpane.tsx
From bugs found here: https://www.notion.so/trymito/Fixes-da95fad69e4f4703882d55ac37691ec5?pvs=4
Check these bugs.
No.
> streamlit: cleanup small taskpanes, import_folder, and more

- mitosheet/mitosheet/step_performers/import_steps/simple_import.py
- mitosheet/mitosheet/streamlit/streamlit.py
- mitosheet/mitosheet/streamlit/v1/spreadsheet.py
- trymito.io/components/StreamlitAppGallery/StreamlitAppGallery.tsx
Releases importing from a remote url
> Release Import Remote URL

- trymito.io/pages/index.tsx
> trymito: embed on desktop only

- trymito.io/pages/data-app.tsx
> Update streamlit title

- mitosheet/mitosheet/enterprise/license_key.py
- mitosheet/mitosheet/enterprise/mito_config.py
- mitosheet/mitosheet/tests/test_mito_config.py
- mitosheet/mitosheet/tests/test_ts_types.py
- mitosheet/mitosheet/user/__init__.py
- mitosheet/mitosheet/user/utils.py
Makes it so we support temp licenses.
Generate a set a temp license.
No.
> mitosheet: cleanup new config

- mitosheet/src/mito/pro/taskpanes/ConditionalFormatting/ConditionalFormattingCard.tsx
Changes the wording of the validation in the conditional formatting because it was a bit confusing.
> Update wording of validation in conditional formatting

- mitosheet/mitosheet/parser.py
- mitosheet/mitosheet/tests/test_parse.py
Adds ability to use TRUE and true in formulas in the same way that you can currently use True.
> Add support for TRUE and true as constants

- trymito.io/pages/data-app.tsx
- trymito.io/styles/DataApp.module.css
Adds the demo video to our website
> trymito: embed loom video

- mitosheet/setup.py
- Fixes Streamlit dependency issue
- Fixes XLSX writer issue here: https://github.com/mito-ds/mito/issues/911
Do setup, make sure works.
Nah.
> mitosheet: update dependencies to recent versions

- trymito.io/pages/blog.tsx
- trymito.io/pages/blog/[slug].tsx
Fixes basic href issues for blog.
Use blog.
No.
> trymito.io: update blogs with links and new paths

- .github/workflows/test-mitosheet-python.yml
- mitosheet/mitosheet/streamlit/streamlit.py
- mitosheet/mitosheet/tests/step_performers/import_steps/test_snowflake_import.py
We previously we're running optional feature dependency tests. Now, we are.
See new tests on CI.
> streamlit testing

- mitosheet/mitosheet/steps_manager.py
- trymito.io/pages/plans.tsx
Make code optimization os 
Try it. 
See tests.
No.
> mitosheet: make cope optimization os

- mitosheet/mitosheet/steps_manager.py
- trymito.io/pages/plans.tsx
> mitosheet/trymito: make code optimization open source

- mitosheet/mitosheet/code_chunks/step_performers/import_steps/excel_range_import_code_chunk.py
- mitosheet/mitosheet/public/v2/excel_utils.py
- mitosheet/mitosheet/tests/step_performers/import_steps/test_excel_range_import.py
- mitosheet/src/mito/components/taskpanes/ExcelRangeImport/ExcelRangeDynamicImportSection.tsx
Adds consecutive number of empty columns.
Use the feature on a good Excel test file you make for yourself. 
No.
> Consecutive empty columns

- mitosheet/css/mito.css
- mitosheet/mitosheet/errors.py
* Fixes CSS in toolbar button by adding fallback colors if the variable isn't defined. 
* Adds quotes into the error handling for replace to make it easier to read.
> Fix toolbar button bug and update error to include quotes

- mitosheet/css/footer.css
- mitosheet/dash_usage.py
- mitosheet/mitosheet/mito_backend.py
- mitosheet/mitosheet/mito_dash/v1/__init__.py
- mitosheet/mitosheet/mito_dash/v1/mito_callback.py
- mitosheet/mitosheet/mito_dash/v1/spreadsheet.py
- mitosheet/mitosheet/selectionUtils.py
- mitosheet/mitosheet/steps_manager.py
- mitosheet/mitosheet/tests/dash/test_dash.py
- mitosheet/mitosheet/types.py
- mitosheet/src/dash/MitoDashWrapper.tsx
- mitosheet/src/mito/components/elements/Dropdown.tsx
- mitosheet/src/mito/types.tsx
This is a reasonably sprawling PR that fixes a bunch of issues with our Dash integration:
1. Moves dropdowns from `absolute` positioning to `fixed` positioning, so that positioning works the same across JupyterLab and Streamlit as well as Dash. The issue was that JupyterLab never scrolls the actual window, nor does streamlit (as it's in an iframe) -- so we never previously had to deal with this case. 
2. Makes the `@mito_callback` work in more cases, by doing 0 manipulation of the Input and State arguments to the `@callback` function (which has a whole bunch of ways you can [pass these](https://dash.plotly.com/flexible-callback-signatures)). 
3. Makes `@mito_callback` give you an error message when you use `@callback` instead of it. Now, it actually tells you what is wrong -- so that you …
> Further Dash Fixes

- mitosheet/mitosheet/user/location.py
- mitosheet/src/mito/Mito.tsx
- mitosheet/src/mito/components/elements/ErrorBoundary.tsx
Turns off signup
Fixers error modal messaging
Remove ~/.mito/user.json and use dash.
> dash: turn off signup in dash

- mitosheet/src/mito/Mito.tsx
> mitosheet: fix dashboard signup

- mitoinstaller/mitoinstaller/log_utils.py
- mitosheet/mitosheet/telemetry/telemetry_utils.py
Disables all telemetry. 
Test no logs are sent out.
Should we update privacy policy?
> mitosheet: turn off telemetry

- .github/workflows/deploy-mitosheet-mitoinstaller.yml
Since our testing changed how things are built, we now need to NPM install and build.
Test from TestPyPi.
No.
> .github: fix deployment so it correctly builds JS assets

- mitosheet/mitosheet/mito_dash/v1/__init__.py
Makes it easy for Dash users to access the RunnableAnalysis class, namely for the `from_json` method.
Import it.
Doc updates!
> dash: add RunnableAnalysis to dash v1 interface

- mitosheet/mitosheet/api/get_parameterizable_params.py
- mitosheet/mitosheet/streamlit/streamlit.py
- mitosheet/mitosheet/streamlit/v1/spreadsheet.py
- mitosheet/mitosheet/tests/streamlit/test_runnable_analysis.py
- mitosheet/mitosheet/tests/test_transpile.py
Makes our impl match the type and docs.
Use it.
Cha.
> mitosheet: move from initial value to original value

- mitosheet/setup.py
Make sure we include the extension folders.
Merge it.
No.
> mitosheet: make sure setup.py includes correct filders

- mitosheet/setup.py
1. Adds Streamlit and Dash paths
2. Makes it so things work on JupyterLab and notebooks, by making sure our files get written to the correct place in the /share folder.
Merge, test on all platforms post deployment.
No.
> mitosheet: fix up setup again

- trymito.io/excel-to-python-page-contents/types.tsx
- trymito.io/pages/_app.tsx
- trymito.io/pages/excel-to-python/[...slug].tsx
- trymito.io/pages/plans.tsx
Remove intercom from the website since we don't use it anymore. 
> Glossary optimizations

- trymito.io/excel-to-python-page-contents/CONCAT.json
- trymito.io/excel-to-python-page-contents/HOUR.json
- trymito.io/excel-to-python-page-contents/LOWER.json
- trymito.io/excel-to-python-page-contents/REPLACE.json
- trymito.io/excel-to-python-page-contents/SUM.json
- trymito.io/pages/excel-to-python/[...slug].tsx
Adds first batch of pages to help users transition from Excel to Python by showing how to recreate Excel functionality in Python:
1. REPLACE
2. SUM
3. LOWER
4. CONCAT
5. HOUR
Review language / code + make edits directly
No.
> Glossary pages batch 1

- trymito.io/excel-to-python-page-contents/COUNT.json
- trymito.io/excel-to-python-page-contents/HOUR.json
- trymito.io/excel-to-python-page-contents/IF.json
- trymito.io/excel-to-python-page-contents/ISNA.json
- trymito.io/excel-to-python-page-contents/LOWER.json
- trymito.io/excel-to-python-page-contents/RANK.json
- trymito.io/pages/excel-to-python/[...slug].tsx
Adds more useful pages for users
- RANK
- IF
- COUNT
- IFNA
> Glossary batch 2

- trymito.io/pages/excel-to-python.tsx
> trymito: fix glossary links for html

- trymito.io/pages/blog.tsx
- trymito.io/pages/index.tsx
- trymito.io/pages/industries/financial-services.tsx
- trymito.io/pages/industries/life-sciences.tsx
- Update links from `data-apps` to `data-app`
- Add missing viewport width from blog.tsx 
Test links
None.
> Fix broken iternal links

- trymito.io/excel-to-python-page-contents/AVERAGE.json
- trymito.io/excel-to-python-page-contents/DAY.json
- trymito.io/excel-to-python-page-contents/FIND.json
- trymito.io/excel-to-python-page-contents/HOUR.json
- trymito.io/excel-to-python-page-contents/INDEX MATCH.json
- trymito.io/excel-to-python-page-contents/MAX.json
- trymito.io/excel-to-python-page-contents/MEDIAN.json
- trymito.io/excel-to-python-page-contents/MID.json
- trymito.io/excel-to-python-page-contents/MIN.json
- trymito.io/excel-to-python-page-contents/MINUTE.json
- trymito.io/excel-to-python-page-contents/MODE.json
- trymito.io/excel-to-python-page-contents/MONTH.json
- trymito.io/excel-to-python-page-contents/PRICE.json
- trymito.io/excel-to-python-page-contents/ROUND.json
- trymito.io/excel-to-python-page-contents/SECOND.json
- trymito.io/excel-to-python-page-contents/SIGN.json
- trymito.io/excel-to-python-page-contents/SUM.json
- trymito.io/excel-to-python-page-contents/TODAY.json
- trymito.io/excel-to-python-page-contents/YEAR.json
- trymito.io/pages/excel-to-python.tsx
- trymito.io/pages/excel-to-python/[...slug].tsx
Adds more pages to the Excel to Python glossary
> Glossary pages batch 3

- mitosheet/setup.py
Resolves https://github.com/mito-ds/mito/issues/966
Install 
No
> mitosheet: update dash dependency version

- trymito.io/pages/excel-to-python.tsx
- trymito.io/pages/excel-to-python/[...slug].tsx
- trymito.io/styles/ExcelToPython.module.css
Do a better job describing Mito in the Excel to Python glossary
See mobile and different browsers. 
No.
> Glossary page optimizations 2

- mitosheet/mitosheet/ai/recon.py
- mitosheet/mitosheet/step_performers/step_performer.py
- mitosheet/mitosheet/step_performers/user_defined_edit.py
- mitosheet/mitosheet/tests/step_performers/test_ai_transformation.py
Fixes https://github.com/mito-ds/mito/issues/997
See new test. Use AI transformation.
Nope.
> mitosheet: fix ai transformation

- mitosheet/mitosheet/mito_dash/v1/spreadsheet.py
- mitosheet/mitosheet/tests/dash/test_dash.py
- tests/dash-test.py
> dash: fix dash tests

- trymito.io/pages/_document.js
- trymito.io/pages/data-app.tsx
- trymito.io/pages/spreadsheet-automation.tsx
> Website optimizations 11 8

- trymito.io/components/CustomerCard/CustomerCard.tsx
- trymito.io/pages/customers.tsx
> Website optimizations 11 9

- trymito.io/components/CodeBlock/CodeBlock.module.css
- trymito.io/components/Glossary/HorizontalNav/HorizontalNav.tsx
- trymito.io/excel-to-python-page-contents/COUNTIF.json
- trymito.io/excel-to-python-page-contents/FILTER.json
- trymito.io/excel-to-python-page-contents/IFERROR.json
- trymito.io/excel-to-python-page-contents/LEFT.json
- trymito.io/excel-to-python-page-contents/MID.json
- trymito.io/excel-to-python-page-contents/PIVOT TABLE.json
- trymito.io/excel-to-python-page-contents/RIGHT.json
- trymito.io/excel-to-python-page-contents/SORT.json
- trymito.io/excel-to-python-page-contents/SUMIF.json
- trymito.io/excel-to-python-page-contents/TRIM.json
- trymito.io/excel-to-python-page-contents/types.tsx
- trymito.io/pages/excel-to-python.tsx
- trymito.io/pages/excel-to-python/[...slug].tsx
- trymito.io/styles/ExcelToPython.module.css
Adds pages for:
- pivot table
- filter
- sort
Fixes:
- spacing on mobile and desktop when there are large code lines
Check it. 
No.
> Glossary transformations batch 1

- mitosheet/mitosheet/public/v3/sheet_functions/misc_functions.py
- mitosheet/mitosheet/tests/public/v1/sheet_functions/misc_functions/test_type.py
- mitosheet/mitosheet/tests/public/v1/sheet_functions/test_functions_after_filter.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/misc_functions/test_type.py
Closes: https://github.com/mito-ds/mito/issues/1028
See new test.
No.
> mitosheet: handle None properly in TYPE function

- mitosheet/src/mito/components/import/FileBrowser/FileBrowser.tsx
Before:
After: <img width="359" alt="image" src="https://github.com/mito-ds/mito/assets/6673460/363c96d2-93eb-4b3a-ad2e-c54ec3608d0f">
> Fix import button overlap

- mitosheet/src/mito/utils/actions.tsx
Updates tooltips for:
* Specific graph types (Scatter, bar, line)
* Code snippets
* Anti-Merge button
* Percentage number format button
> Update tooltips to be more helpful

- trymito.io/pages/blog/[slug].tsx
- trymito.io/pages/excel-to-python/[...slug].tsx
> Website optimizations 11 16

- trymito.io/excel-to-python-page-contents/AVERAGE.json
- trymito.io/excel-to-python-page-contents/COUPNCD.json
- trymito.io/excel-to-python-page-contents/COUPNUM.json
- trymito.io/excel-to-python-page-contents/IRR.json
- trymito.io/excel-to-python-page-contents/MOD.json
- trymito.io/excel-to-python-page-contents/NPV.json
- trymito.io/excel-to-python-page-contents/REVERSE.json
- trymito.io/excel-to-python-page-contents/SLOPE.json
- trymito.io/excel-to-python-page-contents/SORT.json
- trymito.io/excel-to-python-page-contents/SUMPRODUCT.json
> Glossary pages batch 5

- mitosheet/mitosheet/mito_dash/v1/apps/app_timer_change.py
Adds new app in the docs. 
Run this app.
No.
> dash: add app timer change

- trymito.io/next.config.js
Implement 301 redirects according to the https://nextjs.org/docs/pages/api-reference/next-config-js/redirects#header-cookie-and-query-matching
Follow the [testing procedure here](https://chat.openai.com/share/beacdc36-0bfa-4cd8-84a7-609013b9fb34) to test locally before deploying
No
> 301 redirect

- trymito.io/next.config.js
test redirect approach by redirecting blog1.trymito.io
> trymito: add blog1 redirect

- trymito.io/pages/index.tsx
- trymito.io/pages/plans.tsx
> Add dash to website

- trymito.io/styles/[slug].module.css
Add styling for tables produced by ghost 
> trymito: add table styling for blogs

- trymito.io/components/Header/Header.tsx
Add navbar absolute links in the html
> trymito: update linking in toolbar

- mitosheet/css/footer.css
> Prevent selecting tab text on right click

- mitosheet/css/toolbar.css
> Fix text wrap on hover in tab bar

- mitosheet/src/mito/components/footer/Footer.tsx
- mitosheet/src/mito/components/footer/GraphSheetContextMenu.tsx
- mitosheet/src/mito/components/footer/SheetTab.tsx
- mitosheet/src/mito/components/footer/SheetTabContextMenu.tsx
- mitosheet/src/mito/types.tsx
- tests/streamlit_ui_tests/streamlit.spec.ts
Updates the context menus for sheet tabs to only be able to display one at a time.
> Only allow one sheet tab context menu to be open at a time

- mitosheet/src/mito/components/taskpanes/Graph/GraphExportTab.tsx
Make sure export graph as png works
Export a graph as a png
No.
> mitosheet: add export_graph_as_png

- mitosheet/src/mito/components/footer/SheetTab.tsx
> mitosheet: don't open sheet tab action if shift is pressed

- mitosheet/mitosheet/step_performers/graph_steps/plotly_express_graphs.py
Makes graph colors work correctly if streamlit is installed.
Closes https://github.com/mito-ds/mito/issues/1105
```
import streamlit
import mitosheet
```
Then, make a graph.
Do this on this branch, and on dev, to confirm we fixed it. 
No.
> Fix graph colors

- mitosheet/README.md
Updates the README to add instructions for running streamlit for dev.
> Update README.md to include streamlit instructions

- trymito.io/excel-to-python-page-contents/EXP.json
- trymito.io/pages/use-cases/python-training.tsx
- trymito.io/styles/globals.css
- Adds `POWER` to the `EXP` page
- Fixes bug that prevented code from being visible 
> POWER page

- trymito.io/components/Header/Header.tsx
- trymito.io/components/TranslucentButton/TranslucentButton.tsx
- trymito.io/pages/_document.js
> Tes Plausible goals

- trymito.io/components/CTAButtons/CTAButtons.tsx
- trymito.io/components/Header/Header.tsx
- trymito.io/components/TextButton/TextButton.tsx
- trymito.io/excel-to-python-page-contents/CEIL.json
- trymito.io/excel-to-python-page-contents/MID.json
- trymito.io/excel-to-python-page-contents/REPLACE.json
- trymito.io/excel-to-python-page-contents/ROUND.json
- trymito.io/excel-to-python-page-contents/TRIM.json
- trymito.io/excel-to-python-page-contents/VAR.json
- trymito.io/excel-to-python-page-contents/VLOOKUP.json
- trymito.io/pages/excel-to-python/[...slug].tsx
- trymito.io/pages/use-cases/python-training.tsx
- trymito.io/utils/plausible.tsx
Adds new glossary pages and improves popular existing ones. Also adds plausible classes.
Test the code. 
No.
> Glossary pages 1 13 24

- mitosheet/mitosheet/public/v1/sheet_functions/types/to_float_series.py
- mitosheet/mitosheet/public/v1/sheet_functions/types/utils.py
- mitosheet/mitosheet/public/v3/types/float.py
- mitosheet/mitosheet/tests/public/v3/sheet_functions/number_functions/test_float.py
- mitosheet/mitosheet/tests/step_performers/column_steps/test_change_column_dtype.py
Let users cast a string, "82%" to a float.  A user reported this bug today
See tests
> mitosheet: support % string to float

- trymito.io/components/CTACards/DashboardCTACard.tsx
- trymito.io/components/CTACards/DownloadCTACard.tsx
- trymito.io/pages/data-app.tsx
- trymito.io/pages/index.tsx
- trymito.io/pages/industries/financial-services.tsx
- trymito.io/pages/industries/life-sciences.tsx
- trymito.io/pages/infrastructure-integration-python-tool.tsx
- trymito.io/pages/low-code-sql.tsx
- trymito.io/pages/plans.tsx
- trymito.io/pages/python-ai-tools.tsx
- trymito.io/pages/spreadsheet-automation.tsx
- trymito.io/pages/teams.tsx
- trymito.io/pages/use-cases/python-training.tsx
- trymito.io/utils/plausible.tsx
> trymito: add plausible classes

- mitosheet/src/mito/components/import/XLSXImportConfigScreen.tsx
From error reduction [here](https://www.notion.so/trymito/1-18-23-0a188f54b53f4f3e94a74144866d3e36?pvs=4).
Nothing really.
Nothing.
> mitosheet: fix sheet crashing bug in excel import under rare conditions

- mitosheet/mitosheet/code_chunks/step_performers/import_steps/excel_import_code_chunk.py
- mitosheet/mitosheet/tests/step_performers/import_steps/test_excel_import.py
- Fix bug where single quote in Excel sheet name causes import to fail
See tests
No.
> mitosheet: fix single file in sheet name

- mitosheet/src/mito/components/toolbar/GraphTabs/GraphTypeConfigurations.tsx
Adds back the aggregation type (formerly hist function) to the graph configurations
> Add aggregation type to graph configuration

- mitosheet/css/toolbar.css
- mitosheet/src/mito/components/toolbar/GraphTabs/PlotFormatOptions.tsx
> Fix height inconsistencies between format tab options

- mitosheet/css/elements/TextButton.css
- mitosheet/css/taskpanes/DefaultTaskpane.css
- mitosheet/src/mito/components/taskpanes/FillNa/FillNaTaskpane.tsx
> Fix text button cutoff

- trymito.io/components/CTAButtons/CTAButtons.tsx
Adds plausible link to book a demo button 
Check it. 
No.
> Plausible book a demo

- mitosheet/mitosheet/__main__.py
- mitosheet/mitosheet/hello.py
- mitosheet/mitosheet/mito_backend.py
- mitosheet/mitosheet/step_performers/graph_steps/graph_utils.py
- mitosheet/mitosheet/telemetry/telemetry_utils.py
- trymito.io/components/CTAButtons/CTAButtons.tsx
- trymito.io/components/Footer/Footer.tsx
- trymito.io/components/Header/Header.tsx
- trymito.io/components/InstallInstructions/InstallInstructions.tsx
- trymito.io/pages/index.tsx
- trymito.io/utils/plausible.tsx
1. Adds install instrucitons
2. Adds the `hello` command
3. does not add email collection in hello command, just to not get too fancy for now
A few things here:
1. Test the new install instructions
2. Make sure the classes on buttons on the website are good
4. Make sure logging is good in the `hello` command, including adding failures
Should we update the docs as well/
> Pip install on main page

- tests/streamlit_ui_tests/add_column_tests.spec.ts
- tests/streamlit_ui_tests/utils.ts
Adds a few basic `add column tests` all using the context menu for now. 
Check them out. 
No.
> tests: ad add column tests

- trymito.io/components/CTAButtons/CTAButtons.tsx
- trymito.io/pages/plans.tsx
- trymito.io/utils/plausible.tsx
- Adds Book a Demo to plans page 
Test link
No.
> trymito: add book a demo to plans page

- tests/streamlit_ui_tests/toolbar/top.spec.ts
- Undo
- Redo
- Clear
- Steps
- Help button
- Search button
> Add toolbar top tests

- mitosheet/src/mito/components/taskpanes/CodeOptions/CodeOptionsTaskpane.tsx
- tests/streamlit_test.py
- tests/streamlit_ui_tests/taskpanes/code_config.spec.ts
- Add name to generated function
- Add parameter to generated function
Updates the streamlit app to also include the generated code
Updates the code config taskpane to pick up the first toggle
> Add code config tests

- mitosheet/src/mito/pro/taskpanes/SetDataframeFormat/SuggestedStyles.tsx
- tests/streamlit_ui_tests/taskpanes/formatting.spec.ts
- Adding a suggested style
- Adding a custom style to column headers
- Adding a custom style to rows
> Add formatting tests

- tests/streamlit_ui_tests/grid/set_column_formula_tests.spec.ts
- Adding a vlookup, navigating back to the original sheet, then pressing enter
- Adding a vlookup, pressing enter from the other sheet
- Trying to use cross-sheet formulas with non-vlookup
> Add cross sheet formula test

- mitosheet/setup.py
Remove a dependency we don't use. 
See tests still passing.
No changes.
> mitosheet: remove unused depedency for xlsx

- trymito.io/pages/excel-to-python/[...slug].tsx
Move up the CTA.
Look at the preview.
None.
> trymito.io: move up the mitosheet CTA

- mitosheet/css/taskpanes/Graph/GraphSidebar.css
- tests/streamlit_ui_tests/graph.spec.ts
Fixes #1273 and adds a test for it.
> Fix scrolling in select data taskpane of graph editor

- mitosheet/mitosheet/tests/streamlit/test_streamlit.py
- mitosheet/mitosheet/utils.py
Make sure the app works if you only have font_color set
See the test
No -- docs already say this is allowed
> mitosheet: fix bug with not supplying background_color

- mitosheet/src/mito/components/endo/EndoGrid.tsx
- tests/streamlit_ui_tests/grid/set_column_formula_tests.spec.ts
> Fix bug when double-clicking cell while cell editor is open

- mitosheet/mitosheet/pro/conditional_formatting_utils.py
- mitosheet/mitosheet/public/v3/formatting.py
- mitosheet/mitosheet/tests/streamlit/test_column_definitions.py
- mitosheet/mitosheet/utils.py
- mitosheet/src/mito/components/endo/focusUtils.tsx
1. Fix default int formatting export
2. Make conditional formats apply on string columns
3. fix weird scroll when Mito is tall
See new tests. Manually test the other two.
No.
> More bug fixes

- mitosheet/mitosheet/mito_backend.py
- mitosheet/mitosheet/steps_manager.py
- mitosheet/mitosheet/streamlit/v1/apps/column_definitions_app.py
- mitosheet/mitosheet/streamlit/v1/spreadsheet.py
- mitosheet/mitosheet/tests/step_performers/test_export_to_file.py
- mitosheet/mitosheet/tests/streamlit/test_streamlit.py
- mitosheet/mitosheet/tests/test_mito_backend.py
- mitosheet/mitosheet/types.py
- mitosheet/src/mito/components/endo/EndoGrid.tsx
- mitosheet/src/mito/components/endo/FormulaBar.tsx
- mitosheet/src/mito/components/endo/celleditor/CellEditor.tsx
- mitosheet/src/mito/components/endo/celleditor/cellEditorUtils.tsx
- mitosheet/src/mito/components/toolbar/FormulaTabContents.tsx
- mitosheet/src/mito/types.tsx
- mitosheet/src/mito/utils/actions.tsx
Let Streamlit app developer set the default cell editor to individual cell. 
See tests + existing test "'Edit individual cell only applied to edited cell and preserves formula and toggle on next open of cell editor'"
Yes -- we need to add documentation to the streamlit api
> mitosheet: set default_apply_formula_to_column

- trymito.io/components/InstallInstructions/InstallInstructions.tsx
> trymito: apply syntax highlighting to install commands

- trymito.io/components/CaseStudyCard/CaseStudies.tsx
> revert case studies

- trymito.io/pages/index.tsx
Moves up install instructions to be more clearly visible.
See preview.
No.
> Move up install instructions

- trymito.io/pages/_document.js
Adds warmly to our website as an experiment.
> trymito: add warmly

- trymito.io/pages/excel-to-python/[...slug].tsx
> Remove typeform excel to python glossary

- mitosheet/mitosheet/enterprise/telemetry/mito_log_uploader.py
- mitosheet/mitosheet/tests/test_mito_log_uploader.py
- mitosheet/pyproject.toml
- trymito.io/components/Header/Header.module.css
- trymito.io/components/Header/Header.tsx
Attempt to fix deployment issues by adding license to pyproject.toml
Merge into dev and see if deployment to test pypi passes.
> Fix deployment

- mitosheet/pyproject.toml
Fix the deployment procedure by upgrading twine version. 
Test by merging into dev. 
None.
> mitosheet: fix deployment

- mitosheet/mitosheet/mito_backend.py
- mitosheet/mitosheet/public/v3/sheet_functions/string_functions.py
- mitosheet/mitosheet/step_performers/utils/user_defined_function_utils.py
- mitosheet/mitosheet/tests/api/test_get_available_snowflake_options_and_defaults.py
- mitosheet/mitosheet/tests/operators/test_div.py
- mitosheet/mitosheet/tests/test_transpile.py
- mitosheet/mitosheet/transpiler/transpile_utils.py
- mitosheet/mitosheet/types.py
- mitosheet/setup.py
- mitosheet/src/mito/components/taskpanes/UserDefinedImport/UserDefinedFunctionParamConfigSection.tsx
- mitosheet/src/mito/types.tsx
Support `List[int]` and `Dict[str, str]` input types for custom importers 
Create imports that use each new input type. 
TODO: Update the docs.
> Custom import type expansion

- mitosheet/mitosheet/enterprise/license_key.py
- mitosheet/mitosheet/mito_backend.py
- mitosheet/mitosheet/public/v3/sheet_functions/string_functions.py
- mitosheet/mitosheet/step_performers/utils/user_defined_function_utils.py
- mitosheet/mitosheet/tests/api/test_get_available_snowflake_options_and_defaults.py
- mitosheet/mitosheet/tests/operators/test_div.py
- mitosheet/mitosheet/tests/test_transpile.py
- mitosheet/mitosheet/transpiler/transpile_utils.py
- mitosheet/mitosheet/types.py
- mitosheet/setup.py
- mitosheet/src/mito/components/taskpanes/UserDefinedImport/UserDefinedFunctionParamConfigSection.tsx
- mitosheet/src/mito/types.tsx
- Adds new types to the custom importers
> Release 8-29-24

- mitosheet/src/mito/Mito.tsx
- mitosheet/src/mito/components/toolbar/HomeTabContents.tsx
- mitosheet/src/mito/components/toolbar/Toolbar.tsx
- disable tours for all
- disable signup for dataframe renderer
Test out onboarding flows on dataframe render and mitosheet.sheet() calls
No.
> dogfood 10-8-24

- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
There are a certain class of bugs that occur and have fixes that are specific to Jupyter. This PR starts to let the mito-ai LLM know about these issues. 
No.
> mito-ai: teach mito-ai about operating inside of jupyter

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatMessage.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/CodeBlock.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- Fix bug with `reject ai generated code` button not returning code cell to correct state. 
Try it. 
No.
> Dogfood 10-25-24

- .github/workflows/test-mitosheet-frontend.yml
- mito-ai/src/Extensions/AiChat/AiChatPlugin.ts
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/Extensions/AiChat/ChatWidget.tsx
- mito-ai/src/Extensions/CellToolbarButtons/CellToolbarButtonsPlugin.tsx
- tests/README.md
- tests/jupyter_utils/jupyterlab_utils.ts
- tests/jupyter_utils/mitosheet_utils.ts
- tests/jupyterlab_ui_tests/jupyterlab.dataframe-render.spec.ts
- tests/jupyterlab_ui_tests/jupyterlab.mitosheet.spec.ts
- tests/jupyterlab_ui_tests/mitosheet.spec.ts
- tests/mac-setup.sh
- tests/mitoai_ui_tests/mitoai.spec.ts
- tests/mitoai_ui_tests/utils.ts
- tests/notebook_ui_tests/notebook.mitosheet.spec.ts
- tests/package.json
- tests/windows-setup.bat
Adds some basic integration tests for Mito AI + fixes up a few bugs caught in the process! 
See new tests! 
No.
> Integration Tests for Mito AI 

- evals/eval_types.py
- evals/main.py
- evals/prompts/__init__.py
- evals/prompts/multi_shot_prompt.py
- evals/prompts/single_shot_prompt.py
- evals/requirements.txt
- evals/utils.py
Creates a second prompt to let us improve the prompt comparison output.
Now, we generate a table like this: 
Try it out. 
No.
> Ai evals prompt comparrison

- tests/mitoai_ui_tests/mitoai.spec.ts
Test to make sure AI taskpane shortcut (CMD+E) is working.  
Run `CMD+E opens the AI chat` test.
N/A
> Added CMD+E test

- .github/workflows/test-mito-ai.yml
- tests/mitoai_ui_tests/mitoai.spec.ts
Use the correct keyboard shortcut for os
- Watch tests pass
No.
> tests: use the correct keyboard shortcut for os

- evals/ai_api_calls/get_open_ai_completion.py
- evals/prompts/inline_code_completion_prompts/__init__.py
- evals/prompts/inline_code_completion_prompts/prod_prompt_v3.py
- evals/test_cases/inline_code_completion_tests/dataframe_transformation_tests.py
- evals/test_runners/code_gen_test_runner.py
Improves the inline code completion prompt from 18% to 52%, that's a 188% improvement. 
We achieve this by: 
1. Providing variable context
2. Providing examples
3. Providing specific formatting instructions so that the AI formats the code with new line characters when needed. 
Try out the new prompt. 
No.
> Improve inline code complete prompt

- mito-ai/mito_ai/handlers.py
- mito-ai/mito_ai/utils/open_ai_utils.py
- mito-ai/mito_ai/utils/telemetry_utils.py
- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/prompts/SmartDebugPrompt.tsx
- tests/mitoai_ui_tests/aiInlineCompleter.spec.ts
Expanded logging to consider input location. Each log now has context appropriate fields. For example, the smart debugger with log the error and error type, while the sidebar chat will log the users query.  
The main logging changes can be found here: https://github.com/mito-ds/mito/blob/4ad1a0432b3ce110cdf53965e66d31dad48f20f1/mito-ai/mito_ai/utils/telemetry_utils.py#L132
A few things to consider:
- Logging only works for key type is `USER_KEY`. Server logging will be implemented in the next PR. 
- Mixpanel logging is [quite limited](https://docs.mixpanel.com/docs/data-structure/property-reference/data-type#string). To say on track, timeline wise, I've opted to ignore these constraints. After the other PRs in the shape are completed, I'll make a second pass, and see what can be done. For …
> Expand Logging: Add New Top-Level Logs

- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/prompts/ChatPrompt.tsx
Adds back Q&A prompts since it got deleted in a a merge resolution or something. 
Try out Q&A style prompts
No.
> mito-ai: add back q&a chat

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
Update placeholder text to teach people about @ mentions
> Update placeholder to discover @ mention

- mito-ai/mito_ai/providers.py
- mito-ai/mito_ai/utils/open_ai_utils.py
- mito-ai/mito_ai/utils/schema.py
Added a new field to the user file for inline completion trials. 
Clone this repo and play around with the user file. 
N/A
> Tracking first usage date

- trymito.io/pages/plans.tsx
Change pro pricing to $20 usd. 
Check it out. 
No.
> trymito: move pricing to 20 usd

- trymito.io/pages/plans.tsx
Updtes bullet points for each plan. 
N/A - Look at the plan page in preview
N/A
> Updated pricing page

- mito-ai/mito_ai/providers.py
Check to see if a user key is present before checking for server quota overages. 
Update the user file to simulate overages. 
N/A
> Updated quota checking logic

- evals/test_cases/inline_code_completion_tests/dataframe_transformation_tests.py
- evals/test_cases/inline_code_completion_tests/function_tests.py
- evals/test_runners/code_gen_test_runner.py
Analyzed the failing autocomplete evals here: https://www.notion.so/trymito/Analyzing-Failed-Inline-Code-Completion-Evals-17ad841c233680429ea2e6a680c61265?pvs=4
- Adds better infrastructure for learning from our evals
- Improves a few broken tests
Try it out if you want. 
No
> Prefix autocomplete evals

- mito-ai/style/ChatTaskpane.css
Fixes https://github.com/mito-ds/mito/issues/1462#issuecomment-2608768182
Send a message to the AI, then edit it. Flip between light and dark mode to make sure the colors look good.
N/A
> Fixed Dark Mode Edit Buttons 

- mitosheet/setup.py
- mitosheet/src/mito/utils/colors.tsx
Fixes the colors on Streamlit and Dash so that they don't rely on Jupyter css variables that are non existent. 
See the tests. 
No.
> Fix colors on streamlit and dash

- mito-ai/mito_ai/handlers.py
- mito-ai/mito_ai/models.py
- mito-ai/mito_ai/prompt_builders.py
- mito-ai/mito_ai/providers.py
- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- Added an agent mode toggle button in the chat taskpane header. 
- Added agent prompt.
- Updated webhook endpoints to handle agent requests.  
For now the agent mode button is just the help icon. This will be updated in my next PR handling the frontend.
Toggle agent mode, and send a request. You should see the response show up as a JSON object. 
No. Will document at the end.
> Agent Mode Backend

- .github/workflows/deploy-mitosheet-mitoinstaller.yml
> .github: fix bug in cd

- mitosheet/mitosheet/mito_backend.py
> mitosheet: fix bug with mitosheet not loading

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
A message is shown at the end of the agent plan, letting users know that agent mode will run code on their behalf. 
Use agent mode, look for last message. 
No
> Added Agent Disclaimer 

- tests/mitoai_ui_tests/agent.spec.ts
Added integration tests for agent mode. 
Run tests.
No
> Agent Mode: Tests

- .github/workflows/test-mito-ai.yml
Fixes bug in CI to ensure we test on Mito Server
See tests
No.
> .github: run workflow with and without server

- mito-ai/mito_ai/handlers.py
- mito-ai/mito_ai/providers.py
- mito-ai/mito_ai/utils/open_ai_utils.py
- mito-ai/mito_ai/utils/telemetry_utils.py
- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
1. `mito_ai_agent_prompt_success` for the first message that the user prompts to the agent
2. `mito_ai_agent_execution_success` for the future messages that the agent sends to execute it's plan
Send a message in agent mode, accept the plan, check the logs.
N/A
> Agent Mode: Logging

- mito-ai/mito_ai/models.py
- mito-ai/mito_ai/prompt_builders/agent_planning_prompt.py
- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
Passing the variable manager to the agent prompt. 
Create a notebook with content. Then send a message in agent mode. 
If you want to reference a variable in agent mode, make sure to run the cells to register the variable with the variable manager.  
No
> Notebook Variables in Agent Prompt

- mito-ai/mito_ai/handlers.py
- mito-ai/mito_ai/models.py
- mito-ai/mito_ai/utils/telemetry_utils.py
- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/Extensions/ErrorMimeRenderer/ErrorMimeRendererPlugin.tsx
- mito-ai/src/Extensions/ErrorMimeRenderer/errorUtils.tsx
- mito-ai/src/utils/agentActions.tsx
- mito-ai/src/utils/notebook.tsx
- mito-ai/src/utils/scroll.tsx
- mito-ai/src/utils/sleep.ts
- mito-ai/style/ChatTaskpane.css
- tests/mitoai_ui_tests/agent.spec.ts
> Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better.
Now when the agent it fails, it tries three times to fix itself. 
Try it out + see the new test. 
We need to add to agent mode documentation!
> Agent auto error fixing

- mito-ai/mito_ai/handlers.py
- mito-ai/mito_ai/models.py
- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/ChatMessage.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/Extensions/InlineCompleter/provider.ts
- mito-ai/src/utils/websocket/models.ts
- mito-ai/src/utils/websocket/websocketClient.ts
Stronger types for the web socket API
Test it. Ideally, we get our tests to a place where they are so strong that refactors like this (which shouldn't change any behavior) don't need any manual testing. 
No.
> Websocket api

- mito-ai/mito_ai/models.py
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/components/LoadingCircle.tsx
- mito-ai/src/utils/agentActions.tsx
- tests/mitoai_ui_tests/agent.spec.ts
Let's the user stop the agent's execution! Since we don't to close the websocket, if we're in the process of getting a response back from the Ai, we just wait for it and then send no further messages. 
Try it out + see two new tests! 
We should make when we release
> Stop agent

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/components/ToggleButton.tsx
- mito-ai/style/ChatInput.css
- mito-ai/style/ChatTaskpane.css
- mito-ai/style/ToggleButton.css
- tests/mitoai_ui_tests/agent.spec.ts
- tests/mitoai_ui_tests/utils.ts
- New toggle under chat input.
- Added a submit button.
- Added a cancel button to exit agent (planning phase). 
Toggle between chat and agent modes, and send some messages.
No
> Agent Mode Toggle

- mito-ai/style/ChatInput.css
Fix for https://github.com/mito-ds/mito/issues/1535
Select a code cell with content, enter chat mode. Make sure the border goes all the way around.
Do the same for agent mode.
N/A
> Fixed Chat Input Border 

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
Fixes https://github.com/mito-ds/mito/issues/1544
In Agent mode, send any prompt. Edit at least one of the steps to be something like "skip me." When the Agent executes this item in the plan it should not create a new cell. 
N/A
> Agent: No code, no cells

- mito-ai/mito_ai/models.py
- mito-ai/mito_ai/prompt_builders/agent_system_message.py
- mito-ai/mito_ai/providers.py
- mito-ai/mito_ai/utils/utils.py
- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/utils/strings.tsx
- mito-ai/src/utils/websocket/models.ts
- tests/playwright.config.js
Lets the Ai describe its steps as it works. This makes it a ton easier to follow! 
Try it out! 
When we release
> mito-ai: let the agent write a description

- mito-ai/src/Extensions/AiChat/ChatMessage/ChatMessage.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/Citation.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/MarkdownBlock.tsx
- mito-ai/src/utils/notebook.tsx
- mito-ai/style/Citation.css
Let the AI cite its work. When the user clicks on a citation, scroll the notebook there and highlight the correct line!
Add a few different code cells to your notebook. 
Then, add this code cell 
```
max_value = 1000
min_value = -1
average_value = 30
```
Then, add this input: 
The min value is -1 {"type": "citation", "cell_id": "<fill in cell id>", "line": 1} and the max_value is 1000  {"type": "citation", "cell_id": "<fill in cell id>", "line": 0}
When you click on each of those, it should take you that line in the notebook and highlight it purple for a few seconds. 
Once we merge in the backend PR, the agent will include these in its responses, and we will get conversations that look like this: 
Yes.
> Citations UI

- mito-ai/mito_ai/prompt_builders/agent_system_message.py
- mito-ai/mito_ai/providers.py
Now the Ai is instructed to create citation objects when it shares an insight with you. 
Try it out and then make sure that the citation it generates is reasonable.
Some things to pay attention to: 
1. The citation should not be included in a comment of the code. It should only appear in the chat. 
2. The citation line should go to the right line (I've noticed this incorrect a few times)
When we release
> Citation backend

- mito-ai/src/Extensions/AiChat/AiChatPlugin.ts
- tests/mitoai_ui_tests/misc.spec.ts
- tests/mitoai_ui_tests/mitoai.spec.ts
Automatically opens the AI Chat when Jupyter is launched. This will help users discover the AI Chat functionality, which they have historically struggled to do! 
Try it out + see the test. 
No.
> Auto open chat

- mito-ai/mito_ai/completion_handlers/chat_completion_handler.py
- mito-ai/mito_ai/models.py
- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/Extensions/AiChat/ChatMessage/PythonCode.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/utils/websocket/websocketClient.ts
Added streaming for chat messages. 
Clone this PR, and send a chat message. 
You may also need to run:
```bash
git pull origin streaming-user-key
```
> Streaming user key frontend - take 2

- mito-ai/mito_ai/completion_handlers/agent_auto_error_fixup_handler.py
- mito-ai/mito_ai/completion_handlers/agent_execution_handler.py
- mito-ai/mito_ai/completion_handlers/chat_completion_handler.py
- mito-ai/mito_ai/completion_handlers/code_explain_handler.py
- mito-ai/mito_ai/completion_handlers/inline_completer_handler.py
- mito-ai/mito_ai/completion_handlers/smart_debug_handler.py
- mito-ai/mito_ai/message_history.py
- mito-ai/mito_ai/providers.py
- mito-ai/mito_ai/tests/performance_test.py
- mito-ai/mito_ai/utils/telemetry_utils.py
> mito-ai: log thread_id

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- tests/mitoai_ui_tests/mitoai.spec.ts
Defaults the new chats to agent mode  
Try it out. 
Nope
> default to new chat to agent mode 

- mito-ai/mito_ai/completion_handlers/open_ai_models.py
Move to gpt 4.1
Make sure the functionality works. 
No
> mito-ai: move to gpt-4.1

- trymito.io/components/CTAButtons/CTAButtons.tsx
- trymito.io/pages/index.tsx
Add `jhub` to website
Check the preview
No
> trymito: add jhub link

- mito-ai/mito_ai/completion_handlers/chat_completion_handler.py
- mito-ai/mito_ai/completion_handlers/smart_debug_handler.py
- mito-ai/mito_ai/models.py
- mito-ai/mito_ai/prompt_builders/agent_system_message.py
- mito-ai/mito_ai/prompt_builders/chat_prompt.py
- mito-ai/mito_ai/prompt_builders/chat_system_message.py
- mito-ai/mito_ai/prompt_builders/prompt_constants.py
- mito-ai/mito_ai/prompt_builders/smart_debug_prompt.py
- mito-ai/mito_ai/tests/utils/test_message_history_utils.py
- mito-ai/mito_ai/utils/message_history_utils.py
- mito-ai/src/Extensions/AiChat/ChatHistoryManager.tsx
- mito-ai/src/utils/websocket/models.ts
Teach Chat Mode to provide citations as well. 
Ask some questions! 
No
> Citations in chat

- mito-ai/mito_ai/enterprise/utils.py
- mito-ai/mito_ai/providers.py
- mito-ai/mito_ai/tests/providers_test.py
Setting Azure OpenAI endpoint is an enterprise feature. 
See the tests + try setting the environment variables 
We will update on release
> Azure for enterprise

- mito-ai/mito_ai/providers.py
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
Fixes https://github.com/mito-ds/mito/issues/1647.
The loading message is now shown until the first chunk is received. 
Some scenarios to test:
1. Shows loading message when streaming: chat, smart debug, code explain.
2. Shows loading message when not streaming: chat, smart debug, code explain.
3. Shows error messages/upgrade when streaming.
4. Shows error messages/upgrade when not streaming. 
N/A
> Loading message fix (streaming)

- mitosheet/mitosheet/is_type_utils.py
- mitosheet/mitosheet/utils.py
Resolves https://github.com/mito-ds/mito/issues/1654
See instructions in GitHub issue
No.
> mitosheet: serialize period columns

- mito-ai/pyproject.toml
- mito-ai/schema/toolbar-buttons.json
- mito-ai/src/Extensions/ToolbarButtons/ToolbarButtonsPlugin.tsx
The build system refactor that I did broke all of the toolbar buttons we added through the `toolbar-buttons.json` file: Deploy App, Accept, Reject, explain code
Make sure those buttons are there again! 
No
> fix buttons

- .github/workflows/deploy-mito-ai.yml
- deployment/bump_version.py
- deployment/deploy.py
- deployment/deploy_hatch.py
- deployment/utils.py
- mito-ai/package.json
- mito-ai/pyproject.toml
Update deployment scripts for hatchling because it has a different build command. 
No.
> update deployment scripts for hatchling

- mito-ai/mito_ai/anthropic_client.py
This PR makes two primary changes:
1. Instead of flattening the entire conversation_history into one big string and sending that as a single message to anthropic, we follow the standard of sending a system message to the `system` param and then sending a list of messages from the user and assistant. 
2. Now that we are properly sending the system message which already includes a lot of examples on how to respond (ie, [here](https://github.com/mito-ds/mito/blob/8179b711e878bac331f6ea7d436e7ec6b89cea7c/mito-ai/mito_ai/completions/prompt_builders/agent_system_message.py#L62)) with the AgentResponse type, it seems like we don't need those additional examples. Nice!
> mito-ai: claude message redux

- mito-ai/mito_ai/db/crawlers/snowflake.py
- mito-ai/mito_ai/db/handlers.py
- mito-ai/mito_ai/db/utils.py
- mito-ai/mito_ai/utils/telemetry_utils.py
Added basic logging when users connect to db:
1. Log attempted database connections
2. Log successful database connections
3. Log unsuccessful database connections
Need to test:
- correct db creds:  should log `mito_ai_db_connection_attempt` and `mito_ai_db_connection_success`.
- incorrect db cred: should log `mito_ai_db_connection_attempt` and `mito_ai_db_connection_error`.
N/A
> DB logging

- mito-ai/mito_ai/__init__.py
- mito-ai/src/websockets/appBuilder/appBuilderWebsocketClient.ts
- mito-ai/src/websockets/completions/CompletionsWebsocketClient.ts
Standardize Service URLs
Try it out! 
No
> Update service url

- mito-ai/mito_ai/enterprise/utils.py
- mito-ai/mito_ai/utils/version_utils.py
Lets organizations that have mitosheet-private installed experiment with setting an Azure endpoint.
> Support azure on mitosheet-private

- trymito.io/components/AIInputField/AIInputField.module.css
- trymito.io/components/AIInputField/AIInputField.tsx
- trymito.io/components/Buttons/TextButton/TextButton.module.css
- trymito.io/components/Buttons/TextButton/TextButton.tsx
- trymito.io/components/CTAButtons/CTAButtons.tsx
- trymito.io/components/FeatureSquares/FeatureSquares.tsx
- trymito.io/components/Header/Header.tsx
- trymito.io/next-env.d.ts
- trymito.io/pages/index.tsx
- Updates the website title card
- Removed the outdated Product and Use Cases sections from the Nav Bar 
Once released, when the user inputs a message in the chat, it will redirect them to JupyterHub which will start with their input already sent to the agent. 
Check it out. 
> Website input field polish

- mito-ai/pyproject.toml
- Updated hatchling from 1.5.0 -> 1.27.0
- Removed snowflake-sqlalchemy
> Updated hatchling

- .github/workflows/test-mito-ai-backend.yml
- mito-ai/mito_ai/tests/db/postgres_test.py
- mito-ai/mito_ai/tests/db/test_db_constants.py
- Moved databases to AWS RDS, and updated env vars.
- Added windows tests.
See checks below.
N/A
> Added Windows Runner to Backend Tests

- mito-ai/src/Extensions/AppBuilder/NotebookToStreamlit.tsx
- mito-ai/src/Extensions/AppBuilder/requirementsUtils.tsx
This is a small PR with a few console logs added to figure out where we could be erroring out while creating the requirements.txt and app.py files.
> Adding console logs

- mito-ai/mito_ai/anthropic_client.py
- mito-ai/mito_ai/tests/test_anthropic_client.py
- mito-ai/mito_ai/tests/test_gemini_client.py
- tests/requirements.txt
This is in order to fix https://github.com/mito-ds/mito/issues/1758
N/A
> Anthropic image input fix

- mito-ai/mito_ai/tests/utils/test_gemini_utils.py
Fixed the failing gemini pytest
N/A
> Fixed the failing gemini pytest

- .github/workflows/test-mito-ai-mypy.yml
- mito-ai/.eslintrc.js
- mito-ai/mito_ai/constants.py
- mito-ai/mito_ai/gemini_client.py
- mito-ai/mito_ai/log/handlers.py
- mito-ai/mito_ai/rules/handlers.py
- mito-ai/mito_ai/settings/handlers.py
- mito-ai/mito_ai/settings/utils.py
- mito-ai/mito_ai/tests/db/conftest.py
- mito-ai/mito_ai/tests/utils/test_gemini_utils.py
- mito-ai/mito_ai/utils/gemini_utils.py
- mito-ai/mito_ai/utils/telemetry_utils.py
- mito-ai/mypy.ini
- mito-ai/pyproject.toml
- mito-ai/src/Extensions/AppBuilder/requirementsUtils.tsx
- mito-ai/src/components/NextStepsPills.tsx
- mito-ai/src/tests/NotebookFooter/notebookFooter.test.tsx
- tests/mac-setup.sh
- Fixes a bunch of failing mypy, jest, and pytests. 
- Updates the CI testing workflow so that we should get the same results locally as we do on CI
> Fix non-gemini mypy, jest, and pytests

- mitosheet/src/plugin.tsx
Fix Mitosheet. Without this fix, the new mitosheet button does not work and the mitosheet says the error "invalid installation"
Try it and make sure the tests pass
> Fix mitosheet button

- mito-ai/mito_ai/anthropic_client.py
- mito-ai/mito_ai/gemini_client.py
- mito-ai/mito_ai/tests/test_gemini_client.py
- mito-ai/mito_ai/utils/gemini_utils.py
This is a PR to fix the failing mypy checks
> Gemini mypy fixes

- mito-ai/mito_ai/completions/prompt_builders/agent_system_message.py
- mito-ai/mito_ai/completions/prompt_builders/prompt_constants.py
- mito-ai/src/Extensions/AiChat/ChatMessage/Citation.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/utils/notebook.tsx
We used to have a bunch of mostly duplicate logic for highlighting and scrolling to cells depending on whether it was an entire code cell, a single line, or a range of lines. This just simplifies things by handling them all the same way. 
Try it out! 
Nope
> Merge fix scroll 2

- mito-ai/mito_ai/completions/models.py
- mito-ai/mito_ai/constants.py
- mito-ai/mito_ai/tests/message_history/test_generate_short_chat_name.py
- mito-ai/src/Extensions/AiChat/ChatMessage/ScrollableSuggestions.tsx
- mito-ai/src/websockets/completions/CompletionModels.ts
> Cleanup 6 26 25

- mito-ai/mito_ai/constants.py
- mito-ai/mito_ai/tests/test_constants.py
Use the production lambda function and make sure we don't accidentally switch to dev lambda function again in the future!
Check it out. 
No.
> mito-ai: update lambda url and tests

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
> mito-ai: fix weakmap error with try block

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
> Fix weak map error

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
> mito-ai: try to fix weakmap by using cell id instead of cell

- mito-ai/src/utils/waitForNotebookReady.ts
> mito-ai: wait for notebook to be ready

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/Extensions/AiChat/utils.tsx
- mito-ai/src/tests/AiChat/getBase64EncodedCellOutput.test.tsx
Makes sure that we return the cell output of the cell requested by the AI, instead of whatever the active cell is. Often those are the same, but not always!
See the new tests
No
> mito-ai: fix bug with get cell output tool

- .github/workflows/deploy-mitosheet-mitoinstaller.yml
> .github: remove mitoinstaller deploy

- mito-ai/mito_ai/app_builder/handlers.py
- mito-ai/mito_ai/app_builder/models.py
- mito-ai/mito_ai/streamlit_conversion/streamlit_agent_handler.py
- mito-ai/mito_ai/streamlit_conversion/streamlit_utils.py
- mito-ai/mito_ai/streamlit_preview/handlers.py
- mito-ai/mito_ai/streamlit_preview/manager.py
- mito-ai/mito_ai/tests/streamlit_conversion/test_streamlit_agent_handler.py
- mito-ai/mito_ai/tests/streamlit_conversion/test_streamlit_utils.py
- mito-ai/mito_ai/tests/streamlit_preview/test_streamlit_preview_manager.py
- mito-ai/src/Extensions/AppBuilder/NotebookToStreamlit.tsx
- mito-ai/src/Extensions/ToolbarButtons/ToolbarButtonsPlugin.tsx
- mito-ai/src/tests/AppBuilder/NotebookToStreamlit.test.tsx
- mito-ai/src/websockets/appBuilder/appBuilderModels.ts
Instead of previewing the app in a temporary directory, it previews the app in the users's working directory so that they have access to all of their required files!  
Try it out with a notebook that imports a csv file. 
No.
> Reuse workspace

- mito-ai/mito_ai/__init__.py
- mito-ai/mito_ai/log/handlers.py
- mito-ai/mito_ai/log/urls.py
- mito-ai/src/Extensions/AiChat/ChatMessage/RevertQuestionnaire.tsx
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/components/TextButton.tsx
- mito-ai/src/tests/AiChat/RestoreCheckpoint.test.tsx
- mito-ai/src/utils/checkpoint.tsx
- mito-ai/style/RevertQuestionnaire.css
- mito-ai/style/TextButton.css
- mito-ai/style/button.css
Logging when a user clicks revert, then showing a questionnaire.
Send a question in Agent mode, and hit revert. 
N/A
> Revert Logging + Questionnaire 

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
> mito-ai: clear questionare on new chat

- mito-ai/src/Extensions/SettingsManager/database/ConnectionList.tsx
- mito-ai/src/Extensions/SettingsManager/database/DatabasePage.tsx
- mito-ai/src/Extensions/SettingsManager/database/GettingStartedVideo.tsx
- mito-ai/style/DatabasePage.css
Added setup video to the database page. 
- When you have a database already connected, there is a _Getting Started_ button in the header.
- Remove all database connections, you should see the video in the body of the page. 
Yes, I've already added the video to the docs.
> Database Setup Video 

- mito-ai/style/ModelSelector.css
- mito-ai/style/ToggleButton.css
Make the model selector appear with full model name more. 
Double check me that it all fits on the screen.
> mito-ai: even more model space

- mito-ai/mito_ai/completions/message_history.py
- mito-ai/mito_ai/tests/message_history/test_message_history_utils.py
- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
Resolves https://github.com/mito-ds/mito/issues/1846
Follow the steps in the GitHub issue. 
Nope, just a bug fix.
> mito-ai: restore agent mode on refresh

- mito-ai/src/Extensions/AiChat/ChatTaskpane.tsx
- mito-ai/src/Extensions/SettingsManager/SettingsManagerPlugin.tsx
- mito-ai/src/Extensions/SettingsManager/SettingsWidget.tsx
- mito-ai/src/Extensions/SettingsManager/profiler/CapturedRequestsSection.tsx
- mito-ai/src/Extensions/SettingsManager/profiler/ContextManagerSection.tsx
- mito-ai/src/Extensions/SettingsManager/profiler/ProfilerPage.tsx
- mito-ai/src/utils/constants.ts
- mito-ai/style/ProfilerPage.css
Sometimes we forget how much goes into constructing prompts, the profiler provides a snapshot of all the things.
The profiler has two main components:
1. Context Manager - This is a view of everything in the context manager. 
2. Captured Completion Requests - The object sent to the backend, including the prompt, variables, etc. As long as you have the profiler open, it will automatically capture these requests. 
The profiler should be open alongside your notebook when doing any testing. Switching between tabs in Jupyter will cause certain values to disappear. 
1. Send a few requests with the profiler open, make sure they are being captured.
2. Add variables to a notebook, make sure they show up in the profiler. 
4. Do a small workflow without the profiler open, to make sure nothing was …
> Profiler MVP
